.\"
.\" Japanese Version Copyright (c) 2002 Yuichi SATO
.\"         all rights reserved.
.\" Translated Sun Nov 10 04:11:05 JST 2002
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.TH APPLE_CP 1 "15 Oct 2001" "Netatalk 1.5"
.\"O .SH NAME
.SH 名前
.\"O apple_cp \- Do an apple copy, copying the resource fork as well
apple_cp \- apple ファイルをコピーし、リソースフォークもコピーする
.\"O .SH SYNOPSIS
.SH 書式
.BR /usr/bin/apple_cp
\fISOURCE DEST\fR
.br
.BR /usr/bin/apple_cp
\fISOURCE\fR... \fIDIRECTORY\fR

.\"O .SH DESCRIPTION
.SH 説明
.\"O .BR apple_cp
.\"O is a perl script to copy SOURCE to DEST or multiple SOURCE(s) to
.\"O DIRECTORY. It also copies the resource forks to the .AppleDouble
.\"O directory for DEST or DIRECTORY. If the .AppleDouble directory doesn't
.\"O exist for DEST or DIRECTORY it will create it.
.B apple_cp
は perl スクリプトであり、
SOURCE を DEST へコピーしたり、
複数の SOURCE を DIRECTORY へコピーしたりする。
またリソースフォークを DEST や DIRECTORY の
\&.AppleDouble ディレクトリへコピーする。
DEST や DIRECTORY に .AppleDouble ディレクトリがなければ、作成する。

.\"O .SH EXAMPLES
.SH 例

.BR /usr/bin/apple_cp
test.text /target/directory/

.BR /usr/bin/apple_cp
test.text /target/directory/test2.text

.BR /usr/bin/apple_cp
test.text testing.text /target/directory/

.\"O .SH REPORTING BUGS
.SH バグ報告
.\"O Report bugs to the Netatalk-devel list <netatalk-devel@lists.sourceforge.net>.
バグは Netatalk-devel メーリングリスト
<netatalk-devel@lists.sourceforge.net> へ報告してください。

.\"O .SH SEE ALSO
.SH 関連項目
.BR apple_mv (1),
.BR apple_rm (1).
