#
# Copyright (c) 2021 Linux JM project
#         all rights reserved.
#
PACKAGE_NAME    = which
PACKAGE_VERSION = 2.21
PACKAGE_DATE    = 2015/03/21

AUTHOR_NAME  = "Linux JM project"
AUTHOR_EMAIL = "linuxjm-discuss@lists.osdn.me"

man_numbers = 1
man1_sources = \
	which

THRESH = 100
EXTFLAGS =
PO4A_FLAGS  = -M UTF-8 -k $(THRESH)
PO4A_FLAGS += $(EXTFLAGS)
LANGS = ja

include po4a.mk
