.\"O .TH "DMESG" "1" "2021-07-20" "util\-linux 2.37.2" "User Commands"
.\"O .ie \n(.g .ds Aq \(aq
.\"O .el       .ds Aq '
.\"O .ss \n[.ss] 0
.\"O .nh
.\"O .ad l
.\"O .de URL
.\"O \fI\\$2\fP <\\$1>\\$3
.\"O ..
.\"O .als MTO URL
.\"O .if \n[.g] \{\
.\"O .  mso www.tmac
.\"O .  am URL
.\"O .    ad l
.\"O .  .
.\"O .  am MTO
.\"O .    ad l
.\"O .  .
.\"O .  LINKSTYLE blue R < >
.\"O .\}
.TH DMESG 1 2021\-07\-20 "util\-linux 2.37.2" ユーザーコマンド
.ie  \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de  URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if  \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.\"O ----------------------------------------
.\"O .SH "NAME"
.\"O dmesg \- print or control the kernel ring buffer
.SH 名前
dmesg \- カーネルの (ログ用) リングバッファーの表示や制御を行う
.\"O ----------------------------------------
.\"O .SH "SYNOPSIS"
.\"O .sp
.\"O \fBdmesg\fP [options]
.\"O .sp
.\"O \fBdmesg\fP \fB\-\-clear\fP
.\"O .sp
.\"O \fBdmesg\fP \fB\-\-read\-clear\fP [options]
.\"O .sp
.\"O \fBdmesg\fP \fB\-\-console\-level\fP \fIlevel\fP
.\"O .sp
.\"O \fBdmesg\fP \fB\-\-console\-on\fP
.\"O .sp
.\"O \fBdmesg\fP \fB\-\-console\-off\fP
.SH 書式
.sp
\fBdmesg\fP [options]
.sp
\fBdmesg\fP \fB\-\-clear\fP
.sp
\fBdmesg\fP \fB\-\-read\-clear\fP [options]
.sp
\fBdmesg\fP \fB\-\-console\-level\fP \fIlevel\fP
.sp
\fBdmesg\fP \fB\-\-console\-on\fP
.sp
\fBdmesg\fP \fB\-\-console\-off\fP
.\"O ----------------------------------------
.\"O .SH "DESCRIPTION"
.\"O .sp
.\"O \fBdmesg\fP is used to examine or control the kernel ring buffer.
.\"O .sp
.\"O The default action is to display all messages from the kernel ring buffer.
.SH 説明
.sp
\fBdmesg\fP は、カーネルのリングバッファーを調べたり、制御したりするために使用する。
.sp
デフォルトの動作は、カーネルのリングバッファーにあるすべてのメッセージを表示することである。
.\"O ----------------------------------------
.\"O .SH "OPTIONS"
.\"O .sp
.\"O The \fB\-\-clear\fP, \fB\-\-read\-clear\fP, \fB\-\-console\-on\fP, \fB\-\-console\-off\fP, and \fB\-\-console\-level\fP options are mutually exclusive.
.\"O .sp
.\"O \fB\-C\fP, \fB\-\-clear\fP
.SH オプション
.sp
\fB\-\-clear\fP, \fB\-\-read\-clear\fP, \fB\-\-console\-on\fP, \fB\-\-console\-off\fP,
\fB\-\-console\-level\fP は、どれか一つしか使えない。
.sp
\fB\-C\fP, \fB\-\-clear\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Clear the ring buffer.
.RS 4
リングバッファーをクリアする。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-c\fP, \fB\-\-read\-clear\fP
.RE
.sp
\fB\-c\fP, \fB\-\-read\-clear\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Clear the ring buffer after first printing its contents.
.RS 4
まずリングバッファーの内容を表示し、その後でクリアする。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-D\fP, \fB\-\-console\-off\fP
.RE
.sp
\fB\-D\fP, \fB\-\-console\-off\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Disable the printing of messages to the console.
.RS 4
コンソールへのメッセージ出力を抑止する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-d\fP, \fB\-\-show\-delta\fP
.RE
.sp
\fB\-d\fP, \fB\-\-show\-delta\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display the timestamp and the time delta spent between messages. If used together with \fB\-\-notime\fP then only the time delta without the timestamp is printed.
.RS 4
タイムスタンプとともに、前のメッセージ出力から経過した時間の増分 (time delta) を表示する。\fB\-\-notime\fP
と一緒に使用した場合は、タイムスタンプは省略して、時間の増分だけを表示する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-E\fP, \fB\-\-console\-on\fP
.RE
.sp
\fB\-E\fP, \fB\-\-console\-on\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Enable printing messages to the console.
.RS 4
コンソールへのメッセージ出力を有効にする。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-e\fP, \fB\-\-reltime\fP
.RE
.sp
\fB\-e\fP, \fB\-\-reltime\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display the local time and the delta in human\-readable format. Be aware that conversion to the local time could be inaccurate (see \fB\-T\fP for more details).
.RS 4
ローカルタイムと時間の増分を人間に読みやすいフォーマットで表示する。 ローカルタイムへの変換は不正確かもしれないことに気をつけること (詳しくは
\fB\-T\fP を参照)。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-F\fP, \fB\-\-file\fP \fIfile\fP
.RE
.sp
\fB\-F\fP, \fB\-\-file\fP \fIfile\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Read the syslog messages from the given \fIfile\fP. Note that \fB\-F\fP does not support messages in kmsg format. The old syslog format is supported only.
.RS 4
指定されたファイル \fIfile\fP から syslog のメッセージを読み込む。 \fB\-F\fP は、kmsg
フォーマットのメッセージをサポートしていないことに気をつけること。 サポートしているのは、昔ながらの syslog フォーマットだけである。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-f\fP, \fB\-\-facility\fP \fIlist\fP
.RE
.sp
\fB\-f\fP, \fB\-\-facility\fP \fIlist\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Restrict output to the given (comma\-separated) \fIlist\fP of facilities. For example:
.\"O .sp
.\"O \fBdmesg \-\-facility=daemon\fP
.\"O .sp
.\"O will print messages from system daemons only. For all supported facilities see the \fB\-\-help\fP output.
.RS 4
出力を指定されたファシリティの (コンマで区切った) リストに限定する。たとえば、
.sp
\fBdmesg \-\-facility=daemon\fP
.sp
は、システムデーモンのメッセージのみを表示する。 どんなファシリティがサポートされているかについては、\fB\-\-help\fP の出力を参照のこと。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-H\fP, \fB\-\-human\fP
.RE
.sp
\fB\-H\fP, \fB\-\-human\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Enable human\-readable output. See also \fB\-\-color\fP, \fB\-\-reltime\fP and \fB\-\-nopager\fP.
.RS 4
読みやすい出力にする。 \fB\-\-color\fP, \fB\-\-reltime\fP, \fB\-\-nopager\fP も参照のこと。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-k\fP, \fB\-\-kernel\fP
.RE
.sp
\fB\-k\fP, \fB\-\-kernel\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Print kernel messages.
.RS 4
カーネルメッセージを表示する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-L\fP, \fB\-\-color\fP[=\fIwhen\fP]
.RE
.sp
\fB\-L\fP, \fB\-\-color\fP[=\fIwhen\fP]
.\"O ----------------------------------------
.\"O .RS 4
.\"O Colorize the output. The optional argument \fIwhen\fP can be \fBauto\fP, \fBnever\fP or \fBalways\fP. If the \fIwhen\fP argument is omitted, it defaults to \fBauto\fP. The colors can be disabled; for the current built\-in default see the \fB\-\-help\fP output. See also the \fBCOLORS\fP section below.
.RS 4
出力をカラー表示にする。 指定が任意の引数 \fIwhen\fP には、\fBauto\fP, \fBnever\fP, \fBalways\fP が使える。 引数
\fIwhen\fP が省略された場合は、デフォルトの \fBauto\fP が使用される。 カラー表示は無効にすることもできる。
プログラムに埋め込まれた現在のデフォルトが有効か無効かを知るには、 \fB\-\-help\fP の出力を見ればよい。
下記の「\fBカラー表示\fP」セクションも参照のこと。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-l\fP, \fB\-\-level\fP \fIlist\fP
.RE
.sp
\fB\-l\fP, \fB\-\-level\fP \fIlist\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Restrict output to the given (comma\-separated) \fIlist\fP of levels. For example:
.\"O .sp
.\"O \fBdmesg \-\-level=err,warn\fP
.\"O .sp
.\"O will print error and warning messages only. For all supported levels see the \fB\-\-help\fP output.
.RS 4
出力を、 指定されたレベルの (コンマで区切った) リストに限定する。 たとえば、
.sp
\fBdmesg \-\-level=err,warn\fP
.sp
は、error と warning メッセージのみを表示する。どんなレベルがサポートされているかについては、\fB\-\-help\fP の出力を参照のこと。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-n\fP, \fB\-\-console\-level\fP \fIlevel\fP
.RE
.sp
\fB\-n\fP, \fB\-\-console\-level\fP \fIlevel\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Set the \fIlevel\fP at which printing of messages is done to the console. The \fIlevel\fP is a level number or abbreviation of the level name. For all supported levels see the \fB\-\-help\fP output.
.\"O .sp
.\"O For example, \fB\-n 1\fP or \fB\-n emerg\fP prevents all messages, except emergency (panic) messages, from appearing on the console. All levels of messages are still written to \fI/proc/kmsg\fP, so \fBsyslogd\fP(8) can still be used to control exactly where kernel messages appear. When the \fB\-n\fP option is used, \fBdmesg\fP will \fInot\fP print or clear the kernel ring buffer.
.RS 4
コンソールに出力されるログメッセージのレベル (重大度) を \fIlevel\fP に設定する。 \fIlevel\fP
に指定するのは、数値のレベルか、レベルの名称の短縮形である。 どんなレベルがサポートされているかについては、 \fB\-\-help\fP の出力を参照のこと。
.sp
たとえば、\fB\-n 1\fP や \fB\-n emerg\fP を指定すると、emergency (panic)
以外のすべてのメッセージが、コンソールに表示されなくなる。すべてのレベルのメッセージが \fI/proc/kmsg\fP
に書き込まれることに変わりはないので、 カーネルメッセージをどこに出力するかは、 \fBsyslogd\fP(8) 使って適切にコントロールすることができる。
\fB\-n\fP オプションを使用したときには、 \fBdmesg\fP がカーネルのリングバッファーを表示したり、クリアしたりすることはない。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-\-noescape\fP
.RE
.sp
\fB\-\-noescape\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O The unprintable and potentially unsafe characters (e.g., broken multi\-byte sequences, terminal controlling chars, etc.) are escaped in format \(rsx<hex> for security reason by default. This option disables this feature at all. It\(cqs usable for example for debugging purpose together with \fB\-\-raw\fP. Be careful and don\(cqt use it by default.
.RS 4
非表示文字や問題を起こしかねない文字 (たとえば、破損したマルチバイトシーケンスや、端末制御文字など) は、デフォルトではセキュリティ上の理由から
\(rsx<hex> の形式でエスケープされるようになっている。このオプションはその機能を完全に無効にする。 このオプションは、たとえば
\fB\-\-raw\fP と併せて、デバッグのために使用できる。 使用には気を付けること。デフォルトで使うようにしてはいけない。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-P\fP, \fB\-\-nopager\fP
.RE
.sp
\fB\-P\fP, \fB\-\-nopager\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Do not pipe output into a pager. A pager is enabled by default for \fB\-\-human\fP output.
.RS 4
出力をパイプでページャーに渡さない。 \fB\-\-human\fP の出力では、ページャーはデフォルトで使用される。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-p\fP, \fB\-\-force\-prefix\fP
.RE
.sp
\fB\-p\fP, \fB\-\-force\-prefix\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Add facility, level or timestamp information to each line of a multi\-line message.
.RS 4
複数行メッセージの各行にファシリティ、レベル、タイムスタンプの情報を付け加える。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-r\fP, \fB\-\-raw\fP
.RE
.sp
\fB\-r\fP, \fB\-\-raw\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Print the raw message buffer, i.e., do not strip the log\-level prefixes, but all unprintable characters are still escaped (see also \fB\-\-noescape\fP).
.\"O .sp
.\"O Note that the real raw format depends on the method how \fBdmesg\fP reads kernel messages. The \fI/dev/kmsg\fP device uses a different format than \fBsyslog\fP(2). For backward compatibility, \fBdmesg\fP returns data always in the \fBsyslog\fP(2) format. It is possible to read the real raw data from \fI/dev/kmsg\fP by, for example, the command \(aqdd if=/dev/kmsg iflag=nonblock\(aq.
.RS 4
メッセージバッファーを未加工 (raw) のまま表示する。 すなわち、ログレベルを表す接頭辞を取り除かない。
ただし、すべての非表示文字がエスケープされることには変わりがない (\fB\-\-noescape\fP も参照)。
.sp
注意してほしいが、実際の未加工フォーマットは、\fBdmesg\fP がカーネルメッセージを読み出す方法によって違ってくる。デバイス \fI/dev/kmsg\fP
と \fBsyslog\fP(2) では、違ったフォーマットを使っているのである。 ただし、後方互換のため、\fBdmesg\fP は、常に
\fBsyslog\fP(2) のフォーマットでデータを返すようになっている。 \fI/dev/kmsg\fP にある本当の未加工データは、 たとえば \(aqdd
if=/dev/kmsg iflag=nonblock\(aq といったコマンドを使えば、読むことができる。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-S\fP, \fB\-\-syslog\fP
.RE
.sp
\fB\-S\fP, \fB\-\-syslog\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Force \fBdmesg\fP to use the \fBsyslog\fP(2) kernel interface to read kernel messages. The default is to use \fI/dev/kmsg\fP rather than \fBsyslog\fP(2) since kernel 3.5.0.
.RS 4
カーネルメッセージを読み出すのに、\fBdmesg\fP が \fBsyslog\fP(2) のカーネルインターフェースを使うようにする。kernel 3.5.0
以来、\fBsyslog\fP(2) ではなく、\fI/dev/kmsg\fP を使用するのがデフォルトである。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-s\fP, \fB\-\-buffer\-size\fP \fIsize\fP
.RE
.sp
\fB\-s\fP, \fB\-\-buffer\-size\fP \fIsize\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Use a buffer of \fIsize\fP to query the kernel ring buffer. This is 16392 by default. (The default kernel syslog buffer size was 4096 at first, 8192 since 1.3.54, 16384 since 2.1.113.) If you have set the kernel buffer to be larger than the default, then this option can be used to view the entire buffer.
.RS 4
カーネルのリングバッファーへの問い合わせに、サイズ \fIsize\fP のバッファーを使用する。デフォルトでは 16392 である。(デフォルトのカーネル
syslog バッファーのサイズは、最初は 4096 だったが、1.3.54 以後は 8192 になり、2.1.113 以来 16384 になった。)
カーネルバッファーをデフォルトより大きく設定している場合に、バッファーを全部見るには、 このオプションを使えばよい。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-T\fP, \fB\-\-ctime\fP
.RE
.sp
\fB\-T\fP, \fB\-\-ctime\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Print human\-readable timestamps.
.\"O .sp
.\"O \fBBe aware that the timestamp could be inaccurate!\fP The \fBtime\fP source used for the logs is \fBnot updated after\fP system \fBSUSPEND\fP/\fBRESUME\fP. Timestamps are adjusted according to current delta between boottime and monotonic clocks, this works only for messages printed after last resume.
.RS 4
読みやすいタイムスタンプを表示する。
.sp
「\fBこのタイムスタンプは不正確なことがある！\fP」という点に注意すること。 ログに使用する、タイムスタンプの元になる情報 (time source)
は、システムの \fBサスペンド\fP/\fBレジューム\fP 後に、更新が行われない。 更新が行われないので、タイムスタンプは、ブートタイムと単調増加クロック
(monotonic clocks) との間の現在の増分 (delta) によって時間合わせがなされているのだが、そうした時間合わせが、
最後のレジューム以後に表示されるメッセージ同士の間でしかうまく働かないのである。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-\-since\fP \fItime\fP
.RE
.sp
\fB\-\-since\fP \fItime\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display record since the specified time. The time is possible to specify in absolute way as well as by relative notation (e.g. \(aq1 hour ago\(aq). Be aware that the timestamp could be inaccurate and see \fB\-\-ctime\fP for more details.
.RS 4
指定された時間以降のレコードを表示する。 時間の指定には、絶対的な指定と相対的な指定 (たとえば \(aq1 hour ago\(aq) が可能である。
タイムスタンプは不正確になることがある点に注意。 詳しくは \fB\-\-ctime\fP を参照のこと。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-\-until\fP \fItime\fP
.RE
.sp
\fB\-\-until\fP \fItime\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display record until the specified time. The time is possible to specify in absolute way as well as by relative notation (e.g. \(aq1 hour ago\(aq). Be aware that the timestamp could be inaccurate and see \fB\-\-ctime\fP for more details.
.RS 4
指定された時間までのレコードを表示する。 時間の指定には、絶対的な指定と相対的な指定 (たとえば \(aq1 hour ago\(aq) が可能である。
タイムスタンプは不正確になることがある点に注意。 詳しくは \fB\-\-ctime\fP を参照のこと。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-t\fP, \fB\-\-notime\fP
.RE
.sp
\fB\-t\fP, \fB\-\-notime\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Do not print kernel\(cqs timestamps.
.RS 4
カーネルが出力するタイムスタンプを表示しない。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-\-time\-format\fP \fIformat\fP
.RE
.sp
\fB\-\-time\-format\fP \fIformat\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Print timestamps using the given \fIformat\fP, which can be \fBctime\fP, \fBreltime\fP, \fBdelta\fP or \fBiso\fP. The first three formats are aliases of the time\-format\-specific options. The \fBiso\fP format is a \fBdmesg\fP implementation of the ISO\-8601 timestamp format. The purpose of this format is to make the comparing of timestamps between two systems, and any other parsing, easy. The definition of the \fBiso\fP timestamp is: YYYY\-MM\-DD<T>HH:MM:SS,<microseconds>\(<-+><timezone offset from UTC>.
.\"O .sp
.\"O The \fBiso\fP format has the same issue as \fBctime\fP: the time may be inaccurate when a system is suspended and resumed.
.RS 4
指定されたフォーマット \fIformat\fP を使って、タイムスタンプを表示する。\fIformat\fP には、\fBctime\fP, \fBreltime\fP,
\fBdelta\fP, \fBiso\fP が使える。 最初の三つは、それぞれのタイムフォーマットを指定するオプションのエイリアスであり、\fBiso\fP
フォーマットは、ISO\-8601 のタイムスタンプフォーマットの \fBdemsg\fP における実装である。 この最後のフォーマットの目的は、
二つのシステム間でのタイムスタンプの比較のような解析作業を容易にすることだ。 \fBiso\fP タイムスタンプは、
YYYY\-MM\-DD<T>HH:MM:SS,<microseconds><\-+><timezone
offset from UTC> という形式になる。
.sp
\fBiso\fP フォーマットにも \fBctime\fP と同じ問題がある。
すなわち、システムがサスペンド、レジュームした場合、日時は不正確かもしれないのである。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-u\fP, \fB\-\-userspace\fP
.RE
.sp
\fB\-u\fP, \fB\-\-userspace\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Print userspace messages.
.RS 4
ユーザー空間のメッセージを表示する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-w\fP, \fB\-\-follow\fP
.RE
.sp
\fB\-w\fP, \fB\-\-follow\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Wait for new messages. This feature is supported only on systems with a readable \fI/dev/kmsg\fP (since kernel 3.5.0).
.RS 4
新しいメッセージが出力されるのを待つ。この機能は、 \fI/dev/kmsg\fP を読むことのできるシステムでのみサポートされている (カーネル 3.5.0
以降)。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-W\fP, \fB\-\-follow\-new\fP
.RE
.sp
\fB\-W\fP, \fB\-\-follow\-new\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Wait and print only new messages.
.RS 4
待機する。そして、新しいメッセージのみを表示する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-x\fP, \fB\-\-decode\fP
.RE
.sp
\fB\-x\fP, \fB\-\-decode\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Decode facility and level (priority) numbers to human\-readable prefixes.
.RS 4
ファシリティとレベル (重大度) の番号を人間に分かりやすい接頭辞に変換する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-V\fP, \fB\-\-version\fP
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display version information and exit.
.RS 4
バージョン情報を表示して終了する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-h\fP, \fB\-\-help\fP
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display help text and exit.
.RS 4
ヘルプを表示して終了する。
.\"O ----------------------------------------
.\"O .RE
.RE
.\"O ----------------------------------------
.\"O .SH "COLORS"
.\"O .sp
.\"O Implicit coloring can be disabled by an empty file \fI/etc/terminal\-colors.d/dmesg.disable\fP. See \fBterminal\-colors.d\fP(5) for more details about colorization configuration.
.\"O .sp
.\"O The logical color names supported by \fBdmesg\fP are:
.\"O .sp
.\"O \fBsubsys\fP
.SH カラー表示
.sp
自動的なカラー表示は、 \fI/etc/terminal\-colors.d/dmesg.disable\fP という空ファイルを作ることで無効にできる。
カラー表示の設定についての詳細は、 \fBterminal\-colors.d\fP(5) を参照のこと。
.sp
\fBdmesg\fP は、以下の論理カラー名をサポートしている。
.sp
\fBsubsys\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O The message sub\-system prefix (e.g., "ACPI:").
.RS 4
メッセージのサブシステム接頭辞 (たとえば、"ACPI")。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fBtime\fP
.RE
.sp
\fBtime\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O The message timestamp.
.RS 4
メッセージのタイムスタンプ。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fBtimebreak\fP
.RE
.sp
\fBtimebreak\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O The message timestamp in short ctime format in \fB\-\-reltime\fP or \fB\-\-human\fP output.
.RS 4
\fB\-\-reltime\fP や \fB\-\-human\fP における出力メッセージの、短い ctime フォーマットで表現したタイムスタンプ。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fBalert\fP
.RE
.sp
\fBalert\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O The text of the message with the alert log priority.
.RS 4
ログの重大度が alert のメッセージのテキスト部分。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fBcrit\fP
.RE
.sp
\fBcrit\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O The text of the message with the critical log priority.
.RS 4
ログの重大度が critical のメッセージのテキスト部分。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fBerr\fP
.RE
.sp
\fBerr\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O The text of the message with the error log priority.
.RS 4
ログの重大度が error のメッセージのテキスト部分。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fBwarn\fP
.RE
.sp
\fBwarn\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O The text of the message with the warning log priority.
.RS 4
ログの重大度が warning のメッセージのテキスト部分。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fBsegfault\fP
.RE
.sp
\fBsegfault\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O The text of the message that inform about segmentation fault.
.RS 4
セグメンテーションフォールトを知らせるメッセージのテキスト部分。
.\"O ----------------------------------------
.\"O .RE
.RE
.\"O ----------------------------------------
.\"O .SH "EXIT STATUS"
.\"O .sp
.\"O \fBdmesg\fP can fail reporting permission denied error. This is usually caused by \fBdmesg_restrict\fP kernel setting, please see \fBsyslog\fP(2) for more details.
.SH 終了ステータス
.sp
\fBdmesg\fP が「操作が許可されていない」旨のエラーを出して、実行に失敗することがある。 これが起きるのは、たいてい、カーネルの設定
\fBdmesg_restrict\fP のせいである。詳しくは、\fBsyslog\fP(2) を参照のこと。
.\"O ----------------------------------------
.\"O .SH "AUTHORS"
.\"O .sp
.\"O .MTO "kzak\(atredhat.com" "Karel Zak" ""
.\"O .sp
.\"O \fBdmesg\fP was originally written by \c
.\"O .MTO "tytso\(atathena.mit.edu" "Theodore Ts\(cqo" "."
.SH 作者
.sp
.MTO kzak\(atredhat.com "Karel Zak" ""
.sp
\fBdmesg\fP を最初に書いたのは、
.MTO tytso\(atathena.mit.edu "Theodore Ts\(cqo" .
.\"O ----------------------------------------
.\"O .SH "SEE ALSO"
.\"O .sp
.\"O \fBterminal\-colors.d\fP(5),
.\"O \fBsyslogd\fP(8)
.SH 関連項目
.sp
\fBterminal\-colors.d\fP(5), \fBsyslogd\fP(8)
.\"O ----------------------------------------
.\"O .SH "REPORTING BUGS"
.\"O .sp
.\"O For bug reports, use the issue tracker at \c
.\"O .URL "https://github.com/karelzak/util\-linux/issues" "" "."
.SH バグ報告
.sp
バグ報告は、 以下にある issue トラッカーを利用すること。
.URL https://github.com/karelzak/util\-linux/issues "" .
.\"O ----------------------------------------
.\"O .SH "AVAILABILITY"
.\"O .sp
.\"O The \fBdmesg\fP command is part of the util\-linux package which can be downloaded from \c
.\"O .URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" "."
.SH 入手方法
.sp
\fBdmesg\fP コマンドは util\-linux パッケージの一部であり、 以下からダウンロードできる。
.URL https://www.kernel.org/pub/linux/utils/util\-linux/ "Linux Kernel Archive" .
.\"O ----------------------------------------
