.\"O .TH "REV" "1" "2021-06-02" "util\-linux 2.37.2" "User Commands"
.\"O .ie \n(.g .ds Aq \(aq
.\"O .el       .ds Aq '
.\"O .ss \n[.ss] 0
.\"O .nh
.\"O .ad l
.\"O .de URL
.\"O \fI\\$2\fP <\\$1>\\$3
.\"O ..
.\"O .als MTO URL
.\"O .if \n[.g] \{\
.\"O .  mso www.tmac
.\"O .  am URL
.\"O .    ad l
.\"O .  .
.\"O .  am MTO
.\"O .    ad l
.\"O .  .
.\"O .  LINKSTYLE blue R < >
.\"O .\}
.TH REV 1 2021\-06\-02 "util\-linux 2.37.2" ユーザーコマンド
.ie  \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de  URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if  \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.\"O ----------------------------------------
.\"O .SH "NAME"
.\"O rev \- reverse lines characterwise
.SH 名前
rev \- 入力された文字を逆に並べた行を出力する
.\"O ----------------------------------------
.\"O .SH "SYNOPSIS"
.\"O .sp
.\"O \fBrev\fP [option] [\fIfile\fP...]
.SH 書式
.sp
\fBrev\fP [option] [\fIfile\fP...]
.\"O ----------------------------------------
.\"O .SH "DESCRIPTION"
.\"O .sp
.\"O The \fBrev\fP utility copies the specified files to standard output, reversing the order of characters in every line. If no files are specified, standard input is read.
.\"O .sp
.\"O This utility is a line\-oriented tool and it uses in\-memory allocated buffer for a whole wide\-char line. If the input file is huge and without line breaks than allocate the memory for the file may be unsuccessful.
.SH 説明
.sp
\fBrev\fP ユーティリティーは、 指定されたファイルを読み込んで、 各行の文字を逆順に並べて、 標準出力へ書き出す。
ファイルが指定されなかった場合は、 標準入力から読み込みを行う。
.sp
このユーティリティーは行指向 (line\-oriented) なツールであり、 長い一行全体の文字に対して、 メモリ内にバッファーを割り当てて使用する。
入力ファイルがあまりに大きく、改行文字もなかった場合には、 そのファイルへのメモリ割り当てが失敗することがある。
.\"O ----------------------------------------
.\"O .SH "OPTIONS"
.\"O .sp
.\"O \fB\-V\fP, \fB\-\-version\fP
.SH オプション
.sp
\fB\-V\fP, \fB\-\-version\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display version information and exit.
.RS 4
バージョン情報を表示して終了する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-h\fP, \fB\-\-help\fP
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display help text and exit.
.RS 4
ヘルプを表示して終了する。
.\"O ----------------------------------------
.\"O .RE
.RE
.\"O ----------------------------------------
.\"O .SH "SEE ALSO"
.\"O .sp
.\"O \fBtac\fP(1)
.SH 関連項目
.sp
\fBtac\fP(1)
.\"O ----------------------------------------
.\"O .SH "REPORTING BUGS"
.\"O .sp
.\"O For bug reports, use the issue tracker at \c
.\"O .URL "https://github.com/karelzak/util\-linux/issues" "" "."
.SH バグ報告
.sp
バグ報告は、 以下にある issue トラッカーを利用すること。
.URL https://github.com/karelzak/util\-linux/issues "" .
.\"O ----------------------------------------
.\"O .SH "AVAILABILITY"
.\"O .sp
.\"O The \fBrev\fP command is part of the util\-linux package which can be downloaded from \c
.\"O .URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" "."
.SH 入手方法
.sp
\fBrev\fP コマンドは util\-linux パッケージの一部であり、 以下からダウンロードできる。
.URL https://www.kernel.org/pub/linux/utils/util\-linux/ "Linux Kernel Archive" .
.\"O ----------------------------------------
