.\"O .TH "SCRIPTREPLAY" "1" "2021-07-20" "util\-linux 2.37.2" "User Commands"
.\"O .ie \n(.g .ds Aq \(aq
.\"O .el       .ds Aq '
.\"O .ss \n[.ss] 0
.\"O .nh
.\"O .ad l
.\"O .de URL
.\"O \fI\\$2\fP <\\$1>\\$3
.\"O ..
.\"O .als MTO URL
.\"O .if \n[.g] \{\
.\"O .  mso www.tmac
.\"O .  am URL
.\"O .    ad l
.\"O .  .
.\"O .  am MTO
.\"O .    ad l
.\"O .  .
.\"O .  LINKSTYLE blue R < >
.\"O .\}
.TH SCRIPTREPLAY 1 2021\-07\-20 "util\-linux 2.37.2" ユーザーコマンド
.ie  \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de  URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if  \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.\"O ----------------------------------------
.\"O .SH "NAME"
.\"O scriptreplay \- play back typescripts, using timing information
.SH 名前
scriptreplay \- タイミング情報を使って、タイプスクリプトを再生する
.\"O ----------------------------------------
.\"O .SH "SYNOPSIS"
.\"O .sp
.\"O \fBscriptreplay\fP [options] [\fB\-t\fP] \fItimingfile\fP [\fItypescript\fP [\fIdivisor\fP]]
.SH 書式
.sp
\fBscriptreplay\fP [options] [\fB\-t\fP] \fItimingfile\fP [\fItypescript\fP [\fIdivisor\fP]]
.\"O ----------------------------------------
.\"O .SH "DESCRIPTION"
.\"O .sp
.\"O This program replays a typescript, using timing information to ensure that output happens in the same rhythm as it originally appeared when the script was recorded.
.\"O .sp
.\"O The replay simply displays the information again; the programs that were run when the typescript was being recorded are \fBnot run again\fP. Since the same information is simply being displayed, \fBscriptreplay\fP is only guaranteed to work properly if run on the same type of terminal the typescript was recorded on. Otherwise, any escape characters in the typescript may be interpreted differently by the terminal to which \fBscriptreplay\fP is sending its output.
.\"O .sp
.\"O The timing information is what \fBscript\fP(1) outputs to file specified by \fB\-\-log\-timing\fP.
.\"O .sp
.\"O By default, the typescript to display is assumed to be named \fItypescript\fP, but other filenames may be specified, as the second parameter or with option \fB\-\-log\-out\fP.
.\"O .sp
.\"O If the third parameter or \fB\-\-divisor\fP is specified, it is used as a speed\-up multiplier. For example, a speed\-up of 2 makes \fBscriptreplay\fP go twice as fast, and a speed\-up of 0.1 makes it go ten times slower than the original session.
.SH 説明
.sp
このプログラムは、タイプスクリプトを再生する。その際、タイミング情報を使って、
スクリプトが記録されたときの、元の出力表示と同じリズムで、出力が行われるようにする。
.sp
この再生は、記録された情報を再表示するだけである。 タイプスクリプトが記録されていたときに実行されていたプログラムが、再実行されるわけではない。
単に同じ情報を表示しているだけなので、 \fBscriptreplay\fP が正確に動作すると保証できるのは、
タイプスクリプトが記録されたのと同じタイプの端末で実行される場合だけである。
そうでない場合は、タイプスクリプト中のどのエスケープ文字も、\fBscriptreplay\fP
がその出力を送り出す端末によって異なった解釈をされるかもしれない。
.sp
タイミング情報とは、\fBscript\fP(1) が \fB\-\-log\-timing\fP によって指定されたファイルに出力するものである。
.sp
デフォルトでは、再生対象になるタイプスクリプトには、\fItypescript\fP という名前が付いていることになっている。しかし、他のファイル名を 2
番目のパラメーターとして、あるいは \fB\-\-log\-out\fP オプションで指定することもできる。
.sp
3 番目のパラメーターや \fB\-\-divisor\fP を指定すると、それはスピードアップ乗数として使用される。 たとえば、スピードアップ乗数に 2
を指定すると、\fBscriptreplay\fP は、オリジナルセッションの 2 倍の速度で再生を行う。 0.1
を指定すると、オリジナルセッションより動作速度が 10 倍遅くなる。
.\"O ----------------------------------------
.\"O .SH "OPTIONS"
.\"O .sp
.\"O \fB\-I\fP, \fB\-\-log\-in\fP \fIfile\fP
.SH オプション
.sp
\fB\-I\fP, \fB\-\-log\-in\fP \fIfile\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O File containing \fBscript\fP\(aqs terminal input.
.RS 4
\fBscript\fP の端末入力を記録しているファイル。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-O\fP, \fB\-\-log\-out\fP \fIfile\fP
.RE
.sp
\fB\-O\fP, \fB\-\-log\-out\fP \fIfile\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O File containing \fBscript\fP\(aqs terminal output.
.RS 4
\fBscript\fP の端末出力を記録しているファイル。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-B\fP, \fB\-\-log\-io\fP \fIfile\fP
.RE
.sp
\fB\-B\fP, \fB\-\-log\-io\fP \fIfile\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O File containing \fBscript\fP\(aqs terminal output and input.
.RS 4
\fBscript\fP の端末入力と端末出力を記録しているファイル。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-t\fP, \fB\-\-timing\fP \fIfile\fP
.RE
.sp
\fB\-t\fP, \fB\-\-timing\fP \fIfile\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O File containing \fBscript\fP\(aqs timing output. This option overrides old\-style arguments.
.RS 4
\fBscript\fP のタイミング出力を記録しているファイル。 このオプションは、旧式の引数に優先する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-T\fP, \fB\-\-log\-timing\fP \fIfile\fP
.RE
.sp
\fB\-T\fP, \fB\-\-log\-timing\fP \fIfile\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O This is an alias for \fB\-t\fP, maintained for compatibility with \fBscript\fP(1) command\-line options.
.RS 4
このオプションは、\fB\-t\fP の別名である。 \fBscript\fP(1) のコマンドラインオプションと名前を合わせるために維持されている。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-s\fP, \fB\-\-typescript\fP \fIfile\fP
.RE
.sp
\fB\-s\fP, \fB\-\-typescript\fP \fIfile\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O File containing \fBscript\fP\(aqs terminal output. Deprecated alias to \fB\-\-log\-out\fP. This option overrides old\-style arguments.
.RS 4
\fBscript\fP の端末出力を記録しているファイル。\fB\-\-log\-out\fP の別名だが、非推奨である。このオプションは、旧式の引数に優先する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-c\fP, \fB\-\-cr\-mode\fP \fImode\fP
.RE
.sp
\fB\-c\fP, \fB\-\-cr\-mode\fP \fImode\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Specifies how to use the CR (0x0D, carriage return) character from log files. The default mode is \fIauto\fP, in this case CR is replaced with line break for stdin log, because otherwise \fBscriptreplay\fP would overwrite the same line. The other modes are \fInever\fP and \fIalways\fP.
.RS 4
ログファイルにある CR 文字 (0x0D, キャリッジリターン) の使い方を指定する。 デフォルトのモードは、\fIauto\fP
であり、その場合、標準入力のログでは、CR は改行に置き換えられる。 そうしないと、\fBscriptreplay\fP
が同一行を上書きすることになるからである。 他のモードに \fInever\fP と \fIalways\fP がある。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-d\fP, \fB\-\-divisor\fP \fInumber\fP
.RE
.sp
\fB\-d\fP, \fB\-\-divisor\fP \fInumber\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Speed up the replay displaying this \fInumber\fP of times. The argument is a floating\-point number. It\(cqs called divisor because it divides the timings by this factor. This option overrides old\-style arguments.
.RS 4
再生の表示を \fInumber\fP 倍にスピードアップする。この引数 \fInumber\fP は浮動小数点数である。このオプションが divisor (除数)
と呼ばれるのは、タイミングをこの要素で割るからである。 このオプションは、旧式の引数に優先する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-m\fP, \fB\-\-maxdelay\fP \fInumber\fP
.RE
.sp
\fB\-m\fP, \fB\-\-maxdelay\fP \fInumber\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Set the maximum delay between updates to \fInumber\fP of seconds. The argument is a floating\-point number. This can be used to avoid long pauses in the typescript replay.
.RS 4
表示の更新間の待ち時間の最大を \fInumber\fP 秒にする。 この引数 \fInumber\fP は浮動小数点数である。
このオプションを使えば、タイプスクリプトの再生で長い間が明いてしまうのを避けることができる。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-\-summary\fP
.RE
.sp
\fB\-\-summary\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display details about the session recorded in the specified timing file and exit. The session has to be recorded using \fIadvanced\fP format (see \fBscript\fP(1)) option \fB\-\-logging\-format\fP for more details).
.RS 4
指定されたタイミングファイルに記録されたセッションについての詳細を表示して、終了する。 対象になるセッションは、\fIadvanced\fP
フォーマットで記録されていなければならない (詳しいことは、\fBscript\fP(1) のオプション \fB\-\-logging\-format\fP
の説明を参照のこと)。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-x\fP, \fB\-\-stream\fP \fItype\fP
.RE
.sp
\fB\-x\fP, \fB\-\-stream\fP \fItype\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Forces \fBscriptreplay\fP to print only the specified stream. The supported stream types are \fIin\fP, \fIout\fP, \fIsignal\fP, or \fIinfo\fP. This option is recommended for multi\-stream logs (e.g., \fB\-\-log\-io\fP) in order to print only specified data.
.RS 4
指定されたストリームのみを \fBscriptreplay\fP に表示させる。 指定できるストリームのタイプは、\fIin\fP, \fIout\fP,
\fIsignal\fP, \fIinfo\fP である。 このオプションは、マルチストリームのログに (たとえば、\fB\-\-log\-io\fP を使ったときに)
指定したストリームのデータだけを表示させたい場合に利用するとよい。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-V\fP, \fB\-\-version\fP
.RE
.sp
\fB\-V\fP, \fB\-\-version\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display version information and exit.
.RS 4
バージョン情報を表示して終了する。
.\"O ----------------------------------------
.\"O .RE
.\"O .sp
.\"O \fB\-h\fP, \fB\-\-help\fP
.RE
.sp
\fB\-h\fP, \fB\-\-help\fP
.\"O ----------------------------------------
.\"O .RS 4
.\"O Display help text and exit.
.RS 4
ヘルプを表示して終了する。
.\"O ----------------------------------------
.\"O .RE
.RE
.\"O ----------------------------------------
.\"O .SH "EXAMPLES"
.\"O .sp
.\"O .if n .RS 4
.\"O .nf
.\"O .fam C
.\"O % script \-\-log\-timing file.tm \-\-log\-out script.out
.\"O Script started, file is script.out
.\"O % ls
.\"O <etc, etc>
.\"O % exit
.\"O Script done, file is script.out
.\"O % scriptreplay \-\-log\-timing file.tm \-\-log\-out script.out
.\"O .fam
.\"O .fi
.\"O .if n .RE
.SH 例
.sp
.if  n .RS 4
.nf
.fam C
% script \-\-log\-timing file.tm \-\-log\-out script.out
Script started, file is script.out
% ls
<etc, etc>
% exit
Script done, file is script.out
% scriptreplay \-\-log\-timing file.tm \-\-log\-out script.out
.fam
.fi
.if  n .RE
.\"O ----------------------------------------
.\"O .SH "AUTHORS"
.\"O .sp
.\"O The original \fBscriptreplay\fP program was written by \c
.\"O .MTO "joey\(atkitenet.net" "Joey Hess" "."
.\"O The program was re\-written in C by
.\"O .MTO "jay\(atgnu.org" "James Youngman" ""
.\"O and
.\"O .MTO "kzak\(atredhat.com" "Karel Zak" ""
.SH 作者
.sp
\fBscriptreplay\fP プログラムの原型を書いたのは、
.MTO joey\(atkitenet.net "Joey Hess" .
である。 プログラムを C で書き直したのは、以下のものである。
.MTO jay\(atgnu.org "James Youngman" ""
,
.MTO kzak\(atredhat.com "Karel Zak" ""
.\"O ----------------------------------------
.\"O .SH "COPYRIGHT"
.\"O .sp
.\"O Copyright © 2008 James Youngman
.\"O .sp
.\"O Copyright © 2008\-2019 Karel Zak
.\"O .sp
.\"O This is free software; see the source for copying conditions. There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.\"O .sp
.\"O Released under the GNU General Public License version 2 or later.
.SH 著作権
.sp
Copyright © 2008 James Youngman
.sp
Copyright © 2008\-2019 Karel Zak
.sp
This is free software; see the source for copying conditions. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.sp
Released under the GNU General Public License version 2 or later.
.\"O ----------------------------------------
.\"O .SH "SEE ALSO"
.\"O .sp
.\"O \fBscript\fP(1),
.\"O \fBscriptlive\fP(1)
.SH 関連項目
.sp
\fBscript\fP(1), \fBscriptlive\fP(1)
.\"O ----------------------------------------
.\"O .SH "REPORTING BUGS"
.\"O .sp
.\"O For bug reports, use the issue tracker at \c
.\"O .URL "https://github.com/karelzak/util\-linux/issues" "" "."
.SH バグ報告
.sp
バグ報告は、 以下にある issue トラッカーを利用すること。
.URL https://github.com/karelzak/util\-linux/issues "" .
.\"O ----------------------------------------
.\"O .SH "AVAILABILITY"
.\"O .sp
.\"O The \fBscriptreplay\fP command is part of the util\-linux package which can be downloaded from \c
.\"O .URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" "."
.SH 入手方法
.sp
\fBscriptreplay\fP コマンドは util\-linux パッケージの一部であり、 以下からダウンロードできる。
.URL https://www.kernel.org/pub/linux/utils/util\-linux/ "Linux Kernel Archive" .
.\"O ----------------------------------------
