.\" Copyright (c) 1993 Michael Haardt (michael@moria.de),
.\"     Fri Apr  2 11:32:09 MET DST 1993
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" The GNU General Public License's references to "object code"
.\" and "executables" are to be interpreted as the output of any
.\" document formatting or typesetting system, including
.\" intermediate and printed output.
.\"
.\" This manual is distributed in the hope that it will be useful,
.\" but WITHOUT ANY WARRANTY; without even the implied warranty of
.\" MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\" GNU General Public License for more details.
.\"
.\" You should have received a copy of the GNU General Public
.\" License along with this manual; if not, write to the Free
.\" Software Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111,
.\" USA.
.\"
.\" Modified formatting Sat Jul 24 17:13:38 1993, Rik Faith (faith@cs.unc.edu)
.\" Modified (extensions and corrections)
.\"   Sun May  1 14:21:25 MET DST 1994 Michael Haardt
.\"   If mistakes in the capabilities are found, please send a bug report to:
.\"   michael@moria.de
.\" Modified Mon Oct 21 17:47:19 EDT 1996 by Eric S. Raymond (esr@thyrsus.com)
.\"
.\" Japanese Version Copyright (c) 1999 NOKUBI Takatsugu
.\" 	all rights reserved.
.\" Translated Fri Jan 29 13:09:56 JST 1999
.\"	by NOKUBI Takatsugu <knok@daionet.gr.jp>
.\" Proofed & Modified Thu 12 Oct 2000
.\"     by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.\"WORD capability	機能
.\"WORD formfeed	頁送り
.\"WORD	standout	強調
.\"WORD carriage return	復帰
.\"WORD new line	改行
.\"WORD block graphic character(s)	図形文字(集合)
.\"WORD alternate character set		代替文字集合
.\"
.TH TERMCAP 5 1996-10-21 "Linux" "Linux Programmer's Manual"
.\"O .SH NAME
.SH 名前
.\"O termcap \- terminal capability database
termcap \- 端末機能のデータベース
.\"O .SH DESCRIPTION
.SH 説明
.\"O The termcap database is an obsolete facility for describing the
.\"O capabilities of character-cell terminals and printers.
.\"O It is retained only for capability with old programs;
.\"O new ones should use the
.\"O .BR terminfo (5)
.\"O database and associated libraries.
termcap データベースは、
文字単位で動作する端末やプリンタの機能を記述するための旧式の機構である。
この機構は古いプログラムを動作させるためだけに保持されているので、
新しいプログラムは
.BR terminfo (5)
データベースとそれに関連したライブラリを用いるべきである。
.LP
.\"O .I /etc/termcap
.\"O is an ASCII file (the database master) that lists the capabilities of
.\"O many different types of terminals.
.\"O Programs can read termcap to find
.\"O the particular escape codes needed to control the visual attributes of
.\"O the terminal actually in use.
.\"O (Other aspects of the terminal are
.\"O handled by
.\"O stty (1).)
.\"O The termcap database is indexed on the
.\"O .B TERM
.\"O environment variable.
.I /etc/termcap
は、多くの異なる種類の端末に関する機能を列記したアスキーファイル
(データベースマスター) である。
プログラムは termcap を読み込んで、
実際に使用している端末に個別のエスケープコード群を取得する。
これを用いると、その端末の視覚的な性質を制御することができる
(端末の他の性質は
.BR stty (1)
で制御する)。
termcap データベースは、環境変数
.B TERM
の値で引かれる。
.LP
.\"O Termcap entries must be defined on a single logical line, with \(aq\\\(aq
.\"O used to suppress the newline.
.\"O Fields are separated by \(aq:\(aq.
.\"O The first field of each entry starts at the left-hand margin,
.\"O and contains a list of names for the terminal, separated by \(aq|\(aq.
termcap のエントリは、単一の論理行でなければならない。
ただし、行末に \(aq\\\(aq を用いればそこでの改行を抑制することができる。
フィールドは \(aq:\(aq で分割される。
各エントリの最初のフィールドは左側先頭から始まり、
内容はその端末の名前のリストである。名前の区切りには \(aq|\(aq が用いられる。
.LP
.\"O The first subfield may (in BSD termcap entries from versions 4.3 and
.\"O prior) contain a short name consisting of two characters.
.\"O This short name may consist of capital or small letters.
.\"O In 4.4BSD termcap entries this field is omitted.
最初のサブフィールドは
(4.3 以前のバージョンのBSD termcap エントリでは)
2 文字からなる短い名前となっている。この短い名前は
大文字もしくは小文字で構成される。4.4BSD の termcap エントリでは、
このフィールドは省略される。
.LP
.\"O The second subfield (first, in the newer 4.4BSD format) contains the
.\"O name used by the environment variable
.\"O .BR TERM .
.\"O It should be spelled in lowercase letters.
.\"O Selectable hardware capabilities should be marked
.\"O by appending a hyphen and a suffix to this name.
.\"O See below for an example.
.\"O Usual suffixes are w (more than 80 characters wide), am
.\"O (automatic margins), nam (no automatic margins), and rv (reverse video
.\"O display).
.\"O The third subfield contains a long and descriptive name for
.\"O this termcap entry.
2 番目 (最新の 4.4BSD フォーマットでは 1 番目) のサブフィールドには、
環境変数
.B TERM
で用いられる名称が入る。
このフィールドには小文字しか使えない。
選択可能なハードウェア機能は、ハイフンと接尾語 (suffix)
を名称の後に追加することによって示す必要がある。以下の例を見よ。
慣習的な接尾語には、w (80 文字以上の幅がある)、
am (automatic margins: 自動的な行の折り返し)、
nam (non automatic margins: 自動的でない行の折り返し)、
rv (reverse video display: 反転ビデオ表示)
などがある。
3番目のサブフィールドには、
このtermcapエントリーに対する長い説明的な名称が入る。
.LP
.\"O Subsequent fields contain the terminal capabilities; any continued
.\"O capability lines must be indented one tab from the left margin.
この後に続くフィールドには、端末の機能を記述する。
機能を記述する行が継続する場合は、
左端から1つのタブをおいてインデントしなければならない。
.LP
.\"O Although there is no defined order, it is suggested to write first
.\"O boolean, then numeric, and then string capabilities, each sorted
.\"O alphabetically without looking at lower or upper spelling.
.\"O Capabilities of similar functions can be written in one line.
順序については定義されていないが、
大文字小文字は区別せずにアルファベット順にならべ、
始めはブール値の、次は数値の、最後は文字列の機能を書くことが推奨されている。
同じような働きをする機能は 1 行にまとめて書くと良い。
.LP
.nf
.\"O Example for:
例:
.sp
Head line: vt|vt101|DEC VT 101 terminal in 80 character mode:\e
Head line: Vt|vt101-w|DEC VT 101 terminal in (wide) 132 character mode:\e
Boolean: :bs:\e
Numeric: :co#80:\e
String: :sr=\eE[H:\e
.fi
.\"O .SS "Boolean Capabilities"
.SS "ブール値で指定する機能"
.nf
.\"O 5i	Printer will not echo on screen
5i	プリンタはスクリーンにエコーしない
.\"O am	Automatic margins which means automatic line wrap
am	自動マージン。自動的に行を折り返す
.\"O bs	Control-H (8 dec.) performs a backspace
bs	コントロール H (キーコード 8) をバックスペースとして扱う
.\"O bw	Backspace on left margin wraps to previous line and right margin
bw	左端でのバックスペースを、上の行の右端に折り返す
.\"O da	Display retained above screen
da	画面の上端から外れていた行を表示する (通常はマルチページ端末で)
.\"O db	Display retained below screen
db	画面の下端から外れていた行を表示する (通常はマルチページ端末で)
.\"O eo	A space erases all characters at cursor position
eo	空白文字はカーソル位置の全ての文字を消す
.\"O es	Escape sequences and special characters work in status line
es	ステータス行上のエスケープシーケンスや特殊文字は有効に働く
.\"O gn	Generic device
gn	一般的なデバイスである
.\"O hc	This is a hardcopy terminal
hc	ハードコピー端末である
.\"O HC	The cursor is hard to see when not on bottom line
HC	最下行にないカーソルは見づらい
.\"O hs	Has a status line
hs	ステータス行がある
.\"O hz	Hazeltine bug, the terminal can not print tilde characters
hz	チルダ文字が表示できない端末である (Hazeltine 端末のバグ)
.\"O in	Terminal inserts null bytes, not spaces, to fill whitespace
in	ホワイトスペースを埋めるのに、スペースではなく NULL バイトを挿入する端末である
.\"O km	Terminal has a meta key
km	端末にはメタキーがある
.\"O mi	Cursor movement works in insert mode
mi	挿入モードでもカーソル移動ができる
.\"O ms	Cursor movement works in standout/underline mode
ms	強調/下線モードでもカーソル移動ができる
.\"O NP	No pad character
NP	パディング文字がない
.\"O NR	ti does not reverse te
NR	ti は te を反転しない
.\"O nx	No padding, must use XON/XOFF
nx	パディングではなく、XON/XOFF を使わなければならない
.\"O os	Terminal can overstrike
os	重ね打ちが可能な端末である
.\"O ul	Terminal underlines although it can not overstrike
ul	重ね打ちはできないが、下線表示のできる端末である
.\"O xb	Beehive glitch, f1 sends ESCAPE, f2 sends \fB^C\fP
xb	f1 はエスケープを送信し、f2 は \fB^C\fP を送信する (Beehive 端末の不具合)
.\"O xn	Newline/wraparound glitch
xn	改行/折り返しに不具合がある
.\"O xo	Terminal uses xon/xoff protocol
xo	端末は xon/xoff プロトコルを用いる
.\"O xs	Text typed over standout text will be displayed in standout
xs	強調文字の上に出力された文字は強調文字として表示される
.\"O xt	Teleray glitch, destructive tabs and odd standout mode
xt	破壊的なタブと中途半端な強調モード (Teleray 端末の不具合)
.fi
.\"O .SS "Numeric Capabilities"
.SS "数値で指定する機能"
.nf
.\"O co	Number of columns
co	端末の行数
.\"O dB	Delay in milliseconds for backspace on hardcopy terminals
dB	ハードコピー端末において、バックスペースに必要な遅延時間 (ミリ秒単位)
.\"O dC	Delay in milliseconds for carriage return on hardcopy terminals
dC	ハードコピー端末において、復帰に必要な遅延時間 (ミリ秒単位)
.\"O dF	Delay in milliseconds for form feed on hardcopy terminals
dF	ハードコピー端末において、頁送りに必要な遅延時間 (ミリ秒単位)
.\"O dN	Delay in milliseconds for new line on hardcopy terminals
dN	ハードコピー端末において、改行に必要な遅延時間 (ミリ秒単位)
.\"O dT	Delay in milliseconds for tabulator stop on hardcopy terminals
dT	ハードコピー端末において、タブストップに必要な遅延時間 (ミリ秒単位)
.\"O dV	Delay in milliseconds for vertical tabulator stop on
.\"O 	hardcopy terminals
dV	ハードコピー端末において、垂直タブに必要な遅延時間 (ミリ秒単位)
.\"O it	Difference between tab positions
it	タブ位置間の文字数
.\"O lh	Height of soft labels
lh	ソフトラベルの高さ
.\"O lm	Lines of memory
lm	画面メモリに収容できる行数
.\"O lw	Width of soft labels
lw	ソフトラベルの幅
.\"O li	Number of lines
li	行数
.\"O Nl	Number of soft labels
Nl	ソフトラベルの数
.\"O pb	Lowest baud rate which needs padding
pb	パディングが必要となる最低のボーレート
.\"O sg	Standout glitch
sg	強調表示の不具合 (強調表示に切替えたときに表示されるスペースの数)
.\"O ug	Underline glitch
ug	下線表示の不具合 (強調表示に切替えたときに表示されるスペースの数)
.\"O vt	virtual terminal number
vt	仮想端末番号
.\"O ws	Width of status line if different from screen width
ws	ステータス行の幅 (画面幅と異なる場合)
.fi
.\"O .SS "String Capabilities"
.SS	"文字列で指定する機能"
.nf
.\"O !1	shifted save key
!1	シフト状態の save キー
.\"O !2	shifted suspend key
!2	シフト状態の suspend キー
.\"O !3	shifted undo key
!3	シフト状態の undo キー
.\"O #1	shifted help key
#1	シフト状態の help キー
.\"O #2	shifted home key
#2	シフト状態の home キー
.\"O #3	shifted input key
#3	シフト状態の input キー
.\"O #4	shifted cursor left key
#4	シフト状態の左カーソルキー
.\"O %0	redo key
%0	redo キー
.\"O %1	help key
%1	help キー
.\"O %2	mark  key
%2	markキー
.\"O %3	message key
%3	message キー
.\"O %4	move key
%4	move キー
.\"O %5	next-object key
%5	next-object キー
.\"O %6	open key
%6	open キー
.\"O %7	options key
%7	options キー
.\"O %8	previous-object key
%8	previous-object キー
.\"O %9	print key
%9	print キー
.\"O %a	shifted message key
%a	シフト状態の message キー
.\"O %b	shifted move key
%b	シフト状態の move キー
.\"O %c	shifted next key
%c	シフト状態の next キー
.\"O %d	shifted options key
%d	シフト状態の options キー
.\"O %e	shifted previous key
%e	シフト状態の previous キー
.\"O %f	shifted print key
%f	シフト状態の print キー
.\"O %g	shifted redo key
%g	シフト状態の redo キー
.\"O %h	shifted replace key
%h	シフト状態の replace キー
.\"O %i	shifted cursor right key
%i	シフト状態の右カーソルキー
.\"O %j	shifted resume key
%j	シフト状態の resume キー
.\"O &0	shifted cancel key
&0	シフト状態の cancel キー
.\"O &1	reference key
&1	reference キー
.\"O &2	refresh key
&2	refresh キー
.\"O &3	replace key
&3	replace キー
.\"O &4	restart key
&4	restart キー
.\"O &5	resume key
&5	resume キー
.\"O &6	save key
&6	save キー
.\"O &7	suspend key
&7	suspend キー
.\"O &8	undo key
&8	undo キー
.\"O &9	shifted begin key
&9	シフト状態の begin キー
.\"O *0	shifted find key
*0	シフト状態の find キー
.\"O *1	shifted command key
*1	シフト状態の command キー
.\"O *2	shifted copy key
*2	シフト状態の copy キー
.\"O *3	shifted create key
*3	シフト状態の create キー
.\"O *4	shifted delete character
*4	シフト状態の delete キー
.\"O *5	shifted delete line
*5	シフト状態の delete line キー
.\"O *6	select key
*6	select キー
.\"O *7	shifted end key
*7	シフト状態の end キー
.\"O *8	shifted clear line key
*8	シフト状態の clear line キー
.\"O *9	shifted exit key
*9	シフト状態の exit キー
.\"O @0	find key
@0	find キー
.\"O @1	begin key
@1	begin キー
.\"O @2	cancel key
@2	cancel キー
.\"O @3	close key
@3	close キー
.\"O @4	command key
@4	command キー
.\"O @5	copy key
@5	copy キー
.\"O @6	create key
@6	create キー
.\"O @7	end key
@7	end キー
.\"O @8	enter/send key
@8	enter/send キー
.\"O @9	exit key
@9	exit キー
.\"O al	Insert one line
al	1 行挿入する
.\"O AL	Insert %1 lines
AL	%1 行挿入する
.\"O ac	Pairs of block graphic characters to map alternate character set
ac	図形文字のペアの集合。代替文字セットにマップするためのもの
.\"O ae	End alternative character set
ae	代替文字セットの終り
.\"O as	Start alternative character set for block graphic characters
as	図形文字集合に対する、代替文字セットの開始
.\"O bc	Backspace, if not \fB^H\fP
bc	\fB^H\fP がバックスペースでない場合のバックスペース
.\"O bl	Audio bell
bl	(音声の) ベルを鳴らす
.\"O bt	Move to previous tab stop
bt	前のタブストップへ移動
.\"O cb	Clear from beginning of line to cursor
cb	行頭からカーソル位置までのクリア
.\"O cc	Dummy command character
cc	ダミーコマンド文字
.\"O cd	Clear to end of screen
cd	画面の最後までをクリア
.\"O ce	Clear to end of line
ce	行の最後までをクリア
.\"O ch	Move cursor horizontally only to column %1
ch	カーソルを水平方向にだけ移動し、 %1 桁の位置にする
.\"O cl	Clear screen and cursor home
cl	画面を消去し、カーソルをホームポジションへ
.\"O cm	Cursor move to row %1 and column %2 (on screen)
cm	画面上の %1 行、 %2 桁へカーソルを移動
.\"O CM	Move cursor to row %1 and column %2 (in memory)
CM	メモリ上の %1 行、 %2 桁へカーソルを移動
.\"O cr	Carriage return
cr	復帰
.\"O cs	Scroll region from line %1 to %2
cs	%1 行目から %2 行目までの範囲をスクロールする
.\"O ct	Clear tabs
ct	タブの消去
.\"O cv	Move cursor vertically only to line %1
cv	カーソルを垂直方向にだけ移動し、 %1 行の位置にする
.\"O dc	Delete one character
dc	一文字削除する
.\"O DC	Delete %1 characters
DC	%1 文字削除する
.\"O dl	Delete one line
dl	一行削除する
.\"O DL	Delete %1 lines
DL	%1 行削除する
.\"O dm	Begin delete mode
dm	delete モード開始
.\"O do	Cursor down one line
do	カーソルを一行下げる
.\"O DO	Cursor down #1 lines
DO	カーソルを #1 行下げる
.\"O ds	Disable status line
ds	ステータス行を無効にする
.\"O eA	Enable alternate character set
eA	代替文字集合を有効にする
.\"O ec	Erase %1 characters starting at cursor
ec	カーソル位置から %1 文字消去する
.\"O ed	End delete mode
ed	delete モード終了
.\"O ei	End insert mode
ei	intert モード終了
.\"O ff	Formfeed character on hardcopy terminals
ff	ハードコピー端末での頁送り文字
.\"O fs	Return character to its position before going to status line
fs	ステータス行に移動する前の位置へ復帰する文字
.\"O F1	The string sent by function key f11
.\"O F2	The string sent by function key f12
.\"O F3	The string sent by function key f13
F1	ファンクションキー f11 が送出する文字列
F2	ファンクションキー f12 が送出する文字列
F3	ファンクションキー f13 が送出する文字列
\&...	\&...
.\"O F9	The string sent by function key f19
.\"O FA	The string sent by function key f20
.\"O FB	The string sent by function key f21
F9	ファンクションキー f19 が送出する文字列
FA	ファンクションキー f20 が送出する文字列
FB	ファンクションキー f21 が送出する文字列
\&...	\&...
.\"O FZ	The string sent by function key f45
.\"O Fa	The string sent by function key f46
.\"O Fb	The string sent by function key f47
FZ	ファンクションキー f45 が送出する文字列
Fa	ファンクションキー f46 が送出する文字列
Fb	ファンクションキー f47 が送出する文字列
\&...	\&...
.\"O Fr	The string sent by function key f63
Fr	ファンクションキー f63 が送出する文字列
.\"O hd	Move cursor a half line down
hd	カーソルを一行の半分だけ下に移動
.\"O ho	Cursor home
ho	カーソルをホームポジションに移動
.\"O hu	Move cursor a half line up
hu	カーソルを一行の半分だけ上に移動
.\"O i1	Initialization string 1 at login
i1	ログイン時の初期化文字列 1
.\"O i3	Initialization string 3 at login
i3	ログイン時の初期化文字列 3
.\"O is	Initialization string 2 at login
is	ログイン時の初期化文字列 2
.\"O ic	Insert one character
ic	一文字挿入
.\"O IC	Insert %1 characters
IC	%1 文字挿入
.\"O if	Initialization file
if	初期化ファイル
.\"O im	Begin insert mode
im	insert モード開始
.\"O ip	Insert pad time and needed special characters after insert
ip	挿入後のパディングに必要な時間と特殊文字
.\"O iP	Initialization program
iP	初期化プログラム
.\"O K1	upper left key on keypad
K1	キーパッドの左上キー
.\"O K2	center key on keypad
K2	キーパッドの中央キー
.\"O K3	upper right key on keypad
K3	キーパッドの右上キー
.\"O K4	bottom left key on keypad
K4	キーパッドの左下キー
.\"O K5	bottom right key on keypad
K5	キーパッドの右下キー
.\"O k0	Function key 0
k0	ファンクションキー 0
.\"O k1	Function key 1
k1	ファンクションキー 1
.\"O k2	Function key 2
k2	ファンクションキー 2
.\"O k3	Function key 3
k3	ファンクションキー 3
.\"O k4	Function key 4
k4	ファンクションキー 4
.\"O k5	Function key 5
k5	ファンクションキー 5
.\"O k6	Function key 6
k6	ファンクションキー 6
.\"O k7	Function key 7
k7	ファンクションキー 7
.\"O k8	Function key 8
k8	ファンクションキー 8
.\"O k9	Function key 9
k9	ファンクションキー 9
.\"O k;	Function key 10
k;	ファンクションキー 10
.\"O ka	Clear all tabs key
ka	clea all tabs キー
.\"O kA	Insert line key
kA	insert line キー
.\"O kb	Backspace key
kb	バックスペースキー
.\"O kB	Back tab stop
kB	back tab キー
.\"O kC	Clear screen key
kC	clear screen キー
.\"O kd	Cursor down key
kd	下カーソルキー
.\"O kD	Key for delete character under cursor
kD	カーソル位置の文字を消すキー
.\"O ke	turn keypad off
ke	キーパッドをオフにする
.\"O kE	Key for clear to end of line
kE	行末までをクリアするキー
.\"O kF	Key for scrolling forward/down
kF	前方向/下方向へスクロールするキー
.\"O kh	Cursor home key
kh	home キー
.\"O kH	Cursor hown down key
kH	cursor hown down キー
.\"O kI	Insert character/Insert mode key
kI	文字挿入キー/insert モードキー
.\"O kl	Cursor left key
kl	左カーソルキー
.\"O kL	Key for delete line
kL	行を削除するキー
.\"O kM	Key for exit insert mode
kM	insert モードを終了するキー
.\"O kN	Key for next page
kN	次のページへ移動するキー
.\"O kP	Key for previous page
kP	前のページへ移動するキー
.\"O kr	Cursor right key
kr	右カーソルキー
.\"O kR	Key for scrolling backward/up
kR	後ろ方向/上方向にスクロールするキー
.\"O ks	Turn keypad on
ke	キーパッドをオンにする
.\"O kS	Clear to end of screen key
kS	画面最後までをクリアするキー
.\"O kt	Clear this tab key
kt	タブクリアキー
.\"O kT	Set tab here key
kT	タブストップ設定キー
.\"O ku	Cursor up key
ku	上カーソルキー
.\"O l0	Label of zeroth function key, if not f0
.\"O l1	Label of first function key, if not f1
.\"O l2	Label of first function key, if not f2
l0	0 番目のファンクションキーのラベル (f0 でない場合)
l1	1 番目のファンクションキーのラベル (f1 でない場合)
l2	2 番目のファンクションキーのラベル (f2 でない場合)
\&...	\&...
.\"O la	Label of tenth function key, if not f10
la	10 番目のファンクションキーのラベル (f10 でない場合)
.\"O le	Cursor left one character
le	カーソルを左へ一文字分移動する
.\"O ll	Move cursor to lower left corner
ll	カーソルを左下隅に移動する
.\"O LE	Cursor left %1 characters
LE	カーソルを左 %1 文字分移動する
.\"O LF	Turn soft labels off
LF	ソフトラベルをオフにする
.\"O LO	Turn soft labels on
LO	ソフトラベルをオンにする
.\"O mb	Start blinking
mb	点滅開始
.\"O MC	Clear soft margins
MC	ソフトマージンをクリア
.\"O md	Start bold mode
md	bold モード開始
.\"O me	End all mode like so, us, mb, md and mr
me	so, us, mb, md, mr などのモード全てを終了する
.\"O mh	Start half bright mode
mh	半輝度モード開始
.\"O mk	Dark mode (Characters invisible)
mk	ダークモード (文字は見えなくなる)
.\"O ML	Set left soft margin
ML	左側のソフトマージンを設定
.\"O mm	Put terminal in meta mode
mm	端末をメタモードに設定する
.\"O mo	Put terminal out of meta mode
mo	端末をメタモードでなくする
.\"O mp	Turn on protected attribute
mp	属性保護モードをオンにする
.\"O mr	Start reverse mode
mr	反転モード開始
.\"O MR	Set right soft margin
MR	右端のソフトマージンを設定
.\"O nd	Cursor right one character
nd	カーソルを右に一文字分移動
.\"O nw	Carriage return command
nw	復帰コマンド
.\"O pc	Padding character
pc	パディング文字
.\"O pf	Turn printer off
pf	プリンタをオフにする
.\"O pk	Program key %1 to send string %2 as if typed by user
pk	ユーザが入力したときに文字列 %2 を送出するプログラムキー %1
.\"O pl	Program key %1 to execute string %2 in local mode
pl	ローカルモードで文字列 %2 を実行するプログラムキー %1
.\"O pn	Program soft label %1 to show string %2
pn	文字列 %2 を表示するためのプログラムソフトラベル %1
.\"O po	Turn the printer on
po	プリンタをオンにする
.\"O pO	Turn the printer on for %1 (<256) bytes
pO	%1 (<256) バイトの間プリンタをオンにする
.\"O ps	Print screen contents on printer
ps	画面上の内容をプリンタに印刷する
.\"O px	Program key %1 to send string %2 to computer
px	文字列 %2 をコンピュータに送出するプログラムキー %1
.\"O r1	Reset string 1 to set terminal to sane modes
.\"O r2	Reset string 2 to set terminal to sane modes
.\"O r3	Reset string 3 to set terminal to sane modes
r1	端末を正常なモードに設定するリセット文字列 1
r2	端末を正常なモードに設定するリセット文字列 2
r3	端末を正常なモードに設定するリセット文字列 3
.\"O RA	disable automatic margins
RA	自動折り返しを無効にする
.\"O rc	Restore saved cursor position
rc	保存しておいたカーソル位置に復帰する
.\"O rf	Reset string filename
rf	リセット文字列の入ったファイル名
.\"O RF	Request for input from terminal
RF	端末からの入力要求
.\"O RI	Cursor right %1 characters
RI	カーソルを右へ %1 文字分移動する
.\"O rp	Repeat character %1 for %2 times
rp	文字 %1 を %2 回分繰り返す
.\"O rP	Padding after character sent in replace mode
rP	置換モードにおいて、文字を送出した後に行うパディング
.\"O rs	Reset string
rs	リセット文字列
.\"O RX	Turn off XON/XOFF flow control
RX	XON/XOFF フロー制御をオフにする
.\"O sa	Set %1 %2 %3 %4 %5 %6 %7 %8 %9 attributes
sa	属性 %1 %2 %3 %4 %5 %6 %7 %8 %9 を設定
.\"O SA	enable automatic margins
SA	自動折り返しを有効にする
.\"O sc	Save cursor position
sc	カーソル位置を保存する
.\"O se	End standout mode
se	強調モード終了
.\"O sf	Normal scroll one line
sf	順方向の 1 行スクロール
.\"O SF	Normal scroll %1 lines
SF	順方向の %1 行スクロール
.\"O so	Start standout mode
so	強調モード開始
.\"O sr	Reverse scroll
sr	逆スクロール
.\"O SR	scroll back %1 lines
SR	%1 行分逆スクロールする
.\"O st	Set tabulator stop in all rows at current column
st	全ての行において、現在の桁位置をタブストップに設定する
.\"O SX	Turn on XON/XOFF flow control
SX	XON/XOFF フロー制御をオンにする
.\"O ta	move to next hardware tab
ta	次のハードウェアタブ位置へ移動
.\"O tc	Read in terminal description from another entry
tc	他のエントリから端末の説明を読む込む
.\"O te	End program that uses cursor motion
te	カーソル移動を用いるプログラムの終了
.\"O ti	Begin program that uses cursor motion
ti	カーソル移動を用いるプログラムの開始
.\"O ts	Move cursor to column %1 of status line
ts	ステータス行のカーソルを %1 桁へ移動
.\"O uc	Underline character under cursor and move cursor right
uc	カーソル位置の文字に下線をつけ、右にカーソルを移動
.\"O ue	End underlining
ue	下線モード終了
.\"O up	Cursor up one line
up	カーソルを 1 行分上に移動
.\"O UP	Cursor up %1 lines
UP	カーソルを %1 行分上に移動
.\"O us	Start underlining
us	下線モード開始
.\"O vb	Visible bell
vb	ビジュアルベル
.\"O ve	Normal cursor visible
ve	カーソルを通常の明るさにする
.\"O vi	Cursor invisible
vi	カーソルを見えなくする
.\"O vs	Standout cursor
vs	強調カーソル
.\"O wi	Set window from line %1 to %2 and column %3 to %4
wi	ウィンドウ領域を %1〜%2 行、%3〜%4 桁に設定
.\"O XF	XOFF character if not \fB^S\fP
XF	XOFF 制御文字 (\fB^S\fP でない場合)
.fi
.LP
.\"O There are several ways of defining the control codes for string capabilities:
文字列機能の制御コードを定義するには、いくつかの方法がある。
.LP
.\"O Every normal character represents itself,
.\"O except \(aq^\(aq, \(aq\e\(aq, and \(aq%\(aq.
\&\(aq^\(aq, \(aq\e\(aq, \(aq%\(aq を除く全ての通常の文字は、それ自身を表す。
.LP
.\"O A \fB^x\fP means Control-x.
.\"O Control-A equals 1 decimal.
\fB^x\fP は Control-x を意味する。 Control-A は 10 進数の 1 に等しい。
.\"NAKANO: 1 decimal?
.LP
.\"O \ex means a special code.
.\"O x can be one of the following characters:
\&\ex は特殊コードとして扱われる。x には以下の文字のどれかが入る。
.RS
.\"O E Escape (27)
E エスケープ (27)
.br
.\"O n Linefeed (10)
n ラインフィード (10)
.br
.\"O r Carriage return (13)
r 復帰 (13)
.br
.\"O t Tabulation (9)
t タブ (9)
.br
.\"O b Backspace (8)
b バックスペース (8)
.br
.\"O f Form feed (12)
f 頁送り (12)
.br
.\"O 0 Null character.
.\"O A \exxx specifies the octal character xxx.
0 ヌルキャラクタ。'\exxx' は 8 進数 xxx の文字を表す。
.RE
.IP i
.\"O Increments parameters by one.
パラメータを 1 増加させる。
.IP r
.\"O Single parameter capability
一つのパラメータをとる機能
.IP +
.\"O Add value of next character to this parameter and do binary output
次の文字の値をパラメータに追加し、バイナリで出力する
.IP 2
.\"O Do ASCII output of this parameter with a field with of 2
パラメータを 2 桁の数字として ASCII 出力する (printf の %2d と同じ意味)
.IP d
.\"O Do ASCII output of this parameter with a field with of 3
パラメータを数字として ASCII 出力する (printf の %d と同じ意味)
.IP %
.\"O Print a \(aq%\(aq
\(aq%\(aq を表示する
.LP
.\"O If you use binary output, then you should avoid the null character (\(aq\\0\(aq)
.\"O because it terminates the string.
.\"O You should reset tabulator expansion
.\"O if a tabulator can be the binary output of a parameter.
バイナリ出力を行う場合、
文字列が終端されないようにヌル文字 (\(aq\\0\(aq) を避けねばならない。
タブ文字をパラメータのバイナリ出力とする場合は、
タブ文字の展開をリセットしなければならない。
.\"O .IP Warning:
.IP 注意:
.\"O The above metacharacters for parameters may be wrong, they document Minix
.\"O termcap which may not be compatible with Linux termcap.
上記のような、パラメータとしてのメタ文字は正しくないかもしれない。
このことは、Minixの termcap と
Linux の termcap との間に互換性がないことに繋がっている。
.\"NAKANO: あやしい。
.LP
.\"O The block graphic characters can be specified by three string capabilities:
図形文字は 3 つの文字列機能で指定できる。
.IP as
.\"O start the alternative charset
代替文字セットの開始
.IP ae
.\"O end it
代替文字セットの終了
.IP ac
.\"O pairs of characters.
.\"O The first character is the name of the block graphic
.\"O symbol and the second characters is its definition.
文字列のペアの集合を指定する。
最初の文字は図形文字の名称で、
2 番目の文字はその定義である。
.LP
.\"O The following names are available:
名称には以下のものがある。
.sp
.nf
.\"O +	right arrow (>)
+	右矢印 (>)
.\"O ,	left arrow (<)
,	左矢印 (<)
.\"O \&.	down arrow (v)
\&.	下矢印 (v)
.\"O 0	full square (#)
0	なかを塗りつぶした四角 (#)
.\"O I	lantern (#)
I	ランタン記号 (#)
(訳注 原文は latern だったが、これは lantern の typo と思われる)
.\"O -	upper arrow (^)
-	上矢印 (^)
.\"O \&'	rhombus (+)
\&'	菱形 (+)
.\"O a	chess board (:)
a	チェス板 (:)
.\"O f	degree (')
f	角度 (')
.\"O g	plus-minus (#)
g	プラスマイナス (#)
.\"O h	square (#)
h	四角 (#)
.\"O j	right bottom corner (+)
j	右下隅 (+)
.\"O k	right upper corner (+)
k	右上隅 (+)
.\"O l	left upper corner (+)
l	左上隅 (+)
.\"O m	left bottom corner (+)
m	左下隅 (+)
.\"O n	cross (+)
n	十字 (+)
.\"O o	upper horizontal line (-)
o	上水平線 (-)
.\"O q	middle horizontal line (-)
q	中水平線 (-)
.\"O s	bottom horizontal line (_)
s	下水平線 (_)
.\"O t	left tee (+)
t	左 T 字 (+)
.\"O u	right tee (+)
u	右 T 字 (+)
.\"O v	bottom tee (+)
v	下 T 字 (+)
.\"O w	normal tee (+)
w	正 T 字 (+)
.\"O x	vertical line (|)
x	垂直線 (|)
.\"O ~	paragraph (???)
~	段落 (???)
.fi
.sp
.\"O The values in parentheses are suggested defaults which are used by curses,
.\"O if the capabilities are missing.
括弧内の値は、
指定した機能が存在しない場合に用いられるデフォルトの値である。
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR ncurses (3),
.BR termcap (3),
.BR terminfo (5)
.SH 校正者記
訳出にあたっては "\fBtermcap & terminfo\fP"
(Strang, Mui, O'reilly 共著, 鈴木麗 監訳, アスキー出版局 1992)
を参考にした。
ただし本日本語マニュアルにおける誤りは校正者の責任である。
