#
# Copyright (c) 2021 Linux JM project
#         all rights reserved.
#
PACKAGE_NAME    = autoconf
PACKAGE_VERSION = 2.71
PACKAGE_DATE    = 2021/01/29

AUTHOR_NAME  = "Linux JM project"
AUTHOR_EMAIL = "linuxjm-discuss@lists.osdn.me"

man_numbers = 1
man1_sources =     \
	autoconf   \
	autoheader \
	autom4te   \
	autoreconf \
	autoscan   \
	autoupdate \
	ifnames

THRESH = 100
EXTFLAGS =
PO4A_FLAGS  = -M UTF-8 -k $(THRESH)
PO4A_FLAGS += $(EXTFLAGS)
LANGS = ja

include po4a.mk
