.\"O .TH svnserve 8
.TH svnserve 8   
.\"O ----------------------------------------
.\"O .SH NAME
.\"O svnserve \- Server for the 'svn' repository access method
.SH 名前
svnserve \- 'svn' リポジトリアクセス方式に対応するサーバー
.\"O ----------------------------------------
.\"O .SH SYNOPSIS
.SH 書式
.\"O ----------------------------------------
.\"O .TP
.\"O \fBsvnserve\fP [\fIoptions\fP]
.TP 
\fBsvnserve\fP [\fIoptions\fP]
.\"O ----------------------------------------
.\"O .SH DESCRIPTION
.\"O \fBsvnserve\fP allows access to Subversion repositories using the svn
.\"O network protocol.  It can both run as a standalone server process, or
.\"O it can run out of inetd.  You must choose a mode of operation when you
.\"O start \fBsvnserve\fP.  The following options are recognized:
.SH 説明
\fBsvnserve\fP は、 ネットワークプロトコル svn を使って、 Subversion リポジトリへのアクセスを行います。
これはスタンドアロンのサーバープロセスとして実行可能であり、 また inetd を使って実行することも可能です。 \fBsvnserve\fP
を実行する際には、 操作モードを選んでおく必要があります。 以下に示すオプションが用いられます。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-d\fP, \fB\-\-daemon\fP
.\"O Causes \fBsvnserve\fP to run in daemon mode.  \fBsvnserve\fP
.\"O backgrounds itself and accepts and serves TCP/IP connections on the
.\"O svn port (3690, by default).
.TP  5
\fB\-d\fP, \fB\-\-daemon\fP
\fBsvnserve\fP をデーモンモードで起動します。 \fBsvnserve\fP がバックグラウンドで実行されて、 svn ポート (デフォルトで
3690) 上から TCP/IP 接続を受け付け、 また提供します。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-\-listen\-port\fP=\fIport\fP
.\"O Causes \fBsvnserve\fP to listen on \fIport\fP when run in daemon mode.
.TP  5
\fB\-\-listen\-port\fP=\fIport\fP
デーモンモードでの実行時に、 \fBsvnserve\fP が待ち受ける \fIport\fP を指定します。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-\-listen\-host\fP=\fIhost\fP
.\"O Causes \fBsvnserve\fP to listen on the interface specified by \fIhost\fP,
.\"O which may be either a hostname or an IP address.
.TP  5
\fB\-\-listen\-host\fP=\fIhost\fP
\fIhost\fP によって指定されるインターフェースから \fBsvnserve\fP が待ち受けるようにします。 指定にあたっては、 ホスト名または IP
アドレスを用います。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-\-foreground\fP
.\"O When used together with \fB\-d\fP, this option causes \fBsvnserve\fP
.\"O to stay in the foreground.  This option is mainly useful for
.\"O debugging.
.TP  5
\fB\-\-foreground\fP
\fB\-d\fP とともに用いることで、 \fBsvnserve\fP をフォアグラウンド実行のままとします。
このオプションは主にデバッグ目的で利用することができます。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-i\fP, \fB\-\-inetd\fP
.\"O Causes \fBsvnserve\fP to use the stdin/stdout file descriptors, as is
.\"O appropriate for a daemon running out of inetd.
.TP  5
\fB\-i\fP, \fB\-\-inetd\fP
\fBsvnserve\fP が stdin/stdout ファイルディスクリプターを用いるようにします。 inetd
からデーモン実行する場合に適しています。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-h\fP, \fB\-\-help\fP
.\"O Displays a usage summary and exits.
.TP  5
\fB\-h\fP, \fB\-\-help\fP
使用法の概要を示して終了します。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-\-version\fP
.\"O Print \fBsvnserve\fP's version and the repository filesystem
.\"O back-end(s) a particular \fBsvnserve\fP supports.
.TP  5
\fB\-\-version\fP
\fBsvnserve\fP のバージョンを表示します。 また特定の \fBsvnserve\fP
がサポートするリポジトリのファイルシステムバックエンドを表示します。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-r\fP \fIroot\fP, \fB\-\-root\fP=\fIroot\fP
.\"O Sets the virtual root for repositories served by \fBsvnserve\fP.  The
.\"O pathname in URLs provided by the client will be interpreted relative
.\"O to this root, and will not be allowed to escape this root.
.TP  5
\fB\-r\fP \fIroot\fP, \fB\-\-root\fP=\fIroot\fP
\fBsvnserve\fP が提供するリポジトリの仮想ルートを設定します。 クライアントから指定される URL 内のパス名は、
このルートからの相対パスとして解釈されます。 このルート以外をアクセスすることはできません。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-R\fP \fB\-\-read\-only\fP
.\"O Force all write operations through this \fBsvnserve\fP instance to be
.\"O forbidden, overriding all other access policy configuration.  Do not
.\"O use this option to set general repository access policy - that is what
.\"O the \fBconf/svnserve.conf\fP repository configuration file is for.
.\"O This option should be used only to restrict access via a certain
.\"O method of invoking \fBsvnserve\fP - for example, to allow write access
.\"O via SSH, but not via a \fBsvnserve\fP daemon, or to create a
.\"O restricted SSH key which is only capable of read access.
.TP  5
\fB\-R\fP \fB\-\-read\-only\fP
この \fBsvnserve\fP インスタンスを通じて行われる書き込み操作を、 強制的にすべて禁止します。 これは、
アクセスポリシーを定めた設定を上書きします。 このオプションは、 通常のリポジトリアクセスポリシーには用いないでください。 それを行うのは、
リポジトリ設定ファイル \fBconf/svnserve.conf\fP です。 このオプションは、 特定の方法によって起動した \fBsvnserve\fP
に対しての限定的なアクセス時に用いてください。 たとえば書き込みアクセスを \fBsvnserve\fP デーモン経由ではなく、 SSH
経由で行うような場合です。 あるいは、 読み込みアクセスにのみ利用する限定的な SSH 鍵を生成して利用するような場合です。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-t\fP, \fB\-\-tunnel\fP
.\"O Causes \fBsvnserve\fP to run in tunnel mode, which is just like the
.\"O inetd mode of operation (serve one connection over stdin/stdout)
.\"O except that the connection is considered to be pre-authenticated with
.\"O the username of the current uid.  This flag is selected by the client
.\"O when running over a tunnel agent.
.TP  5
\fB\-t\fP, \fB\-\-tunnel\fP
トンネルモード (tonnel mode) により \fBsvnserve\fP を実行します。 これは inetd モードによる動作に似ています
(stdin/stdout を通じて一接続を提供します)。 ただしその際の接続は、 現在の uid によるユーザー名を使い、
あらかじめ事前承認されたものとして動作する点が異なります。 トンネルエージェントを介して動作しているクライアントにより、 本フラグが選択されます。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-\-tunnel\-user\fP=\fIusername\fP
.\"O When combined with \fB\-\-tunnel\fP, overrides the pre-authenticated
.\"O username with the supplied \fIusername\fP.  This is useful in
.\"O combination with the ssh authorized_key file's "command" directive to
.\"O allow a single system account to be used by multiple committers, each
.\"O having a distinct ssh identity.
.TP  5
\fB\-\-tunnel\-user\fP=\fIusername\fP
\fB\-\-tunnel\fP とともに組み合わせて、 事前承認されたユーザー名を、 指定された \fIusername\fP によって上書きします。 これは ssh
の authorized_key ファイルにある "command" ディレクティブと合わせて用いると便利です。 複数のコミットユーザーが、
単一のシステムアカウントを利用するようなことが可能になります。 この場合、 ssh の認証は別々のものとなります。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-T\fP, \fB\-\-threads\fP
.\"O When running in daemon mode, causes \fBsvnserve\fP to spawn a thread
.\"O instead of a process for each connection.  The \fBsvnserve\fP process
.\"O still backgrounds itself at startup time.
.TP  5
\fB\-T\fP, \fB\-\-threads\fP
デーモンモードでの実行時に、 \fBsvnserve\fP が各接続に対してプロセスを実行するのではなく、 スレッドを実行するようにします。
\fBsvnserve\fP プロセスは、 起動直後にバックグラウンド実行されて起動し続けます。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-\-config\-file\fP=\fIfilename\fP
.\"O When specified, \fBsvnserve\fP reads \fIfilename\fP once at program
.\"O startup and caches the \fBsvnserve\fP configuration.  The password
.\"O and authorization configurations referenced from \fIfilename\fP will
.\"O be loaded on each connection.  \fBsvnserve\fP will not read any
.\"O per-repository \fBconf/svnserve.conf\fP files when this option is
.\"O used.  See the \fBsvnserve.conf\fP(5) man page for details of the
.\"O file format for this option.
.TP  5
\fB\-\-config\-file\fP=\fIfilename\fP
これが指定されると、 \fBsvnserve\fP は起動時に一度だけ \fIfilename\fP の内容を読み込み、 \fBsvnserve\fP
設定としてキャッシュします。 パスワード認証の設定は \fIfilename\fP から参照されますが、 各接続ごとにロードされます。
このオプションが指定された場合、 \fBsvnserve\fP はリポジトリごとの \fBconf/svnserve.conf\fP ファイルは読み込みません。
\fBsvnserve.conf\fP(5) ファイルにおける本オプションの書式については、 その man ページを参照してください。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-\-pid\-file\fP=\fIfilename\fP
.\"O When specified, \fBsvnserve\fP will write its process ID to
.\"O \fIfilename\fP.
.TP  5
\fB\-\-pid\-file\fP=\fIfilename\fP
これを指定した場合、 \fBsvnserve\fP はプロセス ID を \fIfilename\fP に書き出します。
.\"O ----------------------------------------
.\"O .PP
.PP
.\"O ----------------------------------------
.\"O .TP 5
.\"O \fB\-X\fP, \fB\-\-listen\-once\fP
.\"O Causes \fBsvnserve\fP to accept one connection on the svn port, serve
.\"O it, and exit.  This option is mainly useful for debugging.
.TP  5
\fB\-X\fP, \fB\-\-listen\-once\fP
\fBsvnserve\fP が svn ポートからのアクセスを 1 度だけ行い、 それに対する返信を行って終了します。
このオプションは主にデバッグ目的で利用することができます。
.\"O ----------------------------------------
.\"O .PP
.\"O Unless the \fB\-\-config\-file\fP option was specified on the command
.\"O line, once the client has selected a repository by transmitting its
.\"O URL, \fBsvnserve\fP reads a file named \fBconf/svnserve.conf\fP in the
.\"O repository directory to determine repository-specific settings such as
.\"O what authentication database to use and what authorization policies to
.\"O apply.  See the \fBsvnserve.conf\fP(5) man page for details of that
.\"O file format.
.PP
\fB\-\-config\-file\fP オプションがコマンドラインから指定されなかった場合には、 クライアントから URL
送信によってリポジトリが選択された際に、 \fBsvnserve\fP はリポジトリ内の \fBconf/svnserve.conf\fP
というファイルを読み込みます。 このファイルは、 利用する認証データベースや承認ポリシーなど、 リポジトリ固有の設定を定めるものです。
\fBsvnserve.conf\fP(5) のファイルフォーマットの詳細は、 その man ページを参照してください。
.\"O ----------------------------------------
.\"O .SH SEE ALSO
.\"O .BR svnserve.conf (5)
.SH 関連項目
\fBsvnserve.conf\fP(5)
.\"O ----------------------------------------
