#
# Build macro for JM project.  If something don't work well,
# please refer the description in admin/JM-CVS/JM-CVS.sgml.
#
include ./JM.rules

#
# defs
#
MKRWWW=bin/mkmanweb.perl
MKPWWW=bin/mkpodweb.perl
MKDIST=bin/mkdist.perl
CHKCVS=bin/chkcvs.sh

ROFFSRC=./manual
PODSRC=./pod
INFOSRC=./info

JMVER=0.5
JMRELEASE := $(shell env LANG=C date +"%Y%m%d")
DIST := man-pages-ja-$(JMRELEASE)


#
# global rules
#
periodic: chkcvs roff infoman html web guide web-extra

all: periodic archive-install 

#
# update check for CVS checkout
#
chkcvs:
	$(CHKCVS)

stamp/cvs-release-modified stamp/cvs-status-modified: chkcvs

#
# roff tree
#
roff: stamp/www-roff-modified

stamp/www-roff-modified: stamp/cvs-status-modified
	@mkdir -p $(WWWROFF)
	$(RSYNC) -a --delete --omit-dir-times -v $(ROFFSRC)/ $(WWWROFF)
	@mkdir -p $(WWWPOD)
	$(RSYNC) -a --delete --omit-dir-times -v $(PODSRC)/ $(WWWPOD)
	touch $@

#
# html tree
#
html: stamp/www-html-modified

stamp/www-html-modified: stamp/cvs-release-modified
#	# dirty hack (#12)
	cp $(WWWHTML)/zebedee/zebedee.pod.html .
	-$(RM) -rf $(WWWHTML)
	mkdir -p $(WWWHTML)
	$(MKRWWW) $(ROFFSRC) $(WWWHTML) $(MAN2HTML)
#	$(MKPWWW) $(PODSRC) $(WWWHTML) $(POD2HTML)
#	# Remove temporary files generated by pod2html
#	rm -f pod2htmd.tmp pod2htmi.tmp
	mkdir -p $(WWWHTML)/zebedee
	cp zebedee.pod.html $(WWWHTML)/zebedee/
	touch $@

#
# info tree
#
infoman: stamp/www-info-modified

stamp/www-info-modified: stamp/info-release-modified
#	temporary disabled (#15)
#	$(MAKE) -C $(INFOSRC) install
	touch $@

#
# web contents
#
web:
	$(MAKE) -C www/\
		WWWROOT=$(WWWROOT) WORKDIR=$(TMPDIR)\
		install

.PHONY:	guide
guide:
#	temporary disabled (#14)
#	$(MAKE) -C guide/ -f Makefile.venv-wrap install WWWROOT=$(WWWROOT) install

.PHONY:	web-extra
web-extra:
	rsync -av manual/LDP_man-pages/untrans.html $(WWWROOT)/LDP_untrans.html

#
# archive related rules
#
archive-install: stamp/latest-archive-modified
	-$(RM) www/man-pages-ja-*.tar.gz www/per-pkg/*.gz
	cp $(TMPDIR)/$(DIST).tar.gz www/
	mkdir -p www/per-pkg
	cp $(TMPDIR)/man-pages-ja-*-$(JMRELEASE).tar.gz www/per-pkg
	touch $<
	make -C www/ DATE=$(JMRELEASE)\
		WWWROOT=$(WWWROOT)\
		index.html
	make -C www/\
		WWWROOT=$(WWWROOT)\
		install

stamp/latest-archive-modified: tarball

#
# tarball
#
tarball: $(TMPDIR)/$(DIST).tar.gz

$(TMPDIR)/$(DIST).tar.gz:
	@mkdir -p $(TMPDIR)
	$(MKDIST) . $(TMPDIR)/$(DIST) $(POD2MAN)
	$(MAKE) -f Makefile.dist install
	(cd $(TMPDIR); tar czf $(DIST).tar.gz $(DIST))
	touch stamp/latest-archive-modified

#
# clean
#
clean:	tmpclean
	rm -f stamp/*-modified
	$(MAKE) -C www/ clean
	$(MAKE) -f Makefile.dist clean

tmpclean:
	rm -rf $(TMPDIR)

realclean:	clean
	$(RM) -rf $(WWWROOT)/*
