.\"O .TH "UUID_CLEAR" "3" "2021-06-02" "util\-linux 2.37.2" "Programmer\(aqs Manual"
.\"O .ie \n(.g .ds Aq \(aq
.\"O .el       .ds Aq '
.\"O .ss \n[.ss] 0
.\"O .nh
.\"O .ad l
.\"O .de URL
.\"O \fI\\$2\fP <\\$1>\\$3
.\"O ..
.\"O .als MTO URL
.\"O .if \n[.g] \{\
.\"O .  mso www.tmac
.\"O .  am URL
.\"O .    ad l
.\"O .  .
.\"O .  am MTO
.\"O .    ad l
.\"O .  .
.\"O .  LINKSTYLE blue R < >
.\"O .\}
.TH UUID_CLEAR 3 2021\-06\-02 "util\-linux 2.37.2" プログラマーマニュアル
.ie  \n(.g .ds Aq \(aq
.el       .ds Aq '
.ss \n[.ss] 0
.nh
.ad l
.de  URL
\fI\\$2\fP <\\$1>\\$3
..
.als MTO URL
.if  \n[.g] \{\
.  mso www.tmac
.  am URL
.    ad l
.  .
.  am MTO
.    ad l
.  .
.  LINKSTYLE blue R < >
.\}
.\"O ----------------------------------------
.\"O .SH "NAME"
.\"O uuid_clear \- reset value of UUID variable to the NULL value
.SH 名前
uuid_clear \- UUID 変数の値を NULL 値にリセットする
.\"O ----------------------------------------
.\"O .SH "SYNOPSIS"
.\"O .sp
.\"O \fB#include <uuid.h>\fP
.\"O .sp
.\"O \fBvoid uuid_clear(uuid_t \fIuu\fP);\fP
.SH 書式
.sp
\fB#include <uuid.h>\fP
.sp
\fBvoid uuid_clear(uuid_t \fP\fIuu\fP\fB);\fP
.\"O ----------------------------------------
.\"O .SH "DESCRIPTION"
.\"O .sp
.\"O The \fBuuid_clear\fP() function sets the value of the supplied uuid variable \fIuu\fP to the NULL value.
.SH 説明
.sp
\fBuuid_clear\fP() 関数は、 指定された uuid 変数 \fIuu\fP を、 NULL 値に設定する。
.\"O ----------------------------------------
.\"O .SH "AUTHORS"
.\"O .sp
.\"O Theodore Y. Ts\(cqo
.SH 著者
.sp
Theodore Y. Ts\(cqo
.\"O ----------------------------------------
.\"O .SH "SEE ALSO"
.\"O .sp
.\"O \fBuuid\fP(3),
.\"O \fBuuid_compare\fP(3),
.\"O \fBuuid_copy\fP(3),
.\"O \fBuuid_generate\fP(3),
.\"O \fBuuid_is_null\fP(3),
.\"O \fBuuid_parse\fP(3),
.\"O \fBuuid_unparse\fP(3)
.SH 関連項目
.sp
\fBuuid\fP(3), \fBuuid_compare\fP(3), \fBuuid_copy\fP(3), \fBuuid_generate\fP(3),
\fBuuid_is_null\fP(3), \fBuuid_parse\fP(3), \fBuuid_unparse\fP(3)
.\"O ----------------------------------------
.\"O .SH "REPORTING BUGS"
.\"O .sp
.\"O For bug reports, use the issue tracker at \c
.\"O .URL "https://github.com/karelzak/util\-linux/issues" "" "."
.SH バグ報告
.sp
バグ報告は、 以下にある issue トラッカーを利用すること。
.URL https://github.com/karelzak/util\-linux/issues "" .
.\"O ----------------------------------------
.\"O .SH "AVAILABILITY"
.\"O .sp
.\"O The \fBlibuuid\fP library is part of the util\-linux package since version 2.15.1. It can be downloaded from \c
.\"O .URL "https://www.kernel.org/pub/linux/utils/util\-linux/" "Linux Kernel Archive" "."
.SH 入手方法
.sp
\fBlibuuid\fP ライブラリは、 util\-linux 2.15.1 以降、 このパッケージの一部であり、 以下からダウンロードできる。
.URL https://www.kernel.org/pub/linux/utils/util\-linux/ "Linux Kernel Archive" .
.\"O ----------------------------------------
