.\"	$Id: lkbib.1,v 1.1.1.1 1999/07/19 01:49:12 cvs Exp $	-*- nroff -*-
.ds g \" empty
.ds G \" empty
.\" Like TP, but if specified indent is more than half
.\" the current line-length - indent, use the default indent.
.de Tp
.ie \\n(.$=0:((0\\$1)*2u>(\\n(.lu-\\n(.iu)) .TP
.el .TP "\\$1"
..
.TH LKBIB 1 "6 August 1992" "Groff Version 1.08"
.SH 名称
lkbib \- 文献目録データベースを検索する
.SH 書式
.B lkbib
[
.B \-v
]
[
.BI \-i fields
]
[
.BI \-p filename
]
[
.BI \-t n
]
.IR key \|.\|.\|.
.SH 解説
.B lkbib は、
.IR key \|.\|.\|.
で指定されたキーを用いて文献目録データベースを検索し、
参考文献の形式で標準出力に出力します。
.B lkbib
は、
.B -p
オプションで指定され
たすべてのデータベースと、デフォルトのデータベースを検索します。デフォ
ルトのデータベースは、環境変数
.SB REFER
で設定されたもの、あるいは、
.B /usr/share/dict/papers/Ind
が用いられます。指定したデータベースファイ
ル名
.I filename
に対応したインデックスファイル
.IB filename .i
(
.BR indxbib (1)
により作成する)が存在すれば、それが検索されます。インデックスは、複数のデー
タベースを網羅している可能性があります。
.SH オプション
.TP
.B \-v
バージョン番号を表示します。
.TP
.BI \-p filename
.I filename
を検索します。複数の
.B \-p
オプションの指定が可能です。
.TP
.BI \-i string
インデックスを持たないファイルを検索する場合、
.I string
に含まれる名前のフィールドの内容を無視します。
.TP
.BI \-t n
キーの先頭
.I n
文字が指定されればよいものとして扱います。
.I n
の初期値は 6 です。
.SH 環境変数
.TP \w'\fBREFER'u+2n
.SB REFER
デフォルトデータベース
.SH 関連ファイル
.Tp \w'\fB/usr/share/dict/papers/Ind'u+2n
.B /usr/share/dict/papers/Ind
環境変数
.SB REFER
が設定されていない場合のデフォルトのデータベース名。
.SH 関連項目
.BR refer (1),
.BR lookbib (1),
.BR indxbib (1)
