.\"	$Id: tbl.1,v 1.1.1.1 1999/07/19 01:49:12 cvs Exp $	-*- nroff -*-
.TH TBL 1 "1 April 1993" "Groff Version 1.08"
.SH 名称
tbl \- troff のための表フォーマッタ
.SH 書式
.B tbl
[
.B \-Cv
]
[
.IR files \|.\|.\|.
]
.SH 解説
本マニュアルでは、groff ドキュメントフォーマットシステムの一部である 
GNU バージョンの
.B tbl
について記述します。
.B tbl
は、 troff ドキュメントに埋
め込まれた表の記述を
.B troff
が解釈できるコマンドに変換します。通常、
.B tbl 
は
.B groff
に
.B \-t
オプションを指定することにより起動されます。
.B tbl
は UNIX
.B tbl
と高い互換性を持ちますが、GNU
.B tbl
の出力は UNIX
.B troff
で処理するこ
とはできません。GNU
.B troff
で処理する必要があります。コマンドラインにファ
イル名が指定されなかった場合、標準入力から読み込みます。ファイル名とし
て
.B \-
を指定した場合も標準入力から読み込みます。
.SH オプション
.TP
.B \-C
.B .TS
や
.B .TE
のあとに空白や改行以外の文字がきても、それを
.B .TS
や
.B .TE
で
あると解釈します。
.TP
.B \-v
バージョン番号を表示します。
.SH 関連項目
.BR groff (1),
.BR troff (1)
