.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 1999-2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"     GNU su man page
.\"     man pages are NOT obsolete!
.\"     <ragnar@ragnar-hojland.com>
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun 12 Mar 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\" 
.TH su 1 "18 June 2002" "GNU Shell Utilities 2.1"
.SH 名前
su \- ユーザー ID とグループ ID を変更してシェルを起動する
.SH 書式
.B su
.BI "[\-] [\-flmp] [\-c " command "] [\-s " shell "] [\-\-fast] [\-\-login]"
.B [\-\-preserve-environment]
.BI "[\-\-command=" command "] [\-\-shell=" shell "]"
.BI [ user " [" arg... ]]
.sp
.SH 説明
.B su
はあるユーザーが一時的に他のユーザになるために用いられる。
.B su
は
.I user
の実ユーザー ID、実効ユーザー ID、グループ ID、および所属グループ
の権限を与えてコマンドを実行する (対話式のシェルであることが多い)。
.PP
.I user
が与えられなかった場合、デフォルトは root すなわちスーパーユーザーである。
実行されるシェルは
.I user
のパスワードエントリから選択される。ここに何も書かれていない場合は
/bin/sh が実行される。
.I user
にパスワードがある場合には、
.B su
はパスワードを要求するプロンプトを表示する。ただし
.B su
を実行したのが実ユーザー ID 0 (スーパーユーザー) の場合には
パスワード認証は行われない。
.PP
.B su
はデフォルトではカレントディレクトリを変更しない。また
.B su
は
環境変数
.BR HOME " と " SHELL
を
.I user
のパスワードエントリの値にセットする。また
.I user
がスーパーユーザー以外の場合には、環境変数
.BR USER " と " LOGNAME
を
.I user
にセットする。デフォルトでは、
起動されるシェルはログインシェルにはならない。
.PP
その他に引き数が与えられた場合には、それらはシェルに渡され、
引き数としてシェルに付加される。
.PP
.B su
は /bin/sh あるいはそれ以外のいかなるシェルも特別には扱わない
(argv[0] に "-su" を設定したり、あるシェルにだけ -c を渡したり、
といったことはしない)。
.PP
.BR syslog (3)
に対応しているシステムでは、
.B su
が失敗したとき
syslog にレポートするようにコンパイルすることができる
(成功をレポートするようにもできる)。
.SH オプション
.TP
.BI "\-c " command ", \-\-command=" command
対話的なシェルを起動するのではなく、シェルに
.I \-c
オプションとともに
.I command
(実行されるコマンドライン一行) を渡す。
.TP
.B "\-f, \-\-fast"
シェルに
.I \-f
オプションを渡す。これはおそらく
.BR csh (1)
と
.BR tcsh (1)
でのみ意味を持つ。これらのシェルでは
.I \-f
オプションを指定すると、スタートアップファイル (.cshrc) を読み込まない。
Bourne 系のシェルでは
.I \-f
オプションはファイル名パターンの展開 (glob) を抑制する。
これは大抵の場合は望ましい動作ではないだろう。
.TP
.B "\-, \-l, \-\-login"
シェルをログインシェルにする。すなわち以下のような取り扱いをする:
すべての環境変数を解除する。その上で
.BR TERM ", " HOME ", " SHELL
を前述のように設定し、
.BR USER ", " LOGNAME
を同じく前述のように (スーパーユーザーであっても) 設定する。
続いて
.B PATH
をコンパイル時のデフォルト値に設定する。ディレクトリを
.I user
のホームディレクトリに変更する。シェル名の前に `-' を付加し、
シェルにログイン時のスタートアップファイルを読ませる。
.TP
.B "\-m, \-p, \-\-preserve\-environment"
環境変数
.BR  HOME ", " USER ", " LOGNAME ", " SHELL
を変更しない。
/etc/passwd で指定されている
.I user
のシェルではなく、現在の環境変数
.B SHELL
で指定されているシェルを実行する。ただし
.B su
を実行するユーザーがスーパーユーザではなく、
.I user
によるシェルの実行が制限されている場合はこの限りではない。
実行が制限されているシェルとは、
/etc/shells にリストされていないシェル、あるいは
/etc/shells がなければコンパイル時の指定リストに存在しないシェルのことである。
このオプションが実行する作業の一部は
.B \-\-login
または
.B \-\-shell
によって上書きされる。
.TP
.BI "\-s, \-\-shell " shell
/etc/passwd に記述された
.I user
のシェルの代わりに
.I shell
を実行する。ただし
.B su
を実行するユーザーがスーパーユーザではなく、
.I user
によるシェルの実行が制限されている場合はこの限りではない。
.TP
.B "\-\-help"
標準出力に使用方法のメッセージを出力して正常終了する。
.TP
.B "\-\-version"
標準出力にバージョン情報を出力して正常終了する。
.SH "GNU su で wheel グループをサポートしないわけ (Richard Stallman)"
ときおり、少数のユーザーによって、
他のユーザーに対する全権を掌握しようとする試みがなされることがある。
例えば 1984 年、 MIT AI ラボの少数のユーザーは
Twenex システムのオペレーターパスワードの変更権限を強奪し、
これを他のユーザーから秘匿することに決定した
(この際には私はこのクーデターの裏をかき、
カーネルにパッチを当てて権限を取り返すことに成功した。
しかしこれが Unix であったら、私にはどうすればよいかわからなかっただろう)。
.PP
しかしながら、時には専制者も秘密を漏らすものである。
通常の su のメカニズムでは、
一般ユーザーの側に立つ者が root のパスワードを知れば、
これを他のユーザーにも知らせることができる。
しかし "wheel group" 機能はこれを不可能にし、
結果として専制者達の権限を強固たるものにしてしまう。
.PP
私は大衆の側に立つものであり、専制的な立場には反対する。
あなたはボスやシステム管理者のやり口に従うことに慣れているかも知れないが、
その場合はまずそのこと自身を不思議に思うべきではないだろうか。
.SH 注意
プログラムのバグについては bug-sh-utils@gnu.org に報告してください。
ページの更新は Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com> が行っています。
