.\"O .TH M4 "1" "May 2021" "GNU M4 1.4.19" "User Commands"
.TH M4 1 2021/05 "GNU M4 1.4.19" ユーザーコマンド
.\"O ----------------------------------------
.\"O .SH NAME
.\"O m4 \- macro processor
.SH 名前
m4 \- マクロプロセッサー
.\"O ----------------------------------------
.\"O .SH SYNOPSIS
.\"O .B m4
.\"O [\fI\,OPTION\/\fR]... [\fI\,FILE\/\fR]...
.SH 書式
\fBm4\fP [\fI\,OPTION\/\fP]... [\fI\,FILE\/\fP]...
.\"O ----------------------------------------
.\"O .SH DESCRIPTION
.\"O Process macros in FILEs.  If no FILE or if FILE is `\-', standard input
.\"O is read.
.SH 説明
FILE 内のマクロを処理します。 FILE の指定がない、 あるいは `\-' が指定された場合、 標準入力から読み込みます。
.\"O ----------------------------------------
.\"O .PP
.\"O Mandatory or optional arguments to long options are mandatory or optional
.\"O for short options too.
.PP
ロングオプション形式の必須または任意引数は、 ショートオプション形式でも必須または任意引数になります。
.\"O ----------------------------------------
.\"O .SS "Operation modes:"
.SS 操作モード:
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-\-help\fR
.\"O display this help and exit
.TP 
\fB\-\-help\fP
このヘルプを表示して終了します。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-\-version\fR
.\"O output version information and exit
.TP 
\fB\-\-version\fP
バージョン情報を表示して終了します。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-E\fR, \fB\-\-fatal\-warnings\fR
.\"O once: warnings become errors, twice: stop
.\"O execution at first error
.TP 
\fB\-E\fP, \fB\-\-fatal\-warnings\fP
1 度目:  警告をエラーとします、 2 度目: 1 度目のエラー箇所で実行を停止します。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-i\fR, \fB\-\-interactive\fR
.\"O unbuffer output, ignore interrupts
.TP 
\fB\-i\fP, \fB\-\-interactive\fP
出力をバッファーに残さず、中断しません。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-P\fR, \fB\-\-prefix\-builtins\fR
.\"O force a `m4_' prefix to all builtins
.TP 
\fB\-P\fP, \fB\-\-prefix\-builtins\fP
ビルトイン名の先頭に強制的に `m4_' をつけます。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-Q\fR, \fB\-\-quiet\fR, \fB\-\-silent\fR
.\"O suppress some warnings for builtins
.TP 
\fB\-Q\fP, \fB\-\-quiet\fP, \fB\-\-silent\fP
ビルトインに対する警告メッセージをいくつか省略します。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-\-warn\-macro\-sequence\fR[=\fI\,REGEXP\/\fR]
.\"O warn if macro definition matches REGEXP,
.TP 
\fB\-\-warn\-macro\-sequence\fP[=\fI\,REGEXP\/\fP]
マクロ定義が REGEXP にタッチした場合に警告します。
.\"O ----------------------------------------
.\"O .IP
.\"O default \e$\e({[^}]*}\e|[0\-9][0\-9]+\e)
.IP
デフォルトは \e$\e({[^}]*}\e|[0\-9][0\-9]+\e) です。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-W\fR, \fB\-\-word\-regexp\fR=\fI\,REGEXP\/\fR
.\"O use REGEXP for macro name syntax
.TP 
\fB\-W\fP, \fB\-\-word\-regexp\fP=\fI\,REGEXP\/\fP
マクロ名の文法に REGEXP を用います。
.\"O ----------------------------------------
.\"O .SS "Preprocessor features:"
.SS プロセッサー機能:
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-D\fR, \fB\-\-define=NAME\fR[=\fI\,VALUE\/\fR]
.\"O define NAME as having VALUE, or empty
.TP 
\fB\-D\fP, \fB\-\-define=NAME\fP[=\fI\,VALUE\/\fP]
VALUE という値または空の値を持つ NAME を定義します。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-I\fR, \fB\-\-include\fR=\fI\,DIRECTORY\/\fR
.\"O append DIRECTORY to include path
.TP 
\fB\-I\fP, \fB\-\-include\fP=\fI\,DIRECTORY\/\fP
インクルードパスに DIRECTORY を追加します。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-s\fR, \fB\-\-synclines\fR
.\"O generate `#line NUM "FILE"' lines
.TP 
\fB\-s\fP, \fB\-\-synclines\fP
`#line NUM "FILE"' 行を生成します。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-U\fR, \fB\-\-undefine\fR=\fI\,NAME\/\fR
.\"O undefine NAME
.TP 
\fB\-U\fP, \fB\-\-undefine\fP=\fI\,NAME\/\fP
NAME を未定義にします。
.\"O ----------------------------------------
.\"O .SS "Limits control:"
.SS 制限制御:
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-g\fR, \fB\-\-gnu\fR
.\"O override \fB\-G\fR to re\-enable GNU extensions
.TP 
\fB\-g\fP, \fB\-\-gnu\fP
\fB\-G\fP を上書きして GNU 拡張を再度有効にします。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-G\fR, \fB\-\-traditional\fR
.\"O suppress all GNU extensions
.TP 
\fB\-G\fP, \fB\-\-traditional\fP
GNU 拡張をすべて無効にします。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-H\fR, \fB\-\-hashsize\fR=\fI\,PRIME\/\fR
.\"O set symbol lookup hash table size [509]
.TP 
\fB\-H\fP, \fB\-\-hashsize\fP=\fI\,PRIME\/\fP
シンボルの検索ハッシュテーブルのサイズを設定します。 [デフォルト: 509]
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-L\fR, \fB\-\-nesting\-limit\fR=\fI\,NUMBER\/\fR
.\"O change nesting limit, 0 for unlimited [0]
.TP 
\fB\-L\fP, \fB\-\-nesting\-limit\fP=\fI\,NUMBER\/\fP
ネスト階層の制限を変更します。 0 を指定すると無制限です。[デフォルト: 0]
.\"O ----------------------------------------
.\"O .SS "Frozen state files:"
.SS "凍結 (frozen) 状態のファイル:"
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-F\fR, \fB\-\-freeze\-state\fR=\fI\,FILE\/\fR
.\"O produce a frozen state on FILE at end
.TP 
\fB\-F\fP, \fB\-\-freeze\-state\fP=\fI\,FILE\/\fP
処理の最後に FILE を凍結状態にします。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-R\fR, \fB\-\-reload\-state\fR=\fI\,FILE\/\fR
.\"O reload a frozen state from FILE at start
.TP 
\fB\-R\fP, \fB\-\-reload\-state\fP=\fI\,FILE\/\fP
処理の最初に FILE の凍結状態から再ロードします。
.\"O ----------------------------------------
.\"O .SS "Debugging:"
.SS デバッグ:
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-d\fR, \fB\-\-debug\fR[=\fI\,FLAGS\/\fR]
.\"O set debug level (no FLAGS implies `aeq')
.TP 
\fB\-d\fP, \fB\-\-debug\fP[=\fI\,FLAGS\/\fP]
デバッグレベルを設定します (FLAGS には `aeq' を含みません)。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-\-debugfile\fR[=\fI\,FILE\/\fR]
.\"O redirect debug and trace output to FILE
.\"O (default stderr, discard if empty string)
.TP 
\fB\-\-debugfile\fP[=\fI\,FILE\/\fP]
デバッグおよびトレース出力を FILE にリダイレクトします (デフォルトは stderr、 空文字の場合は無視されます)。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-l\fR, \fB\-\-arglength\fR=\fI\,NUM\/\fR
.\"O restrict macro tracing size
.TP 
\fB\-l\fP, \fB\-\-arglength\fP=\fI\,NUM\/\fP
マクロのトレースサイズを制限します。
.\"O ----------------------------------------
.\"O .TP
.\"O \fB\-t\fR, \fB\-\-trace\fR=\fI\,NAME\/\fR
.\"O trace NAME when it is defined
.TP 
\fB\-t\fP, \fB\-\-trace\fP=\fI\,NAME\/\fP
NAME が定義されているものとして、 これをトレースします。
.\"O ----------------------------------------
.\"O .SS "FLAGS is any of:"
.SS "FLAGS は以下のいずれか:"
.\"O ----------------------------------------
.\"O .TP
.\"O a
.\"O show actual arguments
.TP 
a
実際の引数を表示します。
.\"O ----------------------------------------
.\"O .TP
.\"O c
.\"O show before collect, after collect and after call
.TP 
c
情報の収集前後、呼び出し後を表示します。
.\"O ----------------------------------------
.\"O .TP
.\"O e
.\"O show expansion
.TP 
e
展開結果を表示します。
.\"O ----------------------------------------
.\"O .TP
.\"O f
.\"O say current input file name
.TP 
f
現在の入力ファイル名を表示します。
.\"O ----------------------------------------
.\"O .TP
.\"O i
.\"O show changes in input files
.TP 
i
入力ファイルにおける変更を表示します。
.\"O ----------------------------------------
.\"O .TP
.\"O l
.\"O say current input line number
.TP 
l
現在の入力行番号を表示します。
.\"O ----------------------------------------
.\"O .TP
.\"O p
.\"O show results of path searches
.TP 
p
パス検索の結果を表示します。
.\"O ----------------------------------------
.\"O .TP
.\"O q
.\"O quote values as necessary, with a or e flag
.TP 
q
a または e フラグを用いる場合に、 必要に応じて値をクォートで囲みます。
.\"O ----------------------------------------
.\"O .TP
.\"O t
.\"O trace for all macro calls, not only traceon'ed
.TP 
t
トレースがオンの時だけでなく、 マクロ呼び出しをすべてトレースします。
.\"O ----------------------------------------
.\"O .TP
.\"O x
.\"O add a unique macro call id, useful with c flag
.TP 
x
マクロ呼び出しの ID を追加します。 c フラグとともに用いると便利です。
.\"O ----------------------------------------
.\"O .TP
.\"O V
.\"O shorthand for all of the above flags
.TP 
V
簡潔に上記フラグすべてを含める指定です。
.\"O ----------------------------------------
.\"O .PP
.\"O If defined, the environment variable `M4PATH' is a colon\-separated list
.\"O of directories included after any specified by `\-I'.
.PP
環境変数 `M4PATH' はディレクトリを、 コロンで区切ったリストを指定しますが、 これが定義されている場合、 `\-I'
の指定の後ろに追加されます。
.\"O ----------------------------------------
.\"O .PP
.\"O Exit status is 0 for success, 1 for failure, 63 for frozen file version
.\"O mismatch, or whatever value was passed to the m4exit macro.
.PP
終了ステータスは成功時が 0、 失敗時が 1、 凍結ファイルのバージョン不一致時が 63 です。 または m4exit マクロに値が設定されれば、
その値になります。
.\"O ----------------------------------------
.\"O .SH AUTHOR
.\"O Written by Rene' Seindal.
.SH 著者
Rene' Seindal
.\"O ----------------------------------------
.\"O .SH "REPORTING BUGS"
.\"O Report bugs to: bug\-m4@gnu.org
.\"O .br
.\"O GNU M4 home page: <https://www.gnu.org/software/m4/>
.\"O .br
.\"O General help using GNU software: <https://www.gnu.org/gethelp/>
.SH バグ報告
バグ報告は bug\-m4@gnu.org までお願いします。
.br
GNU M4 home page: <https://www.gnu.org/software/m4/>
.br
GNU ソフトウェアの全般的なヘルプ: <https://www.gnu.org/gethelp/>
.\"O ----------------------------------------
.\"O .SH COPYRIGHT
.\"O Copyright \(co 2021 Free Software Foundation, Inc.
.\"O License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
.\"O .br
.\"O This is free software: you are free to change and redistribute it.
.\"O There is NO WARRANTY, to the extent permitted by law.
.SH 著作権
Copyright \(co 2021 Free Software Foundation, Inc.  License GPLv3+: GNU GPL
version 3 or later <https://gnu.org/licenses/gpl.html>.
.br
This is free software: you are free to change and redistribute it.  There is
NO WARRANTY, to the extent permitted by law.
.\"O ----------------------------------------
.\"O .SH "SEE ALSO"
.\"O The full documentation for
.\"O .B m4
.\"O is maintained as a Texinfo manual.  If the
.\"O .B info
.\"O and
.\"O .B m4
.\"O programs are properly installed at your site, the command
.SH 関連項目
\fBm4\fP の完全なドキュメントは Texinfo マニュアルとしてメンテナンスされています。 \fBinfo\fP と \fBm4\fP
の両プログラムが適切にインストールされていれば、 以下のコマンド
.\"O ----------------------------------------
.\"O .IP
.\"O .B info m4
.IP
\fBinfo m4\fP
.\"O ----------------------------------------
.\"O .PP
.\"O should give you access to the complete manual.
.PP
を実行して完全なマニュアルを参照できます。
.\"O ----------------------------------------
