.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" %%%LICENSE_END
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\" Modified Mon Mar 29 22:31:13 1993, David Metcalfe
.\" Modified Sun Jun  6 23:27:50 1993, David Metcalfe
.\" Modified Sat Jul 24 21:45:37 1993, Rik Faith (faith@cs.unc.edu)
.\" Modified Sat Dec 16 15:02:59 2000, Joseph S. Myers
.\"
.\"*******************************************************************
.\"
.\" This file was generated with po4a. Translate the source file.
.\"
.\"*******************************************************************
.\"
.\" Japanese Version Copyright (c) 1996 Kentaro OGAWA
.\"         all rights reserved.
.\" Translated Sat, 13 Jul 1996 22:44:04 +0900
.\"         by Kentaro OGAWA <k_ogawa@oyna.cc.muroran-it.ac.jp>
.\" Updated Mon 29 Jan 2001 17:18:34 JST by Kentaro Shirakata <argrath@ub32.org>
.\"
.TH ABS 3 2013\-06\-21 GNU "Linux Programmer's Manual"
.SH 名前
abs, labs, llabs, imaxabs \- 整数の絶対値を計算する
.SH 書式
.nf
\fB#include <stdlib.h>\fP
.sp
\fBint abs(int \fP\fIj\fP\fB);\fP
.br
\fBlong int labs(long int \fP\fIj\fP\fB);\fP
.br
\fBlong long int llabs(long long int \fP\fIj\fP\fB);\fP
.sp
\fB#include <inttypes.h>\fP
.sp
\fBintmax_t imaxabs(intmax_t \fP\fIj\fP\fB);\fP
.fi
.sp
.in -4n
glibc 向けの機能検査マクロの要件 (\fBfeature_test_macros\fP(7)  参照):
.in
.sp
.ad l
\fBllabs\fP():
.RS 4
_XOPEN_SOURCE\ >=\ 600 || _ISOC99_SOURCE || _POSIX_C_SOURCE\ >=\ 200112L;
.br
or \fIcc\ \-std=c99\fP
.RE
.ad
.SH 説明
\fBabs\fP()  関数は、整数の引数 \fIj\fP の絶対値を計算する。 \fBlabs\fP(), \fBllabs\fP(), \fBimaxabs\fP()
関数は、 それぞれの関数の型に応じた引数 \fIj\fP の絶対値を計算する。
.SH 返り値
それぞれの関数の型に応じた整数の引数の絶対値を返す。
.SH 属性
.SS "マルチスレッディング (pthreads(7) 参照)"
関数 \fBabs\fP(), \fBlabs\fP(), \fBllabs\fP(), \fBimaxabs\fP() はスレッドセーフである。
.SH 準拠
.\" POSIX.1 (1996 edition) requires only the
.\" .BR abs ()
.\" function.
SVr4, POSIX.1\-2001, 4.3BSD, C99.  C89 は \fBabs\fP()  関数と \fBlabs\fP()  関数のみを含んでいる。
\fBllabs\fP()  関数と \fBimaxabs\fP()  関数は C99 で追加された。
.SH 注意
最大の負整数の絶対値は、定義されていない。
.PP
\fBllabs\fP()  関数はバージョン 2.0 から glibc に含まれるようになったが、 libc5 や libc4 にはない。
\fBimaxabs\fP()  関数は バージョン 2.1.1 から glibc に含まれるようになった。
.PP
\fBllabs\fP()  が宣言されるためには、標準ヘッダを include する前に \fB_ISOC99_SOURCE\fP か
\fB_ISOC9X_SOURCE\fP(どちらかは glibc の バージョンに依存する)を define しておく必要がある。
.PP
GCC は \fBabs\fP()  と \fBlabs\fP()  をビルドイン関数として扱う。 GCC 3.0 は \fBllabs\fP()  と
\fBimaxabs\fP()  もビルドインとして扱う。
.SH 関連項目
\fBcabs\fP(3), \fBceil\fP(3), \fBfabs\fP(3), \fBfloor\fP(3), \fBrint\fP(3)
.SH この文書について
この man ページは Linux \fIman\-pages\fP プロジェクトのリリース 3.65 の一部
である。プロジェクトの説明とバグ報告に関する情報は
http://www.kernel.org/doc/man\-pages/ に書かれている。
