#
# Copyright (c) 2021 Linux JM project
#         all rights reserved.
#
PACKAGE_NAME    = m4
PACKAGE_VERSION = 1.4.19
PACKAGE_DATE    = 2021/05/28

AUTHOR_NAME  = "Linux JM project"
AUTHOR_EMAIL = "linuxjm-discuss@lists.osdn.me"

man_numbers = 1
man1_sources = \
	m4

THRESH = 100
EXTFLAGS =
PO4A_FLAGS  = -M UTF-8 -k $(THRESH)
PO4A_FLAGS += $(EXTFLAGS)
LANGS = ja

include po4a.mk
