.\" Copyright (C) 1995, Thomas K. Dyas <tdyas@eden.rutgers.edu>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Created   Sat Aug 21 1995     Thomas K. Dyas <tdyas@eden.rutgers.edu>
.\"
.\" typo corrected, aeb, 950825
.\" added layout change from joey, 960722
.\" changed prototype, documented 0xffffffff, aeb, 030101
.\" Modified 2004-11-03 patch from Martin Schulze <joey@infodrom.org>
.\"
.\" Japanese Version Copyright (c) 1997 HANATAKA Shinya
.\"         all rights reserved.
.\" Translated 1997-02-23, HANATAKA Shinya <hanataka@abyss.rim.or.jp>
.\" Updated 2003-04-24, Kentaro Shirakata <argrath@ub32.org>
.\" Updated 2007-05-04, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.\"WORD:	process			プロセス
.\"WORD:	execution domain	実行ドメイン
.\"WORD:	personality		パーソナリティ
.\"WORD:	binary			バイナリ
.\"WORD:	operating system	オペレーティング・システム
.\"
.TH PERSONALITY 2 2003-01-01 "Linux" "Linux Programmer's Manual"
.\"O .SH NAME
.SH 名前
.\"O personality \- set the process execution domain
personality \- プロセスを実行するドメインを設定する
.\"O .SH SYNOPSIS
.SH 書式
.B #include <sys/personality.h>
.sp
.BI "int personality(unsigned long " persona );
.\"O .SH DESCRIPTION
.SH 説明
.\"O Linux supports different execution domains, or personalities, for each
.\"O process.
.\"O Among other things, execution domains tell Linux how to map
.\"O signal numbers into signal actions.
.\"O The execution domain system allows
.\"O Linux to provide limited support for binaries compiled under other
.\"O UNIX-like operating systems.
Linux は、プロセス毎の異なる実行ドメイン、すなわち
パーソナリティ (personality) をサポートしている。
実行ドメインは Linux にシグナル番号にどのシグナルを割り付けるかを
教えたりする。また、実行ドメイン・システムにより、
Linux は他の UNIX 風のオペレーティング・システムでコンパイルされた
バイナリに対する限定的なサポートを提供している。

.\"O This function will return the current
.\"O .BR personality ()
.\"O when
.\"O .I persona
.\"O equals 0xffffffff.
.\"O Otherwise, it will make the execution domain
.\"O referenced by
.\"O .I persona
.\"O the new execution domain of the calling process.
.B personality ()
関数は、
.I persona
が 0xffffffff の場合は現在の
.B パーソナリティ
を返す。
それ以外の場合、
.I persona
により参照される実行ドメインを、
呼び出し元のプロセスの新しい実行ドメインとする。
.\"O .SH "RETURN VALUE"
.SH 返り値
.\"O On success, the previous
.\"O .I persona
.\"O is returned.
.\"O On error, \-1 is returned, and
.\"O .I errno
.\"O is set appropriately.
成功した場合、以前の
.I persona
が返される。エラーの場合は、\-1 が返され、
.I errno
が適切に設定される。
.\"O .SH ERRORS
.SH エラー
.TP
.B EINVAL
.\"O The kernel was unable to change the personality.
カーネルがパーソナリティを変更できなかった。
.\"O .SH "CONFORMING TO"
.SH 準拠
.\"O .BR personality ()
.\"O is Linux-specific and should not be used in programs intended to
.\"O be portable.
.BR personality ()
は Linux 固有であり、移植を意図したプログラムで使用すべきではない。
