.\" Copyright (C) 2003 Free Software Foundation, Inc.
.\" This file is distributed according to the GNU General Public License.
.\" See the file COPYING in the top level source directory for details.
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated 2003-07-08, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" Updated 2005-02-24, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.\"O .\" Author: Kent Yoder
.\"O .\"
.TH SET_THREAD_AREA 2 2008-11-27 "Linux" "Linux Programmer's Manual"
.\"O .SH NAME
.\"O set_thread_area \- Set a Thread Local Storage (TLS) area
.SH 名前
set_thread_area \- スレッド局所記憶 (TLS) 領域を設定する
.\"O .SH "SYNOPSIS"
.SH 書式
.B #include <linux/unistd.h>
.br
.B #include <asm/ldt.h>
.sp
.BI "int set_thread_area(struct user_desc *" u_info );
.\"O .SH "DESCRIPTION"
.SH 説明
.PP
.\"O .BR set_thread_area ()
.\"O sets an entry in the current thread's Thread Local Storage (TLS) array.
.\"O The TLS array entry set by
.\"O .BR set_thread_area ()
.\"O corresponds to the value of
.\"O .I u_info\->entry_number
.\"O passed in by the user.
.\"O If this value is in bounds,
.\"O .BR set_thread_area ()
.\"O copies the TLS descriptor pointed to by
.\"O .I u_info
.\"O into the thread's TLS array.
.BR set_thread_area ()
は、カレント・スレッドのスレッド局所記憶 (Thread Local Storage; TLS)
配列の中のエントリを設定する。
.BR set_thread_area ()
により設定される TLS 配列のエントリは、ユーザから引き数として渡される
.I u_info\->entry_number
の値に対応している。値が範囲内にある場合、
.BR set_thread_area ()
は
.I u_info
で指された TLS ディスクリプタをスレッドの TLS 配列にコピーする。
.PP
.\"O When
.\"O .BR set_thread_area ()
.\"O is passed an
.\"O entry_number
.\"O \-1, it uses a free TLS entry.
.\"O If
.\"O .BR set_thread_area ()
.\"O finds a free TLS entry, the value of
.\"O .I u_info\->entry_number
.\"O is set upon return to show which entry was changed.
.I entry_number
として \-1 が渡された場合、
.BR set_thread_area ()
は未使用 (free) の TLS エントリを使用する。
未使用の TLS エントリがあった場合、どのエントリが変更されたかが分かる
ように終了時に
.I u_info\->entry_number
の値が変更される。
.\"O .SH "RETURN VALUE"
.SH 返り値
.\"O .BR set_thread_area ()
.\"O returns 0 on success, and \-1 on failure, with
.\"O .I errno
.\"O set appropriately.
.BR set_thread_area ()
は成功した場合 0 を返す。失敗した場合は \-1 を返し、
.I errno
を適切に設定する。
.\"O .SH "ERRORS"
.SH エラー
.TP
.B EINVAL
.\"O \fIu_info\->entry_number\fP is out of bounds.
.I u_info\->entry_number
が範囲外である。
.TP
.B EFAULT
.\"O \fIu_info\fP is an invalid pointer.
.I u_info
が不正なポインタである。
.TP
.B ESRCH
.\"O A free TLS entry could not be located.
未使用の TLS エントリが見つからなかった。
.\"O .SH "VERSIONS"
.SH バージョン
.\"O A version of
.\"O .BR set_thread_area ()
.\"O first appeared in Linux 2.5.29.
.BR set_thread_area ()
は Linux 2.5.29 で初めて登場した。
.\"O .SH "CONFORMING TO"
.SH 準拠
.\"O .BR set_thread_area ()
.\"O is Linux-specific and should not be used in programs that are intended
.\"O to be portable.
.BR set_thread_area ()
は Linux 独自であり、移植を意図したプログラムでは使用すべきではない。
.\"O .SH NOTES
.SH 注意
.\"O Glibc does not provide a wrapper for this system call;
.\"O call it using
.\"O .BR syscall (2).
glibc はこのシステムコールに対するラッパー関数を提供していない。
この関数を使用するには
.BR syscall (2)
を使用すること。
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR get_thread_area (2)
