.\" Copyright (C), 1994, Graeme W. Wilford (Wilf).
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Fri Jul 29th 12:56:44 BST 1994  Wilf. <G.Wilford@ee.surrey.ac.uk>
.\" Changes inspired by patch from Richard Kettlewell
.\"   <richard@greenend.org.uk>, aeb 970616.
.\" Modified, 27 May 2004, Michael Kerrisk <mtk.manpages@gmail.com>
.\"     Added notes on capability requirements
.\"
.\" Japanese Version Copyright (c) 1997 HANATAKA Shinya
.\"         all rights reserved.
.\" Translated Sat Mar  1 16:32:11 JST 1997
.\"         by HANATAKA Shinya <hanataka@abyss.rim.or.jp>
.\" Modified Sun Sep 28 20:26:49 JST 1997
.\"         by HANATAKA Shinya <hanataka@abyss.rim.or.jp>
.\" Updated & Modified Sat May 22 18:21:45 JST 2004
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\" Updated & Modified Wed Jan  5 00:51:28 JST 2005 by Yuichi SATO
.\" Updated 2010-04-10, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>, LDP v3.24
.\"
.\"WORD:	identity		識別
.\"WORD:	effective user ID	実効ユーザーID
.\"WORD:	real user ID		実ユーザーID
.\"WORD:	saved user ID		保存ユーザーID
.\"WORD:	implement		実装
.\"WORD:	root			ルート
.\"WORD:	super-user		スーパー・ユーザー
.\"
.TH SETUID 2 2010-02-21 "Linux" "Linux Programmer's Manual"
.\"O .SH NAME
.SH 名前
.\"O setuid \- set user identity
setuid \- ユーザー識別 (identity) を設定する
.\"O .SH SYNOPSIS
.SH 書式
.B #include <sys/types.h>
.br
.B #include <unistd.h>
.sp
.BI "int setuid(uid_t " uid );
.\"O .SH DESCRIPTION
.SH 説明
.\"O .BR setuid ()
.\"O sets the effective user ID of the calling process.
.\"O If the effective UID of the caller is root,
.\"O the real UID and saved set-user-ID are also set.
.BR setuid ()
は呼び出し元のプロセスの実効 (effective) ユーザー ID を設定する。
もし呼び出し元プロセスの実効 UID が root ならば、
実 (real) UID と保存 (saved) set-user-ID も設定される。
.PP
.\"O Under Linux,
.\"O .BR setuid ()
.\"O is implemented like the POSIX version with the
.\"O .B _POSIX_SAVED_IDS
.\"O feature.
.\"O This allows a set-user-ID (other than root) program to drop all of its user
.\"O privileges, do some un-privileged work, and then reengage the original
.\"O effective user ID in a secure manner.
Linux では、
.BR setuid ()
は
.B _POSIX_SAVED_IDS
をもった POSIX 版のように実装されている。
これは (ルート以外の) set-user-ID プログラムにそのユーザーの特権を
全て与え、特権の必要ない仕事をし、本来の実効ユーザー ID に
安全な方法で再び戻すことを許す。
.PP
.\"O If the user is root or the program is set-user-ID root, special care must be
.\"O taken.
.\"O The
.\"O .BR setuid ()
.\"O function checks the effective user ID of the caller and if it is
.\"O the superuser, all process-related user ID's are set to
.\"O .IR uid .
.\"O After this has occurred, it is impossible for the program to regain root
.\"O privileges.
ユーザーが root またはプログラムが root に set-user-ID されているならば、
特別の注意が払われる。
.BR setuid ()
関数は呼び出し者の実効ユーザー ID をチェックし、
それがスーパー・ユーザーならば、
プロセスに関連する全てのユーザー ID に
.I uid
を設定する。
これが行なわれた後にはプログラムが再びルートの特権を得ることはできない。
.PP
.\"O Thus, a set-user-ID-root program wishing to temporarily drop root
.\"O privileges, assume the identity of an unprivileged user, and then regain
.\"O root privileges afterward cannot use
.\"O .BR setuid ().
.\"O You can accomplish this with
.\"O .BR seteuid (2).
したがって、set-user-ID-root プログラムで、一時的にルート特権を解除し、
非特権ユーザであるかのように振舞い、後でルート権限をもう一度得ようと
する場合には、
.BR setuid ()
を使うことができない。その場合には、
.BR seteuid (2)
を使う必要がある。
.\"O .SH "RETURN VALUE"
.SH 返り値
.\"O On success, zero is returned.
.\"O On error, \-1 is returned, and
.\"O .I errno
.\"O is set appropriately.
成功した場合は 0 が返される。エラーの場合は \-1 が返され、
.I errno
が適切に設定される。
.\"O .SH ERRORS
.SH エラー
.TP
.B EAGAIN
.\"O The
.\"O .I uid
.\"O does not match the current uid and
.\"O .I uid
.\"O brings process over its
.\"O .B RLIMIT_NPROC
.\"O resource limit.
.I uid
が現在のユーザー ID とマッチせず、この
.I uid
によってプロセスがリソース上限
.B RLIMIT_NPROC
を超えた。
.TP
.B EPERM
.\"O The user is not privileged (Linux: does not have the
.\"O .B CAP_SETUID
.\"O capability) and
.\"O .I uid
.\"O does not match the real UID or saved set-user-ID of the calling process.
ユーザーが特権を持たず
(Linux では
.B CAP_SETUID
ケーパビリティ (capability) を持たず)、
.I uid
が呼び出し元プロセスの実 UID または保存 set-user-ID と一致しない。
.\"O .SH "CONFORMING TO"
.SH 準拠
.\"O SVr4, POSIX.1-2001.
.\"O Not quite compatible with the 4.4BSD call, which
.\"O sets all of the real, saved, and effective user IDs.
.\"O .\" SVr4 documents an additional EINVAL error condition.
SVr4, POSIX.1-2001.
4.4BSD のコールとは完全な互換性はない、
BSD のコールは実 (real)、保存 (saved)、実効 (effective) ID の全てを設定する。
.\" SVr4 には他に EINVAL エラーについての記述がある。
.\"O .SH NOTES
.\"O .SS Linux Notes
.SH 注意
.SS Linux での注意
.\"O Linux has the concept of file system user ID, normally equal to the
.\"O effective user ID.
.\"O The
.\"O .BR setuid ()
.\"O call also sets the file system user ID of the calling process.
.\"O See
.\"O .BR setfsuid (2).
Linux はファイル・システム・ユーザー ID の概念を持つ。
通常、これは実効ユーザー ID に等しい。
.BR setuid ()
コールは呼び出し元のプロセスのファイル・システム・ユーザー ID も設定する。
.BR setfsuid (2)
も参照すること。
.PP
.\"O If
.\"O .I uid
.\"O is different from the old effective uid, the process will
.\"O be forbidden from leaving core dumps.
.I uid
が昔の実効 uid と異っていた場合、プロセスはコア・ダンプすることを
禁止される。
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR getuid (2),
.BR seteuid (2),
.BR setfsuid (2),
.BR setreuid (2),
.BR capabilities (7),
.BR credentials (7)
