.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" This manpage is Copyright (C) 1992 Drew Eckhardt;
.\"                               1993 Ian Jackson.
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified 1993-07-24 by Rik Faith <faith@cs.unc.edu>
.\" Modified 1996-09-08 by Arnt Gulbrandsen <agulbra@troll.no>
.\" Modified 1997-01-31 by Eric S. Raymond <esr@thyrsus.com>
.\" Modified 2001-05-17 by aeb
.\" Modified 2004-06-23 by Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" Japanese Version Copyright (c) 1997 HANATAKA Shinya
.\"         all rights reserved.
.\" Translated Fri Dec 12 00:42:31 JST 1997
.\"         by HANATAKA Shinya <hanataka@abyss.rim.or.jp>
.\" Modified Tue Sep  5 02:03:33 JST 2000
.\"         by Yuichi SATO <ysato@h4.dion.ne.jp>
.\" Modified Sat Jun  2 08:48:36 JST 2001 by Yuichi SATO
.\" Modified Sun Jul  7 02:58:51 JST 2002 by Yuichi SATO
.\" Updated & Modified Sun Jan  9 23:28:11 JST 2005
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\"
.\"WORD:	file system		ファイルシステム
.\"WORD:	link			リンク
.\"WORD:	open			オープン
.\"WORD:	close			クローズ
.\"WORD:	symbolic link		シンボリック・リンク
.\"WORD:	descriptor		ディスクリプター
.\"WORD:	socket			ソケット
.\"WORD:	device			デバイス
.\"WORD:	effective UID		実効ユーザーID
.\"WORD:	sticky-bit		スティッキー・ビット
.\"WORD:	dangling symbolic link	壊れたシンボリック・リンク
.\"WORD:	memory			メモリ
.\"WORD:	protocol		プロトコル
.\"
.TH UNLINK 2 2004-06-23 "Linux" "Linux Programmer's Manual"
.\"O .SH NAME
.SH 名前
.\"O unlink \- delete a name and possibly the file it refers to
unlink \- 名前を削除し、場合によってはそれが参照しているファイルも削除する
.\"O .SH SYNOPSIS
.SH 書式
.B #include <unistd.h>
.sp
.BI "int unlink(const char *" pathname );
.\"O .SH DESCRIPTION
.SH 説明
.\"O .BR unlink ()
.\"O deletes a name from the file system.
.\"O If that name was the
.\"O last link to a file and no processes have the file open the file is
.\"O deleted and the space it was using is made available for reuse.
.BR unlink ()
はファイルシステム上の名前を削除する。
もしその名前がファイルへの最後のリンク (link) であり、
どのプロセスもそのファイルをオープン (open) していなければ、
ファイルは削除される。
ファイルが使用していたディスク上の領域は再利用が可能になる。

.\"O If the name was the last link to a file but any processes still have
.\"O the file open the file will remain in existence until the last file
.\"O descriptor referring to it is closed.
もし削除する名前がファイルへの最後のリンクだが、どれかのプロセスが
そのファイルをまだオープンしている場合は、
そのファイルを参照している最後のファイルディスクリプター (file descriptor)
がクローズ (close) されるまでファイルは存在し続ける。

.\"O If the name referred to a symbolic link the link is removed.
もしその名前がシンボリック・リンク (symbolic link) を参照していれば、
リンクは削除される。

.\"O If the name referred to a socket, fifo or device the name for it is
.\"O removed but processes which have the object open may continue to use
.\"O it.
もし名前がソケット (socket) や fifo やデバイス (device) を参照していれば
名前は削除されるがそのオブジェクトをオープンしていたプロセスは
それを使い続けることができる。
.\"O .SH "RETURN VALUE"
.SH 返り値
.\"O On success, zero is returned.
.\"O On error, \-1 is returned, and
.\"O .I errno
.\"O is set appropriately.
成功した場合は 0 を返す。エラーならば \-1 を返し、
.I errno
が適切に設定される。
.\"O .SH ERRORS
.SH エラー
.TP
.B EACCES
.\"O Write access to the directory containing
.\"O .I pathname
.\"O is not allowed for the process's effective UID, or one of the
.\"O directories in
.\"O .I pathname
.\"O did not allow search permission.
.\"O (See also
.\"O .BR path_resolution (7).)
.I pathname
を含んでいるディレクトリの書き込み許可がプロセスの実効 (effective)
ユーザー ID に与えられていないか、
.I pathname
の中のディレクトリのどれかに検索許可が与えられていない
.RB ( path_resolution (7)
も参照すること)。
.TP
.\"O .BR EBUSY " (not on Linux)"
.BR EBUSY " (Linux 以外)"
.\"O The file
.\"O .I pathname
.\"O cannot be unlinked because it is being used by the system
.\"O or another process and the implementation considers this an error.
ファイル
.I pathname
がシステムまたは他のプロセスによって使用されていて
リンクが削除できなかったので、この実装ではエラーとした。
.TP
.B EFAULT
.\"O .I pathname
.\"O points outside your accessible address space.
.I pathname
がアクセス可能なアドレス空間の外を指している。
.TP
.B EIO
.\"O An I/O error occurred.
I/O エラーが発生した。
.TP
.B EISDIR
.\"O .I pathname
.\"O refers to a directory.
.\"O (This is the non-POSIX value returned by Linux since 2.1.132.)
.I pathname
がディレクトリを参照している。
(これは POSIX で規定されていない値で、Linux 2.1.132 以降で返される。)
.TP
.B ELOOP
.\"O Too many symbolic links were encountered in translating
.\"O .IR pathname .
.I pathname
を解決する際に遭遇したシンボリック・リンクが多過ぎる。
.TP
.B ENAMETOOLONG
.\"O .IR pathname " was too long."
.IR pathname " が長過ぎる。"
.TP
.B ENOENT
.\"O A component in
.\"O .I pathname
.\"O does not exist or is a dangling symbolic link, or
.\"O .I pathname
.\"O is empty.
.I pathname
に対応するものが存在しないか、壊れたシンボリック・リンクであるか、
.I pathname
が空である。
.TP
.B ENOMEM
.\"O Insufficient kernel memory was available.
十分なカーネル (kernel) のメモリーが使用できない。
.TP
.B ENOTDIR
.\"O A component used as a directory in
.\"O .I pathname
.\"O is not, in fact, a directory.
.I pathname
のディレクトリ部分が、実際には、ディレクトリでない。
.TP
.B EPERM
.\"O The system does not allow unlinking of directories,
.\"O or unlinking of directories requires privileges that the
.\"O calling process doesn't have.
.\"O (This is the POSIX prescribed error return;
.\"O as noted above, Linux returns
.\"O .B EISDIR
.\"O for this case.)
システムがディレクトリに対する unlink 操作を許可していない。
またはディレクトリに対する unlink 操作のために必要な特権を
呼び出し元のプロセスが持っていない。
(これは POSIX で規定されているエラーの返し方である。
上述の通り、この場合には Linux は
.B EISDIR
を返す。)
.TP
.\"O .BR EPERM " (Linux only)"
.BR EPERM " (Linux のみ)"
.\"O The file system does not allow unlinking of files.
ファイルシステムがファイルに対する unlink 操作を許していない。
.TP
.\"O .BR EPERM " or " EACCES
.BR EPERM " または " EACCES
.\"O The directory containing
.\"O .I pathname
.\"O has the sticky-bit
.\"O .RB ( S_ISVTX )
.\"O set and the process's effective UID is neither the UID of the file to
.\"O be deleted nor that of the directory containing it, and
.\"O the process is not privileged (Linux: does not have the
.\"O .B CAP_FOWNER
.\"O capability).
.I pathname
を含んでいるディレクトリにスティッキー・ビット (sticky-bit)
.RB ( S_ISVTX )
が設定されていて、プロセスの実効ユーザー ID が削除しようとするファイルの
UID でもそれを含んでいるディレクトリのものでもなく、
かつプロセスに特権がない (Linux では
.B CAP_FOWNER
ケーパビリティ (capability) がない)。
.TP
.B EROFS
.\"O .I pathname
.\"O refers to a file on a read-only file system.
.I pathname
が読み込み専用のファイルシステムのファイルを参照している。
.\"O .SH "CONFORMING TO"
.SH 準拠
SVr4, 4.3BSD, POSIX.1-2001.
.\"O .\" SVr4 documents additional error
.\"O .\" conditions EINTR, EMULTIHOP, ETXTBSY, ENOLINK.
.\" SVr4 には他に EINTR, EMULTIHOP, ETXTBSY, ENOLINK エラーについての
.\" 記述がある。
.\"O .SH BUGS
.SH バグ
.\"O Infelicities in the protocol underlying NFS can cause the unexpected
.\"O disappearance of files which are still being used.
NFS プロトコル (protocol) の潜在的な不良により、
まだ使用中のファイルの突然の消滅を引き起こすことがある。
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR rm (1),
.BR chmod (2),
.BR link (2),
.BR mknod (2),
.BR open (2),
.BR rename (2),
.BR rmdir (2),
.BR unlinkat (2),
.BR mkfifo (3),
.BR remove (3),
.BR path_resolution (7),
.BR symlink (7)
