.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright (c) 1992 Drew Eckhardt (drew@cs.colorado.edu), March 28, 1992
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified by Michael Haardt <michael@moria.de>
.\" Modified 1993-07-24 by Rik Faith <faith@cs.unc.edu>
.\" Modified 1995-06-10 by Andries Brouwer <aeb@cwi.nl>
.\" Modified 2004-06-23 by Michael Kerrisk <mtk.manpages@gmail.com>
.\" Modified 2004-10-10 by Andries Brouwer <aeb@cwi.nl>
.\"
.\" Japanese Version Copyright (c) 1997 SUTO, Mitsuaki
.\"         all rights reserved.
.\" Translated Thu Jun 26 21:28:00 JST 1997
.\"         by SUTO, Mitsuaki <suto@av.crl.sony.co.jp>
.\" Updated & Modified Tue Feb 15 03:21:17 JST 2005
.\"         by Yuichi SATO <ysato444@yahoo.co.jp>
.\" Updated 2006-07-21, Akihiro MOTOKI, LDP v2.36
.\" Updated 2007-10-13, Akihiro MOTOKI, LDP v2.65
.\" Updated 2008-08-08, Akihiro MOTOKI, LDP v3.05
.\"
.TH UTIME 2 2008-08-06 "Linux" "Linux Programmer's Manual"
.\"O .SH NAME
.SH 名前
.\"O utime, utimes \- change file last access and modification times
utime, utimes \- ファイルの最終アクセス時刻と修正時刻を変更する
.\"O .SH SYNOPSIS
.SH 書式
.nf
.B #include <sys/types.h>
.br
.B #include <utime.h>
.sp
.BI "int utime(const char *" filename ", const struct utimbuf *" times );
.sp
.B #include <sys/time.h>
.sp
.BI "int utimes(const char *" filename ", const struct timeval " times [2]);
.fi
.\"O .SH DESCRIPTION
.SH 説明
.\"O The
.\"O .BR utime ()
.\"O system call
.\"O changes the access and modification times of the inode specified by
.\"O .I filename
.\"O to the
.\"O .IR actime " and " modtime
.\"O fields of
.\"O .I times
.\"O respectively.
.BR utime ()
システムコールは
.I filename
で示される inode のアクセス時刻と修正時刻を
.I times
中の
.IR actime " と " modtime
にそれぞれ変更する。

.\"O If
.\"O .I times
.\"O is NULL, then the access and modification times of the file are set
.\"O to the current time.
.I times
が
.B NULL
の場合、ファイルのアクセス時刻と修正時刻は現在の時刻に設定される。

.\"O Changing timestamps is permitted when: either
.\"O the process has appropriate privileges,
.\"O or the effective user ID equals the user ID
.\"O of the file, or
.\"O .I times
.\"O is NULL and the process has write permission for the file.
タイムスタンプの変更は以下のいずれかの場合に許可される。
プロセスに適切な特権がある場合、
実効 (effective) ユーザ ID がファイルのユーザ ID と等しい場合、
.I times
が NULL かつ、プロセスがファイルへの書き込み許可を持っている場合。

.\"O The
.\"O .I utimbuf
.\"O structure is:
構造体
.I utimbuf
は以下に示すようになっている。

.in +4n
.nf
struct utimbuf {
.\"O     time_t actime;       /* access time */
.\"O     time_t modtime;      /* modification time */
    time_t actime;       /* アクセス時刻 */
    time_t modtime;      /* 修正時刻 */
};
.fi
.in

.\"O The
.\"O .BR utime ()
.\"O system call
.\"O allows specification of timestamps with a resolution of 1 second.
.BR utime ()
システムコールは 1 秒の分解能でタイムスタンプを指定することができる。

.\"O The
.\"O .BR utimes ()
.\"O system call
.\"O is similar, but the
.\"O .I times
.\"O argument refers to an array rather than a structure.
.\"O The elements of this array are
.\"O .I timeval
.\"O structures, which allow a precision of 1 microsecond for specifying timestamps.
.BR utimes ()
は
.BR utime ()
と同様であるが、
.I times
引き数が構造体ではなく配列を参照する。
この配列の要素は
.I timeval
構造体で、タイムスタンプの指定を 1 マイクロ秒の分解能で行うことができる。
.\"O The
.\"O .I timeval
.\"O structure is:
構造体
.I timeval
は以下に示す通りである。

.in +4n
.nf
struct timeval {
.\"O     long tv_sec;        /* seconds */
    long tv_sec;        /* 秒 */
.\"O     long tv_usec;       /* microseconds */
    long tv_usec;       /* マイクロ秒 */
};
.fi
.in
.PP
.\"O .IR times [0]
.\"O specifies the new access time, and
.\"O .IR times [1]
.\"O specifies the new modification time.
.IR times [0]
は新しいアクセス時刻を、
.IR times [1]
は新しい修正時刻を規定する。
.\"O If
.\"O .I times
.\"O is NULL, then analogously to
.\"O .BR utime (),
.\"O the access and modification times of the file are
.\"O set to the current time.
.I times
が NULL の場合、
.BR utime ()
同様、ファイルのアクセス時刻と修正時刻は現在の時刻に設定される。
.\"O .SH "RETURN VALUE"
.SH 返り値
.\"O On success, zero is returned.
.\"O On error, \-1 is returned, and
.\"O .I errno
.\"O is set appropriately.
成功した場合 0 が返る。失敗した場合 \-1 が返り、
.I errno
がエラーの内容に従って設定される。
.\"O .SH ERRORS
.SH エラー
.TP
.B EACCES
.\"O Search permission is denied for one of the directories in
.\"O the path prefix of
.\"O .I path
.\"O (see also
.\"O .BR path_resolution (7)).
.I path
を構成する何れかのディレクトリに検索許可がない
.RB ( path_resolution (7)
も参照すること)。
.TP
.B EACCES
.\"O .I times
.\"O is NULL,
.\"O the caller's effective user ID does not match the owner of the file,
.\"O the caller does not have write access to the file,
.\"O and the caller is not privileged
.\"O (Linux: does not have either the
.\"O .B CAP_DAC_OVERRIDE
.\"O or the
.\"O .B CAP_FOWNER
.\"O capability).
.I times
が NULL である。
または、呼び出し元の実効ユーザ ID がファイルの所有者と一致しない。
または、呼び出し元がそのファイルへの書き込み許可を持たず、
特権も持っていない (Linux の場合、ケーパビリティ
.B CAP_DAC_OVERRIDE
も
.B CAP_FOWNER
も持っていない)。または、
.TP
.B ENOENT
.\"O .I filename
.\"O does not exist.
.I filename
が存在しない。
.TP
.B EPERM
.\"O .I times
.\"O is not NULL,
.\"O the caller's effective UID does not match the owner of the file,
.\"O and the caller is not privileged
.\"O (Linux: does not have the
.\"O .B CAP_FOWNER
.\"O capability).
.I times
が NULL でなく、かつ呼び出し元の実効 UID がファイルの所有者と一致せず、
かつ呼び出し元が特権を持っていない
(Linux の場合、ケーパビリティ
.B CAP_FOWNER
を持っていない)。
.TP
.B EROFS
.\"O .I path
.\"O resides on a read-only file system.
.I path
が読み込み専用のファイルシステム上にある。
.\"O .SH "CONFORMING TO"
.SH 準拠
.BR utime ():
SVr4, POSIX.1-2001.
.\"O POSIX.1-2008 marks
.\"O .BR utime ()
.\"O as obsolete.
POSIX.1-2008 は
.BR utime ()
を廃止予定としている。
.br
.BR utimes ():
4.3BSD, POSIX.1-2001.
.\"O .SH NOTES
.SH 注意
.\"O Linux does not allow changing the timestamps on an immutable file,
.\"O or setting the timestamps to something other than the current time
.\"O on an append-only file.
Linux では、不変 (immutable) ファイルのタイムスタンプを変更したり、
追加専用 (append-only) のファイルに現在時刻以外のタイムスタンプを
設定したりすることは、許可されていない。

.\"O In libc4 and libc5,
.\"O .BR utimes ()
.\"O is just a wrapper for
.\"O .BR utime ()
.\"O and hence does not allow a subsecond resolution.
libc4 と libc5 では、
.BR utimes ()
は単に
.BR utime ()
のラッパー (wrapper) である。
そのため秒以下を指定することはできない。
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR chattr (1),
.BR futimesat (2),
.BR stat (2),
.BR utimensat (2),
.BR futimes (3),
.BR futimens (3)
