.\" Hey Emacs! This file is -*- nroff -*- source.
.\"
.\" Copyright 1993 Rickard E. Faith (faith@cs.unc.edu)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\" 
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\" 
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" Modified Tue Oct 22 22:09:26 1996 by Eric S. Raymond <esr@thyrsus.com>
.\" FIXME -- Error conditions need to be documented
.\"
.\" Japanese Version Copyright (c) 1997 HANATAKA Shinya
.\"         all rights reserved.
.\" Translated Mon Mar  3 23:37:35 JST 1997
.\"         by HANATAKA Shinya <hanataka@abyss.rim.or.jp>
.\"
.\"WORD:	signal			シグナル
.\"WORD:	obsolete		廃止
.\"
.TH SIGVEC 2 1995-08-31 "Linux 1.3" "Linux Programmer's Manual"
.\"O .SH NAME
.SH 名前
.\"O sigvec \- BSD software signal facilities
sigvec \- BSD ソフトウェア・シグナル環境
.\"O .SH SYNOPSIS
.SH 書式
.B #include <bsd/signal.h>
.sp
.BI "int sigvec(int " sig ", struct sigvec *" vec ", struct sigvec *" ovec );
.\"O .SH DESCRIPTION
.SH 説明
.\"O This interface is made obsolete by
.\"O .BR sigaction (2).
このインタフェースは
.BR sigaction (2)
によって廃止(obsolete)された。
.PP
.\"O Under Linux
.\"O .BR sigvec ()
.\"O is #define'd to
.\"O .BR sigaction (),
.\"O and provides at best a rough approximation of the BSD 
.\"O .BR sigvec ()
.\"O interface.
Linux では
.BR sigvec ()
は 
.BR sigaction ()
に #define されており、
提供されるものは BSD 
.BR sigvec ()
インタフェースとは良くても
おおざっぱな近似にすぎない。
.\"O .SH "CONFORMING TO"
.SH 準拠
BSD, SVr4
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR sigaction (2),
.BR signal (2)
