.\" Copyright 2002 Walter Harms (walter.harms@informatik.uni-oldenburg.de)
.\" Distributed under GPL
.\"
.\" Japanese Version Copyright (c) 2003  Akihiro MOTOKI
.\"         all rights reserved.
.\" Translated 2003-07-24, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" Updated 2005-02-24, Akihiro MOTOKI
.\"
.\"WORD:	exponent	累乗
.\"
.TH CEXP2 3 2008-08-11 "" "Linux Programmer's Manual"
.\"O .SH NAME
.SH 名前
.\"O cexp2, cexp2f, cexp2l \- base-2 exponent of a complex number
cexp2, cexp2f, cexp2l \- 複素数の 2 の累乗
.\"O .SH SYNOPSIS
.SH 書式
.B #include <complex.h>
.sp
.BI "double complex cexp2(double complex " z ");"
.br
.BI "float complex cexp2f(float complex " z ");"
.br
.BI "long double complex cexp2l(long double complex " z ");"
.sp
.\"O Link with \fI\-lm\fP.
\fI\-lm\fP でリンクする。
.\"O .SH DESCRIPTION
.SH 説明
.\"O The function returns 2 raised to the power of
.\"O .IR z .
この関数は 2 の \fIz\fR 乗を返す。
.\"O .SH "CONFORMING TO"
.SH 準拠
.\"O These function names are reserved for future use in C99.
関数名は C99 で今後使用するために予約されている。
.\"O .SH AVAILABILITY
.SH 可用性
.\"O Not yet in glibc, as at version 2.8.
.\"O .\" But reserved in NAMESPACE.
バージョン 2.8 時点では、glibc にはまだ実装されていない。
.\" しかし、名前空間は予約済である。
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR cabs (3),
.BR cexp (3),
.BR clog10 (3),
.BR complex (7)
