.\" Copyright (c) 1991 The Regents of the University of California.
.\" All rights reserved.
.\"
.\" %%%LICENSE_START(BSD_4_CLAUSE_UCB)
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions
.\" are met:
.\" 1. Redistributions of source code must retain the above copyright
.\"    notice, this list of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce the above copyright
.\"    notice, this list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the distribution.
.\" 3. All advertising materials mentioning features or use of this software
.\"    must display the following acknowledgement:
.\"	This product includes software developed by the University of
.\"	California, Berkeley and its contributors.
.\" 4. Neither the name of the University nor the names of its contributors
.\"    may be used to endorse or promote products derived from this software
.\"    without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE REGENTS AND CONTRIBUTORS ``AS IS'' AND
.\" ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
.\" IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
.\" ARE DISCLAIMED.  IN NO EVENT SHALL THE REGENTS OR CONTRIBUTORS BE LIABLE
.\" FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
.\" DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
.\" OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
.\" HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
.\" LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
.\" OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
.\" SUCH DAMAGE.
.\" %%%LICENSE_END
.\"
.\"     @(#)exec.3	6.4 (Berkeley) 4/19/91
.\"
.\" Converted for Linux, Mon Nov 29 11:12:48 1993, faith@cs.unc.edu
.\" Updated more for Linux, Tue Jul 15 11:54:18 1997, pacman@cqc.com
.\" Modified, 24 Jun 2004, Michael Kerrisk <mtk.manpages@gmail.com>
.\"     Added note on casting NULL
.\"
.\"*******************************************************************
.\"
.\" This file was generated with po4a. Translate the source file.
.\"
.\"*******************************************************************
.\"
.\" Japanese Version Copyright (c) 1998 Masato Taruishi
.\"         all rights reserved.
.\" Translated 1998-05-27, Masato Taruishi
.\" Modified 1998-08-08, Fujiwara Teruyoshi <fujiwara@linux.or.jp>
.\" Modified 2000-10-06, Kentaro Shirakata <argrath@ub32.org>
.\" Modified 2005-02-26, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\" Updated 2010-10-27, Akihiro Motoki <amotoki@dd.iij4u.or.jp>, LDP v3.29
.\"
.TH EXEC 3 2010\-09\-25 GNU "Linux Programmer's Manual"
.SH 名前
execl, execlp, execle, execv, execvp, execvpe \- ファイルを実行する
.SH 書式
\fB#include <unistd.h>\fP
.sp
\fBextern char **environ;\fP
.sp
\fBint execl(const char *\fP\fIpath\fP\fB, const char *\fP\fIarg\fP\fB, ...);\fP
.br
\fBint execlp(const char *\fP\fIfile\fP\fB, const char *\fP\fIarg\fP\fB, ...);\fP
.br
\fBint execle(const char *\fP\fIpath\fP\fB, const char *\fP\fIarg\fP\fB,\fP
.br
\fB ..., char * const \fP\fIenvp\fP\fB[]);\fP
.br
\fBint execv(const char *\fP\fIpath\fP\fB, char *const \fP\fIargv\fP\fB[]);\fP
.br
\fBint execvp(const char *\fP\fIfile\fP\fB, char *const \fP\fIargv\fP\fB[]);\fP
.br
\fBint execvpe(const char *\fP\fIfile\fP\fB, char *const \fP\fIargv\fP\fB[],\fP
.br
\fB char *const \fP\fIenvp\fP\fB[]);\fP
.sp
.in -4n
glibc 向けの機能検査マクロの要件 (\fBfeature_test_macros\fP(7)  参照):
.in
.sp
\fBexecvpe\fP(): _GNU_SOURCE
.SH 説明
\fBexec\fP()  ファミリーの関数は現在のプロセスイメージを新しいプロセスイメージで置き 換える。このマニュアルで説明されている関数は
\fBexecve\fP(2)  のフロントエンドである。 (現在のプロセスイメージの置き換えについての詳細は \fBexecve\fP(2)
のマニュアルを参照)
.PP
これらの関数の最初の引き数は、実行されるファイルの名前である。
.PP
関数 \fBexecl\fP(), \fBexeclp\fP(), \fBexecle\fP()  の \fIconst char\ *arg\fP とそれに続く省略部分は
\fIarg0\fP, \fIarg1\fP, \&..., \fIargn\fP とみなされる。 これらには、実行されるプログラムで利用可能な引き数のリストを指定する
(引き数のリストは NULL で終端された文字列へのポインタから構成される)。 慣習として、最初の引き数は、実行されるファイル名
へのポインタにする。引き数のリストは必ず NULL で終わらなければならず、これらの関数は可変長引き数関数なので、 このポインタは \fI(char\ *) NULL\fP とキャストしなければならない。
.PP
関数 \fBexecv\fP(), \fBexecvp\fP(), \fBexecvpe\fP()  は、利用可能な引き数リスト (NULL で終端された文字列への
ポインタの配列) を新しいプログラムに渡す。 慣習として、最初の引き数は実行されるファイル名へ のポインタにする。ポインタの配列は必ず NULL
で終わらなければならない。
.PP
関数 \fBexecle\fP(), \fBexecvpe\fP()  では、呼び出し元が引き数 \fIenvp\fP
経由実行されるプログラムの環境を指定することができる。 \fIenvp\fP 引き数は、NULL で終端された文字列へのポインタの配列であり、 NULL
ポインタで終わらなければならない。 他の関数では、呼び出し元のプロセスの外部変数 \fBenviron\fP から新しいプロセス用の環境を与える。
.SS "execlp() と execvp() の特別な動作"
.PP
関数 \fBexeclp\fP(), \fBexecvp\fP(), \fBexecvpe\fP()  は、指定されたファイル名がスラッシュ (/) を含んでいない場合、
シェルと同じ動作で実行可能なファイルを探索する。 ファイルの検索は、環境変数 \fBPATH\fP
で指定されたコロン区切りのディレクトリのパス名のリストを対象に行われる。 この変数が定義されていない場合、パス名のリストのデフォルト値として、
カレントディレクトリの後ろに、 \fIconfstr(_CS_PATH)\fP が返すディレクトリのリストをつなげた値が使用される (この
\fBconfstr\fP(3)  の呼び出しでは通常 "/bin:/usr/bin" が返される)。

指定されたファイル名がスラッシュを含む場合、 \fBPATH\fP は無視され、指定されたパス名のファイルが実行される。

さらに、いくつかのエラーは特別に処理される。

ファイルが実行ファイルでない場合 (このとき呼び出そうとした \fBexecve\fP(2)  はエラー \fBEACCES\fP
で失敗する)、これらの関数は残りの検索パスの検索を続ける。 他にファイルが見つからなくなった場合 \fIerrno\fP に \fBEACCES\fP
を設定し復帰する。

ファイルのヘッダが実行形式として認識できない場合 (このとき呼び出そうとした \fBexecve\fP(2)  はエラー \fBENOEXEC\fP
で失敗する)、これらの関数はそのファイルを最初の引き数としたシェル (\fI/bin/sh\fP)  を実行する
(これにも失敗した場合、これ以上の検索は行われない)。
.SH 返り値
\fBexec\fP()  群の関数が復帰するのは、エラーが発生した場合のみである。 返り値は \-1 で、 \fIerrno\fP にエラーの内容がセットされる。
.SH エラー
これら全ての関数は失敗する場合がある。その場合、 \fBexecve\fP(2)  に対して規定されたエラーが \fIerrno\fP に設定される。
.SH バージョン
\fBexecvpe\fP()  関数は glibc 2.11 で初めて登場した。
.SH 準拠
POSIX.1\-2001, POSIX.1\-2008.

\fBexecvpe\fP()  関数は GNU による拡張である。
.SH 注意
Linux 以外のシステムには、 (環境変数 \fBPATH\fP が定義されていないときの)  デフォルトのパスにおいて、カレント・ディレクトリが
\fI/bin\fP と \fI/usr/bin\fP の後ろに配置されるものもある。 これはトロイの木馬対策のためである。 Linux
では、デフォルトのパスに、昔ながらの「現在のディレクトリを 先に探索」というルールを使っている。
.PP
ファイルを実行しようとしている間にエラーが発生した時の \fBexeclp\fP()  と \fBexecvp\fP()
のふるまいについて歴史的な慣習はあるが、伝統的に文書として記載されておらず、 POSIX 標準でも規定されていない。BSD (またおそらく他のシステム)
では、 \fBETXTBSY\fP が発生した場合、自動的に中断 (sleep) し再試行を行う。 Linux
はそれをハードエラーとして取り扱い即座に復帰する。
.PP
伝統的に、関数 \fBexeclp\fP()  と \fBexecvp\fP()  は、上で説明したエラーと、これら 2 つの関数自身が返す \fBENOMEM\fP と
\fBE2BIG\fP 以外の全てのエラーを無視していたが、 今では、上で説明した以外のエラーが発生した場合でも、 返ってくるよう変更された。
.SH 関連項目
\fBsh\fP(1), \fBexecve\fP(2), \fBfork\fP(2), \fBptrace\fP(2), \fBfexecve\fP(3),
\fBenviron\fP(7)
.SH この文書について
この man ページは Linux \fIman\-pages\fP プロジェクトのリリース 3.53 の一部
である。プロジェクトの説明とバグ報告に関する情報は
http://www.kernel.org/doc/man\-pages/ に書かれている。
