.\" Copyright (c) Bruno Haible <haible@clisp.cons.org>
.\"
.\" This is free documentation; you can redistribute it and/or
.\" modify it under the terms of the GNU General Public License as
.\" published by the Free Software Foundation; either version 2 of
.\" the License, or (at your option) any later version.
.\"
.\" References consulted:
.\"   GNU glibc-2 source code and manual
.\"   Dinkumware C library reference http://www.dinkumware.com/
.\"   OpenGroup's Single UNIX specification http://www.UNIX-systems.org/online.html
.\"   ISO/IEC 9899:1999
.\"
.\" About this Japanese page, please contact to JM Project <JM@linux.or.jp>
.\" Translated Wed Sep  1 22:40:19 JST 1999
.\"           by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\" Updated Sun Dec 26 19:31:26 JST 1999
.\"           by Kentaro Shirakata <argrath@yo.rim.or.jp>
.\"
.TH ISWBLANK 3  2010-09-20 "GNU" "Linux Programmer's Manual"
.\"O .SH NAME
.SH 名前
.\"O iswblank \- test for whitespace wide character
iswblank \- 空白ワイド文字かどうかを調べる
.\"O .SH SYNOPSIS
.SH 書式
.nf
.B #include <wctype.h>
.sp
.BI "int iswblank(wint_t " wc );
.fi
.sp
.in -4n
.\"O Feature Test Macro Requirements for glibc (see
.\"O .BR feature_test_macros (7)):
glibc 向けの機能検査マクロの要件
.RB ( feature_test_macros (7)
参照):
.in
.sp
.ad l
.BR iswblank ():
.RS
_XOPEN_SOURCE\ >=\ 600 || _ISOC99_SOURCE ||
_POSIX_C_SOURCE\ >=\ 200112L;
.br
or
.I cc\ -std=c99
.RE
.ad
.\"O .SH DESCRIPTION
.SH 説明
.\"O The
.\"O .BR iswblank ()
.\"O function is the wide-character equivalent of the
.\"O .BR isblank (3)
.\"O function.
.\"O It tests whether \fIwc\fP is a wide character
.\"O belonging to the wide-character class "blank".
.BR iswblank ()
関数は、
.BR isblank (3)
に対応するワイド文字関数である。
この関数は、\fIwc\fP がワイド文字クラス "blank" に属するワイド文字かど
うかを調べる。
.PP
.\"O The wide-character class "blank" is a subclass of the wide-character class
.\"O "space".
ワイド文字クラス "blank" はワイド文字クラス "space" のサブクラスである。
.PP
.\"O Being a subclass of the wide-character class "space",
.\"O the wide-character class "blank" is disjoint from the
.\"O wide-character class "graph" and therefore also disjoint
.\"O from its subclasses "alnum", "alpha", "upper", "lower", "digit",
.\"O "xdigit", "punct".
ワイド文字クラス "space" のサブクラスなので、ワイド文字クラス "blank"
はワイド文字クラス "graph" とは共通部分を持たず、したがってそのサブクラス
である "alnum", "alpha", "upper", "lower", "digit", "xdigit", "punct"
とも共通部分を持たない。
.PP
.\"O The wide-character class "blank" always contains
.\"O at least the space character
.\"O and the control character \(aq\\t\(aq.
ワイド文字クラス "blank" は、少なくとも空白文字と制御文字 \(aq\\t\(aq を常に
含む。
.\"O .SH "RETURN VALUE"
.SH 返り値
.\"O The
.\"O .BR iswblank ()
.\"O function returns nonzero
.\"O if \fIwc\fP is a wide character
.\"O belonging to the wide-character class "blank".
.\"O Otherwise it returns zero.
.BR iswblank ()
関数は、\fIwc\fP がワイド文字クラス "blank" に属する
ワイド文字ならば 0 でない値を返す。それ以外の場合には 0 を返す。
.\"O .SH "CONFORMING TO"
.SH 準拠
POSIX.1-2001.
.\"O .SH NOTES
.SH 注意
.\"O The behavior of
.\"O .BR iswblank ()
.\"O depends on the
.\"O .B LC_CTYPE
.\"O category of the
.\"O current locale.
.BR iswblank ()
の動作は、現在のロケールの
.B LC_CTYPE
カテゴリに依存する。
.\"O .SH "SEE ALSO"
.SH 関連項目
.BR isblank (3),
.BR iswctype (3)
