.\" Copyright 1993 David Metcalfe (david@prism.demon.co.uk)
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.\" References consulted:
.\"     Linux libc source code
.\"     Lewine's _POSIX Programmer's Guide_ (O'Reilly & Associates, 1991)
.\"     386BSD man pages
.\"	Single UNIX Specification, Version 2
.\" Modified Thu Apr  8 15:00:12 1993, David Metcalfe
.\" Modified Sat Jul 24 18:44:45 1993, Rik Faith (faith@cs.unc.edu)
.\" Modified Fri Feb 14 21:47:50 1997 by Andries Brouwer (aeb@cwi.nl)
.\" Modified Mon Oct 11 11:11:11 1999 by Andries Brouwer (aeb@cwi.nl)
.\" Modified Wed Nov 10 00:02:26 1999 by Andries Brouwer (aeb@cwi.nl)
.\" Modified Sun May 20 22:17:20 2001 by Andries Brouwer (aeb@cwi.nl)
.\"
.\" Japanese Version Copyright (c) 1997 HIROFUMI Nishizuka
.\"	all rights reserved.
.\" Translated 1997-12-19, HIROFUMI Nishizuka <nishi@rpts.cl.nec.co.jp>
.\" Updated 2000-06-18, Kentaro Shirakata <argrath@ub32.org>
.\" Updated 2005-11-19, Akihiro MOTOKI <amotoki@dd.iij4u.or.jp>
.\"
.TH PUTENV 3  2007-07-26 "GNU" "Linux Programmer's Manual"
.\"O .SH NAME
.SH 名前
.\"O putenv \- change or add an environment variable
putenv \- 環境変数の変更または追加
.\"O .SH SYNOPSIS
.SH 書式
.nf
.B #include <stdlib.h>
.sp
.BI "int putenv(char *" string );
.\" Not: const char *
.fi
.sp
.in -4n
.\"O Feature Test Macro Requirements for glibc (see
.\"O .BR feature_test_macros (7)):
glibc 向けの機能検査マクロの要件
.RB ( feature_test_macros (7)
参照):
.in
.sp
.BR putenv ():
_SVID_SOURCE || _XOPEN_SOURCE
\"O .SH DESCRIPTION
.SH 説明
.\"O The
.\"O .BR putenv ()
.\"O function adds or changes the value of environment
.\"O variables.
.\"O The argument \fIstring\fP is of the form \fIname\fP=\fIvalue\fP.
.BR putenv ()
関数は、環境変数の追加または値の変更を行う。
引数 \fIstring\fP は \fIname\fP=\fIvalue\fP という形式を取る。
.\"O If \fIname\fP does not already exist in the environment, then
.\"O \fIstring\fP is added to the environment.
.\"O If \fIname\fP does exist,
.\"O then the value of \fIname\fP in the environment is changed to
.\"O \fIvalue\fP.
\fIname\fP が環境に存在しない場合は \fIstring\fP が環境に追加される。
\fIname\fP が環境に存在する場合は \fIname\fP の値は \fIvalue\fP に変更される。
.\"O The string pointed to by \fIstring\fP becomes part of the environment,
.\"O so altering the string changes the environment.
\fIstring\fP が指している文字列は環境の一部となるので、
文字列を変更すると環境も変更される。
.\"O .SH "RETURN VALUE"
.SH 返り値
.\"O The
.\"O .BR putenv ()
.\"O function returns zero on success,
.\"O or nonzero if an error occurs.
.BR putenv ()
関数は、成功した場合 0 を、
エラーが発生した場合 0 以外を返す。
.\"O .SH ERRORS
.SH エラー
.TP
.B ENOMEM
.\"O Insufficient space to allocate new environment.
新しい環境を割り当てるのに十分な空きがない。
.SH 準拠
SVr4, POSIX.1-2001, 4.3BSD.
.\"O .SH NOTES
.SH 注意
.\"O The
.\"O .BR putenv ()
.\"O function is not required to be reentrant, and the
.\"O one in libc4, libc5 and glibc 2.0 is not, but the glibc 2.1 version is.
.BR putenv ()
はリエントラントであることを求められていない。
libc4, libc5, glibc 2.0 ではリエントラントではない。
glibc 2.1 ではリエントラントである。
.LP
.\"O Description for libc4, libc5, glibc:
libc4, libc5, glibc に関する説明:
.\"O If the argument \fIstring\fP is of the form \fIname\fP,
.\"O and does not contain an \(aq=\(aq character, then the variable \fIname\fP
.\"O is removed from the environment.
もし引数  \fIstring\fP が \fIname\fP 単独で、
\(aq=\(aq 文字を含んでいない場合、環境変数 \fIname\fP は環境から除去される。
.\"O If
.\"O .BR putenv ()
.\"O has to allocate a new array \fIenviron\fP,
.\"O and the previous array was also allocated by
.\"O .BR putenv (),
.\"O then it will be freed.
.\"O In no case will the old storage associated
.\"O to the environment variable itself be freed.
もし
.BR putenv ()
が新しい \fIenviron\fP 配列を確保しなければならない時、
以前の \fIenviron\fP 配列も
.BR putenv ()
によって確保されたものならば、
それは解放される。
環境変数そのものに割り当てられた古い記憶領域が解放されることはない。
.LP
.\"O The libc4 and libc5 and glibc 2.1.2 versions conform to SUSv2:
.\"O the pointer \fIstring\fP given to
.\"O .BR putenv ()
.\"O is used.
libc4 と libc5 と glibc 2.1.2 では SUSv2 に準拠している。
.BR putenv ()
で与えられたポインタ \fIstring\fP が使われる。
.\"O In particular, this string becomes part of the environment;
.\"O changing it later will change the environment.
この文字列は環境の一部となり、後で変更すると環境も変わる。
.\"O (Thus, it is an error is to call
.\"O .BR putenv ()
.\"O with an automatic variable
.\"O as the argument, then return from the calling function while \fIstring\fP
.\"O is still part of the environment.)
(従って、
.BR putenv ()
を自動変数を引数として呼び出し、
\fIstring\fPが環境の一部のままで呼び出した関数から return するとエラーになる)
.\"O However, glibc 2.0-2.1.1 differs: a copy of the string is used.
.\"O On the one hand this causes a memory leak, and on the other hand
.\"O it violates SUSv2.
.\"O This has been fixed in glibc2.1.2.
しかし、glibc 2.0-2.1.1 では異なり、文字列のコピーが使われる。
これはメモリリークを引き起こすだけでなく、 SUSv2 に違反している。
これは glibc2.1.2 で修正された。
.LP
.\"O The 4.4BSD version, like glibc 2.0, uses a copy.
4.4BSD バージョンでは、glibc 2.0 と同様にコピーを使う。
.LP
.\"O SUSv2 removes the \fIconst\fP from the prototype, and so does glibc 2.1.3.
SUSv2 ではプロトタイプから \fIconst\fP が取り除かれており、
glibc 2.1.3 もそのようになっている。
.SH 関連項目
.BR clearenv (3),
.BR getenv (3),
.BR setenv (3),
.BR unsetenv (3),
.BR environ (7)
