#
# Copyright (c) 2021 Linux JM project
#         all rights reserved.
#
PACKAGE_NAME    = meson
PACKAGE_VERSION = 0.57.2
PACKAGE_DATE    = 2021/04/10

AUTHOR_NAME  = "Linux JM project"
AUTHOR_EMAIL = "linuxjm-discuss@lists.osdn.me"

man_numbers = 1
man1_sources = \
	meson

THRESH = 100
EXTFLAGS =
PO4A_FLAGS  = -M UTF-8 -k $(THRESH)
PO4A_FLAGS += $(EXTFLAGS)
LANGS = ja

include po4a.mk
