.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 1999-2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"     GNU printf man page
.\"     man pages are NOT obsolete!
.\"     <ragnar@ragnar-hojland.com>
.TH printf 1 "18 June 2002" "GNU Shell Utilities 2.1"
.SH NAME
printf \- format and print data
.SH SYNOPSIS
.BI printf " format " [ argument... ]
.sp
.B printf [\-\-help] [\-\-version]
.SH DESCRIPTION
.B printf
prints the
.I format
string, interpreting `%' directives and `\e' escapes in the same way
as the C 
.BR printf (3)
function.  The
.I format
argument is re-used as many times as necessary to convert all of the
given 
.IR argument s.
.P
.B printf
recognizes the following escapes to specify the number of the charcter to
print
.IP \e0ooo
Octal number (`ooo' is 0 to 3 digits)
.IP \exhhh
Hexadecimal number (`hhh' is 1 to 3 digits) 
.IP \euNNNN 
Unicode 16-bit code
.IP \eUNNNNNNNN
Unicode 32-bit code
.PP
Unicode is printed according to the LC_CTYPE environment variable, and
requires \fBiconv\fR.
\fBprintf\fR It has an additional escape, `\ec', which causes
it to produce no further output, and an additional directive, `%b',
which prints its argument string with `\e' escapes interpreted the way
they are in the
.I format
string.
.SH OPTIONS
When GNU
.B printf
is invoked with exactly one argument, the following options are recognized:
.TP
.B "\-\-help"
Print a usage message on standard output and exit successfully.
.TP
.B "\-\-version"
Print version information on standard output then exit successfully.
.SH NOTES
Report bugs to bug-sh-utils@gnu.org.
Page updated by Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
