.\" You may copy, distribute and modify under the terms of the LDP General
.\" Public License as specified in the LICENSE file that comes with the
.\" gnumaniak distribution
.\"
.\" The author kindly requests that no comments regarding the "better"
.\" suitability or up-to-date notices of any info documentation alternative
.\" is added without contacting him first.
.\"
.\" (C) 1999-2002 Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
.\"
.\"     GNU whoami man page
.\"     man pages are NOT obsolete!
.\"     <ragnar@ragnar-hojland.com>
.TH whoami 1 "18 June 2002" "GNU Shell Utilities 2.1"
.SH NAME
whoami \- print effective userid
.SH SYNOPSIS
.B whoami
.sp
.B whoami [\-\-help] [\-\-version]
.SH DESCRIPTION
.B whoami
prints the user name associated with the current effective user ID.
It is equivalent to the command `id 
.BR \-un '.
.SH OPTIONS
.TP
.B "\-\-help"
Print a usage message on standard output and exit successfully.
.TP
.B "\-\-version"
Print version information on standard output then exit successfully.
.SH NOTES
Report bugs to bug-sh-utils@gnu.org.
Page updated by Ragnar Hojland Espinosa <ragnar@ragnar-hojland.com>
