.\" -*- nroff -*-
.TH pcibios_present 9 "August 5, 1997" "Linux DDI" "BIOS32 Functions"
.SH NAME
pcibios_present \- determine whether a PCI bus is available
.SH SYNOPSIS
.B #include  <linux/bios32.h>
.sp
.BI "int pcibios_present(void);"
.SH DESCRIPTION
The
.B pcibios_present
tests for the presence of PCI support on the local host. It returns
true (!0) if PCI support exists, false otherwise.
.SH "RETURN VALUE"
Zero if PCI support is NOT present.
.SH AVAILABILITY
Linux 1.0+
.SH "SEE ALSO"
.hlm 0
.na
.BR "/usr/include/linux/bios32.h" ","
.BR "/usr/src/linux/arch/*/kernel/bios32.c"
.ad
.hlm 1
.SH AUTHOR
Kirk Petersen (kirk@speakeasy.org)
.SH BUGS
Bugs?! This is way to trivial to have bugs.
