.\" -*- nroff -*-
.TH pcibios_write_config_word 9 "August 5, 1997" "Linux DDI" "BIOS32 Functions"
.SH NAME
pcibios_write_config_word \- write one word of data to the configuration
space of the PCI bus
.SH SYNOPSIS
.B #include  <linux/bios32.h>
.sp
.BI "int pcibios_write_config_word (unsigned char bus, unsigned char device_fn,\
unsigned char where, unsigned short value);"
.SH DESCRIPTION
The
.B pcibios_write_config_word
function writes one word to the configuration space of the PCI bus.  The
bus can be specified with the
.B bus
parameters.  The
.B device_fn
paramter determines which ? to use.
.B where
is set to the ?.  The word to be written to the configuration space is
stored in the
.B value
parameter.
.SH "RETURN VALUE"
The return value is taken from the PCI controller in a way that I'm
not quite sure of.
.PP
If the PCI system is unavailable, PCIBIOS_FUNC_NOT_SUPPORTED is
returned.
.SH AVAILABILITY
Linux 1.0?
.SH AUTHOR
Kirk Petersen (kirk@speakeasy.org)
.SH BUGS
