#!/usr/bin/perl
#
# $Id: upd_jpman,v 1.3 2001/03/22 16:11:43 nakano Exp $
#
# Synopsis: upd_jpman (JMCVSROOT)
#
# リポジトリのルートを指定して実行すると、FreeBSD jpman の
# アーカイブのルート (man[1-8] が並んでいるディレクトリ)
# から、最新版をコピーするシェルスクリプトを stdout に吐く。
#
require 'jcode.pl';
jcode::euc($_);

#
# speciel rules
#
%rename_table = (
     'man1/g77.1' => 'man1/f77.1',
     'man1/flex.1' => 'man1/lex.1'
);

unless ( -d $ARGV[0] ) {die "$ARGV[0] does not exist\n"};
open (FD, "cat $ARGV[0]/manual/*/translation_list |");
while (<FD>){
	/^ｃ/ || /^Ｃ/ || next;
	chomp;
	@l = split ":";

	$src = "man$l[5]/$l[4].$l[5]";
	if ($rename_table{$src} ne undef) {$src = $rename_table{$src}};
	
	$l[1] =~ s/ /_/g;
	$dst = "$ARGV[0]/manual/$l[1]/contrib/man$l[5]/$l[4].$l[5]";

	print "cp -f $src $dst\n";
}
close(FD);

