.\" Copyright (c) 1993 by Thomas Koenig (ig25@rz.uni-karlsruhe.de)
.\" and Copyright (C) 2014 Michael Kerrisk <mtk.manpages@gmail.com>
.\"
.\" %%%LICENSE_START(VERBATIM)
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\" %%%LICENSE_END
.\"
.\" Modified Sat Jul 24 17:28:34 1993 by Rik Faith <faith@cs.unc.edu>
.\" Modified Sun Jun 01 17:16:34 1997 by Jochen Hein
.\"   <jochen.hein@delphi.central.de>
.\" Modified Thu Apr 25 00:43:19 2002 by Bruno Haible <bruno@clisp.org>
.\"
.\"*******************************************************************
.\"
.\" This file was generated with po4a. Translate the source file.
.\"
.\"*******************************************************************
.\"
.\" Japanese Version Copyright (c) 1997 HANATAKA Shinya
.\"         all rights reserved.
.\" Translated Wed Dec 24 21:08:08 JST 1997
.\"         by HANATAKA Shinya <hanataka@abyss.rim.or.jp>
.\" Modified Thu 14 Nov 2002 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH LOCALE 7 2019\-03\-06 Linux "Linux Programmer's Manual"
.SH 名前
locale \- 多言語サポートの解説
.SH 書式
.nf
\fB#include <locale.h>\fP
.fi
.SH 説明
ロケール (locale) は言語や文化ルールの集合である。 これには、メッセージ出力に使用する言語、 様々な文字集合、
表記に関する慣習などが含まれる。 プログラムをいろいろな文化に移植可能とするには、 プログラムが自分のロケールを判定し、
それに応じた適切な動作ができる必要がある。
.PP
ヘッダーファイル \fI<locale.h>\fP には、 このための便利なデータ型、 関数、 マクロなどの宣言がある。
.PP
このヘッダーファイルで宣言されている関数には、 現在のロケールを設定する \fBsetlocale\fP(3)
と、数値のフォーマット方法についての情報を取得する \fBlocaleconv\fP(3)  がある。
.PP
ロケール情報は、 プログラムが必要とすると思われるいくつかのカテゴリーに分かれており、 それらはマクロとして宣言されている。 これらのマクロを
\fBsetlocale\fP(3) 関数の最初の引き数に用いると、 各カテゴリーを望むロケールに設定できる。
.TP 
\fBLC_ADDRESS\fP (GNU 拡張、 glibc 2.2 以降)
.\" See ISO/IEC Technical Report 14652
場所や地理関連の項目の表示に使用するフォーマット (郵便番号など) に関する設定を変更する。 この情報が必要なアプリケーションは
\fBnl_langinfo\fP(3) を使って非標準の要素を取得できる。 \fB_NL_ADDRESS_COUNTRY_NAME\fP
(指定されたロケールの言語での国名) や \fB_NL_ADDRESS_LANG_NAME\fP (指定されたロケールの言語での言語名) などがあり、
ドイツ語ロケールでは "Deutschland" と "Deutsch" といった文字列が返される。 他の要素名については
\fI<langinfo.h>\fP にリストがある。
.TP 
\fBLC_COLLATE\fP
このカテゴリーは、 並び換え (sorting) や正規表現で使用される照合順序 (collate) を制御する。 その中には、
文字の等価クラスや複数文字の照合順序も含まれる。 このロケールカテゴリーは、 地域的なアルファベット文字列の比較に使用する \fBstrcoll\fP(3)
関数と \fBstrxfrm\fP(3) 関数の動作を変更する。例えばドイツ語のエスツェット (鋭い s)  は、ソートの際 "ss" として扱われる。
.TP 
\fBLC_CTYPE\fP
This category determines the interpretation of byte sequences as characters
(e.g., single versus multibyte characters), character classifications (e.g.,
alphabetic or digit), and the behavior of character classes.  On glibc
systems, this category also determines the character transliteration rules
for \fBiconv\fP(1)  and \fBiconv\fP(3).  It changes the behavior of the character
handling and classification functions, such as \fBisupper\fP(3)  and
\fBtoupper\fP(3), and the multibyte character functions such as \fBmblen\fP(3)  or
\fBwctomb\fP(3).
.TP 
\fBLC_IDENTIFICATION\fP (GNU 拡張、 glibc 2.2 以降)
.\" See ISO/IEC Technical Report 14652
ロケールのメタデータに関連する設定を変更する。 この情報が必要なアプリケーションは \fBnl_langinfo\fP(3)
を使って非標準の要素を取得できる。 \fB_NL_IDENTIFICATION_TITLE\fP (このロケール文書のタイトル) や
\fB_NL_IDENTIFICATION_TERRITORY\fP (このロケール文書が適用される地理的な範囲) などがあり、 "English
locale for the USA" や "USA" といった文字列が返される。 他の要素名については \fI<langinfo.h>\fP
にリストがある。
.TP 
\fBLC_MONETARY\fP
このカテゴリーは、 金額に関連する数値の表示方法を決定する。 \fBlocaleconv\fP(3)  によって返される情報を変更する。
これには小数点や区切りコンマの位置など、 数字の表示方法に関する詳細が含まれている。この情報は \fBstrfmon\fP(3)  関数が内部で使用する。
.TP 
\fBLC_MESSAGES\fP
このカテゴリーは、 メッセージ表示に使用する言語と、 肯定的・否定的な回答をどのように表示するかに影響する。 この情報を簡単に使用するために、 GNU
C ライブラリには \fBgettext\fP(3), \fBngettext\fP(3), \fBrpmatch\fP(3)  関数が含まれている。 GNU
gettext ファミリーに属する関数は、カテゴリーが \fB"C"\fP 以外の有効なロケールに設定されている場合、環境変数 \fBLANGUAGE\fP
にも従う (\fBLANGUAGE\fP はコロン区切りのロケールのリストである)。 このカテゴリーは \fBcatopen\fP(3) の動作にも影響する。
.TP 
\fBLC_MEASUREMENT\fP (GNU 拡張、 glibc 2.2 以降)
ロケールの測定系 (つまり、メートル法かアメリカでよく使われる単位か) に関連する設定を変更する。 この情報が必要なアプリケーションは
\fBnl_langinfo\fP(3) を使って非標準の要素である \fB_NL_MEASUREMENT_MEASUREMENT\fP を取得できる。 この要素は
1 (メートル法) か 2 (アメリカでよく使われる単位) の値が入った文字列へのポインターを返す。
.TP 
\fBLC_NAME\fP (GNU 拡張、 glibc 2.2 以降)
.\" See ISO/IEC Technical Report 14652
人に呼びかける際に使用されるフォーマットに関する設定を変更する。 この情報が必要なアプリケーションは \fBnl_langinfo\fP(3)
を使って非標準の要素を取得できる。 \fB_NL_NAME_NAME_MR\fP (男性に対する一般的な呼び掛け) や \fB_NL_NAME_NAME_MS\fP
(女性に対する一般的な呼び掛け) などがあり、 ドイツ語ロケールでは "Herr" や "Frau" といった文字列が返される。 他の要素名については
\fI<langinfo.h>\fP にリストがある。
.TP 
\fBLC_NUMERIC\fP
このカテゴリーは、 金額に関係しない数値で使用される表示方法を決定する。 例えば、 1000 単位の区切り文字や小数点文字
(ほとんどの英語圏の国ではピリオドを使用するが、 多くの他の地域ではカンマを使用する)。 このカテゴリーは \fBprintf\fP(3),
\fBscanf\fP(3), \fBstrtod\fP(3) などの関数の動作に影響する。 この情報は \fBlocaleconv\fP(3)
関数でも読み出すことができる。
.TP 
\fBLC_PAPER\fP (GNU 拡張、 glibc 2.2 以降)
.\" See ISO/IEC Technical Report 14652
標準的な紙のサイズの寸法 (US letter や A4 など) に関する設定を変更する。 この情報が必要なアプリケーションは
\fBnl_langinfo\fP(3) を使って非標準の要素である \fB_NL_PAPER_WIDTH\fP と \fB_NL_PAPER_HEIGHT\fP
を取得できる。 この要素はミリメーター単位の寸法を指定する \fIint\fP 値を返す。
.TP 
\fBLC_TELEPHONE\fP (GNU 拡張、 glibc 2.2 以降)
.\" See ISO/IEC Technical Report 14652
電話サービスで使用されるフォーマットに関する設定を変更する。 この情報が必要なアプリケーションは \fBnl_langinfo\fP(3)
を使って非標準の要素を取得できる。 \fB_NL_TELEPHONE_INT_PREFIX\fP (そのロケールでの電話番号の前に付く国を示す番号)
などがある。 "49" (ドイツの場合) といった文字列が返される。 他の要素名については \fI<langinfo.h>\fP
にリストがある。
.TP 
\fBLC_TIME\fP
このカテゴリーは、 日付と時刻の値に使用される表示方法を制御する。 例えば、 ヨーロッパのほとんどでは 24 時間時計を使用するが、 アメリカでは 12
時間時計を使用する。 このカテゴリーの設定は \fBstrftime\fP(3) や \fBstrptime\fP(3) などの関数の動作に影響する。
.TP 
\fBLC_ALL\fP
上記の全て。
.PP
If the second argument to \fBsetlocale\fP(3)  is an empty string, \fI""\fP, for
the default locale, it is determined using the following steps:
.IP 1. 3
環境変数 \fBLC_ALL\fP が設定されている場合には \fBLC_ALL\fP の値が使用される。
.IP 2.
上記のカテゴリーのどれかと同じ名前の環境変数が設定されている場合には、 そのカテゴリーにはその値が使用される。
.IP 3.
環境変数 \fBLANG\fP が設定されている場合には \fBLANG\fP の値が使用される。
.PP
地域的な数値フォーマットの情報は \fBlocaleconv\fP(3)  関数によって返される \fIstruct lconv\fP
で得ることができ、これは以下のように宣言されている:
.PP
.in +4n
.EX
struct lconv {

    /* (通貨以外の) 数値情報 */

    char *decimal_point;     /* Radix character */
    char *thousands_sep;     /* Separator for digit groups to left
                                of radix character */
    char *grouping;     /* Each element is the number of digits in
                           a group; elements with higher indices
                           are further left.  An element with value
                           CHAR_MAX means that no further grouping
                           is done.  An element with value 0 means
                           that the previous element is used for
                           all groups further left. */

    /* 残りのフィールドは通貨情報用である */

    char *int_curr_symbol;   /* First three chars are a currency
                                symbol from ISO 4217.  Fourth char
                                is the separator.  Fifth char
                                is \(aq\e0\(aq. */
    char *currency_symbol;   /* Local currency symbol */
    char *mon_decimal_point; /* Radix character */
    char *mon_thousands_sep; /* Like \fIthousands_sep\fP above */
    char *mon_grouping;      /* Like \fIgrouping\fP above */
    char *positive_sign;     /* Sign for positive values */
    char *negative_sign;     /* Sign for negative values */
    char  int_frac_digits;   /* International fractional digits */
    char  frac_digits;       /* Local fractional digits */
    char  p_cs_precedes;     /* 1 if currency_symbol precedes a
                                positive value, 0 if succeeds */
    char  p_sep_by_space;    /* 1 if a space separates
                                currency_symbol from a positive
                                value */
    char  n_cs_precedes;     /* 1 if currency_symbol precedes a
                                negative value, 0 if succeeds */
    char  n_sep_by_space;    /* 1 if a space separates
                                currency_symbol from a negative
                                value */
    /* Positive and negative sign positions:
       0 Parentheses surround the quantity and currency_symbol.
       1 The sign string precedes the quantity and currency_symbol.
       2 The sign string succeeds the quantity and currency_symbol.
       3 The sign string immediately precedes the currency_symbol.
       4 The sign string immediately succeeds the currency_symbol. */
    char  p_sign_posn;
    char  n_sign_posn;
};
.EE
.in
.SS "ロケール API の POSIX.1\-2008 での拡張"
POSIX.1\-2008 では、 ロケール API への多くの拡張が標準化されている。 これは GNU C ライブラリのバージョン 2.3
で初めて登場した実装に基づいている。 これらの拡張は、 従来のロケール API
がマルチスレッドアプリケーションや複数のロケールを扱う必要があるアプリケーションとうまく組み合わせて使うことができない問題を解決するために設計された。
.PP
この拡張は、 ロケールオブジェクトの作成、操作のための新しい関数 (\fBnewlocale\fP(3), \fBfreelocale\fP(3),
\fBduplocale\fP(3), \fBuselocale\fP(3)) とサフィックス "_l" が付いた新しいライブラリ関数
(\fBtoupper_l\fP(3) など) で構成される。 新しいライブラリ関数は、 従来のロケール依存の API (\fBtoupper\fP(3) など)
を関数実行時に適用するロケールオブジェクトの指定ができるように拡張したものである。
.SH 環境変数
以下の環境変数が \fBnewlocale\fP(3) と \fBsetlocale\fP(3) で使用される。 したがって、
特権を持たないロケールを参照するすべてのプログラムに影響がある。
.TP 
\fBLOCPATH\fP
A list of pathnames, separated by colons (\(aq:\(aq), that should be used to
find locale data.  If this variable is set, only the individual compiled
locale data files from \fBLOCPATH\fP and the system default locale data path
are used; any available locale archives are not used (see \fBlocaledef\fP(1)).
The individual compiled locale data files are searched for under
subdirectories which depend on the currently used locale.  For example, when
\fIen_GB.UTF\-8\fP is used for a category, the following subdirectories are
searched for, in this order: \fIen_GB.UTF\-8\fP, \fIen_GB.utf8\fP, \fIen_GB\fP,
\fIen.UTF\-8\fP, \fIen.utf8\fP, and \fIen\fP.
.SH ファイル
.TP 
\fI/usr/lib/locale/locale\-archive\fP
通常のデフォルトのロケールアーカイブファイル
.TP 
\fI/usr/lib/locale\fP
コンパイルされたロケールファイルの通常のデフォルトのパス。
.SH 準拠
.\"
.\" The GNU gettext functions are specified in LI18NUX2000.
POSIX.1\-2001.
.SH 関連項目
\fBiconv\fP(1), \fBlocale\fP(1), \fBlocaledef\fP(1), \fBcatopen\fP(3), \fBgettext\fP(3),
\fBiconv\fP(3), \fBlocaleconv\fP(3), \fBmbstowcs\fP(3), \fBnewlocale\fP(3),
\fBngettext\fP(3), \fBnl_langinfo\fP(3), \fBrpmatch\fP(3), \fBsetlocale\fP(3),
\fBstrcoll\fP(3), \fBstrfmon\fP(3), \fBstrftime\fP(3), \fBstrxfrm\fP(3),
\fBuselocale\fP(3), \fBwcstombs\fP(3), \fBlocale\fP(5), \fBcharsets\fP(7),
\fBunicode\fP(7), \fButf\-8\fP(7)
.SH この文書について
この man ページは Linux \fIman\-pages\fP プロジェクトのリリース 5.10 の一部である。プロジェクトの説明とバグ報告に関する情報は
\%https://www.kernel.org/doc/man\-pages/ に書かれている。
