.\" Copyright (c) 1996 Free Software Foundation, Inc.
.\" This program is distributed according to the Gnu General Public License.
.\" See the file COPYING in the kernel source directory
.\"
.TH KSYMS 8 "January 31, 2002" Linux "Linux Module Support"
.SH NAME
ksyms \- display exported kernel symbols.
.SH SYNOPSIS
.B ksyms
[\-ahm]
.SH DESCRIPTION
.B Ksyms
shows information about exported kernel symbols.  The format is
address, name, and defining module.
.SS OPTIONS
.TP
.BR \-a ", " \-\-all
Display all symbols.  By default, symbols from the kernel proper
are suppressed.
.TP
.BR \-h ", " \-\-noheader
Suppress the column header.
.TP
.BR \-H ", " \-\-help
Display a summary of options and exit.
.TP
.BR \-m ", " \-\-info
Display module information.  Includes each module's kernel load address
and size in the listing.
.TP
.BR \-V ", " \-\-version
Display the version of \fBksyms\fR.
.SH SEE ALSO
.BR insmod (8),\  modprobe (8),\  depmod (8),\  rmmod (8),\  lsmod (8).
.SH BUGS
\fBksyms\fR [ \-V | \-\-version ] should exit immediately.  Instead, it
prints the version information and behaves as if no options were given.
.SH HISTORY
The \fBksyms\fR command was first conceived by Bjorn Ekwall <bj0rn@blox.se>
.br
The '\fB\-m\fR' option was inspired by David Hinds
<dhinds@allegro.stanford.edu>
.br
Updated for 2.1.17 by Richard Henderson <rth@tamu.edu>
