.\" Copyright (c) 1996 Free Software Foundation, Inc.
.\" This program is distributed according to the Gnu General Public License.
.\" See the file COPYING in the kernel source directory
.\"
.\" Translated Sun Aug 15 10:56:25 JST 1999
.\"         by FUJIWARA Teruyoshi <fujiwara@linux.or.jp>
.\" Updated Tue Jan 23 JST 2001 by Kentaro Shirakata <argrath@ub32.org>
.\" Updated Fri Mar 15 JST 2002 by Kentaro Shirakata <argrath@ub32.org>
.\"
.TH LSMOD 8 "February 4, 2002" Linux "Linux Module Support"
.SH 名前
lsmod \- ロードされているモジュールの一覧を表示する
.SH 書式
.B lsmod
[-hV]
.SH 説明
.B lsmod
は、全てのロードされているモジュールに関する情報を表示する。
.PP
表示のフォーマットは名前、大きさ、使用カウント数、
参照しているモジュールの一覧である。
表示される情報は /proc/modules から入手できる情報と全く同じである。
.PP
モジュールが自分のアンロードを
.I can_unload
ルーチンを使って制御している場合、
lsmod が表示する使用カウント数は実際の使用カウント数とは関係なく -1 となる。
.SH オプション
.TP
.BR \-h ", " \-\-help
オプションの一覧を表示して直ちに終了する。
.TP
.BR \-V ", " \-\-version
\fBlsmod\fR のバージョンを表示して直ちに終了する。
.SH 関連項目
insmod(8), modprobe(8), depmod(8), rmmod(8), ksyms(8)
.SH 履歴
モジュール対応を誰が最初に考えたのかは不明である。
.br
Linux 用の最初のバージョンは Bas Laarhoven <bas@vimec.nl> が作成した。
.br
バージョン 0.99.14 は Jon Tombs <jon@gtex02.us.es> が作成した。
.br
Bjorn Ekwall <bj0rn@blox.se> が拡張を行った。
.br
バージョン 2.1.17 への更新は Richard Henderson <rth@tamu.edu> が行った。
.br
Bjorn Ekwall <bj0rn@blox.se> が 1999 年 3 月に更新した。
