#
# Copyright (c) 2021 Linux JM project
#         all rights reserved.
#
PACKAGE_NAME    = automake
PACKAGE_VERSION = 1.16.3
PACKAGE_DATE    = 2020/11/19

AUTHOR_NAME  = "Linux JM project"
AUTHOR_EMAIL = "linuxjm-discuss@lists.osdn.me"

man_numbers = 1
man1_sources = \
	aclocal-1.16  \
	aclocal       \
	automake-1.16 \
	automake

THRESH = 100
EXTFLAGS =
PO4A_FLAGS  = -M UTF-8 -k $(THRESH)
PO4A_FLAGS += $(EXTFLAGS)
LANGS = ja

include po4a.mk
