.TH WALL 1 "12 September 2000" "" "Linux User's Manual"
.SH NAME
wall -- send a message to everybody's terminal.
.SH SYNOPSIS
.B wall
.RB [ " message " ]
.SH DESCRIPTION
.B Wall
sends a message to everybody logged in with their \fImesg\fP(1) permission
set to \fByes\fP. The message can be given as an argument to \fIwall\fP, or
it can be sent to \fIwall\fP's standard input. When using the standard input
from a terminal, the message should be terminated with the \fBEOF\fP key
(usually Control-D).
.PP
The length of the message is limited to 20 lines.
.SH NOTES
There is an undocumented (well not anymore..) option, "-n", that
supresses the banner printed by
.I wall .
This is for usage by
.I rwalld
(8).
.I Wall
will not allow you to use that flag if wall is installed set-group-id
and the user executing wall is not root.
.PP
For every invocation of
.I wall
a notification will be written to syslog, with facility LOG_USER and
level LOG_INFO.
.SH ENVIRONMENT
.I Wall
ignores the
.B TZ
variable - the time printed in the banner is based on the systems
local time.
.SH SEE ALSO
mesg(1),
rpc.rwalld(8).
.SH AUTHOR
Miquel van Smoorenburg, miquels@cistron.nl
