include ../JM.rules

all:	build-guide

build-guide:
	bash -x build-jm-guide.sh html

_build/html/index.html:	build-guide

clean:
	bash -x build-jm-guide.sh clean

install:	_build/html/index.html
	rsync -acv --delete _build/html/ $(WWWROOT)/guide
