.\" Nicolai Langfeldt (janl@math.uio.no)
.\" In the public domain.
.\"
.\" Japanese Version Copyright (c) 1999 NAKANO Takeo all rights reserved.
.\" Translated Mon Dec 6 1999 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.\" This man page is a part of util-linux.
.\"
.TH SLN 8 "20 June 1997" "Linux 2.0" "Linux Programmer's Manual"
.\"O .SH NAME
.SH 名前
.\"O sln \- static ln
sln \- スタティックリンクされた ln
.\"O .SH SYNOPSIS
.SH 書式
.BI sln " source dest"
.\"O .SH DESCRIPTION
.SH 説明
.\"O .B sln
.\"O symbolically links 
.\"O .I dest
.\"O to
.\"O .IR source .
.\"O It is statically linked, needing no dynamic linking at all.  Thus
.\"O .B sln
.\"O is useful to make symbolic links to dynamic libraries if the
.\"O dynamic linking system for some reason is nonfunctional.
.B sln
は
.IR dest " を " source
にシンボリックにリンクする。
このコマンドはスタティックにリンクされているので、
実行時のダイナミックリンクは全く必要ない。
したがって
.B sln
は、ダイナミックリンクシステムが何らかの理由で機能しなくなっているときに、
ダイナミックライブラリに対するシンボリックリンクをつくるときに便利である。
.\"O .SH "SEE ALSO"
.SH 関連項目
.\"O .BR ln(1)
.\"O .BR ldconfig(8)
.\"O .BR ld.so(8)
.BR ln (1),
.BR ldconfig (8),
.BR ld.so (8)
.\" .SH AUTHOR
.SH 著者
.\" Mike Parker and David MacKenzie.
Mike Parker と David MacKenzie。
