.\" Copyright (C) 1998 David A. Hinds -- dhinds@pcmcia.sourceforge.org
.\" ftl_check.1 1.6 1999/10/25 19:50:46
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Mon May  1 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH FTL_CHECK 1 "1999/10/25 19:50:46" "pcmcia-cs"
.\"O .SH NAME
.\"O ftl_check \- Flash Translation Layer format checker
.SH 名前
ftl_check \- Flash Translation Layer フォーマットチェッカ
.\"O .SH SYNOPSIS
.SH 書式
.B ftl_check
.I device
.\"O .SH DESCRIPTION
.SH 説明
.\"O .B Ftl_check
.\"O dumps a lot of bookkeeping information for a Flash Translation Layer
.\"O partition.  It needs to access the flash partition's raw character-mode
.\"O device (such as
.\"O .IR /dev/mem0c0c ).
.\"O It cannot actually fix formatting problems.
.B ftl_check
は Flash Translation Layer パーティションの登記情報を大量にダンプする。
.\"nakano: bookkeeping?
flash パーティションの raw character モードデバイス
.RI ( /dev/mem0c0c
など) にアクセスできる必要がある。
実際にフォーマットの問題を修正するわけではない。
.\"O .SH AUTHOR
.SH 著者
David Hinds \- dhinds@pcmcia.sourceforge.org
.\"O .SH "SEE ALSO"
.SH 関連項目
.\"O ftl_format(8).
.BR ftl_format (8)


