.\" Copyright (C) 1998 David A. Hinds -- dhinds@pcmcia.sourceforge.org
.\" ide_info.8 1.5 1999/10/25 19:50:46
.\"
.\" Japanese Version Copyright (c) 2000 NAKANO Takeo all rights reserved.
.\" Translated Sun May 14 2000 by NAKANO Takeo <nakano@apm.seikei.ac.jp>
.\"
.TH IDE_INFO 8 "1999/10/25 19:50:46" "pcmcia-cs"
.\"O .SH NAME
.\"O ide_info \- IDE device description tool
.SH 名前
ide_info \- IDE デバイス記述ツール
.\"O .SH SYNOPSIS
.SH 書式
.B ide_info
.I device
.\"O .SH DESCRIPTION
.SH 説明
.\"O .B Ide_info
.\"O opens the specified IDE device file, and retrieves its device
.\"O identification information.  Its
.\"O output is a set of Bourne-style shell commands to define the
.\"O .BR MODEL ,
.\"O .BR FW_REV ,
.\"O and
.\"O .B SERIAL_NO
.\"O variables based on this information.  The PCMCIA configuration script
.\"O for IDE-type devices uses this utility so that the serial number can
.\"O be used to specify configurations for particular cards.
.B ide_info
は指定した IDE デバイスファイルをオープンし、
デバイスの識別情報を取得する。
このコマンドの出力は、シェル変数
.BR MODEL ", " FM_REV ", " SERIAL_NO
を取り出した情報に基づいて定義する、
Borneシェルのコマンド文字列になっている。
DE 系のデバイス用の PCMCIA 設定スクリプトの中でこのユーティリティを使えば、
シリアル番号を使って特定のカードに対する設定を指定できる。
.\"O .SH AUTHOR
.SH 著者
David Hinds \- dhinds@pcmcia.sourceforge.org

