.ig \"-*- nroff -*-
Copyright (C) 1989-1999 Free Software Foundation, Inc.

Permission is granted to make and distribute verbatim copies of
this manual provided the copyright notice and this permission notice
are preserved on all copies.

Permission is granted to copy and distribute modified versions of this
manual under the conditions for verbatim copying, provided that the
entire resulting derived work is distributed under the terms of a
permission notice identical to this one.

Permission is granted to copy and distribute translations of this
manual into another language, under the above conditions for modified
versions, except that this permission notice may be included in
translations approved by the Free Software Foundation instead of in
the original English.
..
.\"
.\" Japanese Version Copyright (c) 2001 UCHIDA Norihiro all rights reserved.
.\" Translated Sun Apr 14 2001 by UCHIDA Norihiro <KY4N-UCD@asahi-net.or.jp>
.\"
.TH GROFF_MSAFER 7 "6 February 2000" "Groff Version 1.16.1"
.SH 名前
groff_msafer \- groff -msafer マクロ
.SH 書式
.B groff
.B \-msafer
[
.IR options .\|.\|.
]
[
.IR files .\|.\|.
]
.SH 説明
-msafer マクロは、
.BR open ,
.BR opena ,
.BR pso ,
.BR sy ,
.B pi
リクエストを取り除く。
これらのマクロは、信頼できないソースからの入力を処理するときに
使うべきである。
安全第一を心掛けるなら、コマンドラインの -m オプションで
真っ先に指定すべきである。
通常は、これらのマクロは groff の
.B \-S
オプションによって呼び出される。このオプションは同時に
.B pic
にも
.B \-S
フラグを渡すようになる。
groff の
.B \-S
オプションは、現在はデフォルトの動作となっている。
古い処理方法で動作させたいときには、
.B \-U
フラグを使用する。
.SH ファイル
.B /usr/local/share/groff/tmac/tmac.safer
.SH 関連項目
.BR groff (1),
.BR troff (1),
.BR pic (1)
