name: release archive
on:
  workflow_dispatch:
  schedule:
    - cron: "15 5 15 * *"
jobs:
  release-archive:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        make TMPDIR=./tmp tarball 
    - name: release
      run: |
        today=$(date +'%Y%m%d')
        release_tag="v$today"
        fn="man-pages-ja-$today.tar.gz"
        gh release create $release_tag ./tmp/$fn --title $release_tag --fail-on-no-commits 
      env:
        GH_TOKEN: ${{ github.token }}
