.\" Japanese Version Copyright (c) 1996 Tanoshima Hidetohsi
.\"         all rights reserved.
.\" Dec 31, 1996   Tanoshima Hidetoshi <tano@sainet.or.jp> 
.\"
.TH BASENAME 1L "GNU Shell Utilities" "FSF" \" -*- nroff -*-
.SH 名前
basename \- ファイル名からディレクトリとサフィックスを取り除く。
.SH 書式
.B basename
name [suffix]
.br
.B basename
{\-\-help,\-\-version}
.SH 説明
このマニュアルページはGNUバージョンの
.BR basename
について書いている。
.B basename
コマンドはファイル名
.IR name
からディレクトリ名を取り去る。
.I suffix
が指定されたり、
.IR name
の最後がこれと同一のものだと、
.I name
からこれを取り去る。
.B basename
はその処理をした name を標準出力に表示する。
.SS オプション
.TP
.I "\-\-help"
使用法を標準出力に表示し、終了する。
.TP
.I "\-\-version"
バージョン情報を標準出力に表示し、終了する。
