.\"
.\" Japanese Version Copyright (c) 1997 Atsushi KAMOSHIDA
.\"         all rights reserved.
.\" Translated Mon Feb 10 19:56:44 JST 1997
.\"         by Atsushi KAMOSHIDA <kamop@tsuki.elect.chuo-u.ac.jp>
.TH GROUPS 1L "GNU Shell Utilities" "FSF" \" -*- nroff -*-
.SH 名前
groups \- ユーザーが属しているグループの表示
.SH 書式
.B groups
[username...]
.br
.B groups
{\-\-help,\-\-version}
.SH 説明
このマニュアルページは GNU の
.BR groups
のために書かれた。
.B groups
は
.IR username
で指定されたユーザが属するグループ名を表示する。
引数を省略すると、コマンドを入力したユーザの属するグループ名を
表示する。ユーザ名が指定されたときは、指定されたユーザの属するグルー
プ名を表示する前にそのユーザ名が表示される。
.PP
グループのリストは `id \-Gn' の実行結果に等しくなる。
.SS オプション
GNU の
.B groups
は一つだけ引数が与えられて実行されたとき，以下
のオプションが有効になる。
.TP
.I "\-\-help"
標準出力に使用法を表示し，正常に終了する。
.TP
.I "\-\-version"
バージョンを表示し，正常に終了する。
