.\"    This file documents the GNU shell utilities.
.\"
.\"    Copyright (C) 1994 Free Software Foundation, Inc.
.\"
.\"    Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\"    Permission is granted to copy and distribute modified versions of
.\" this manual under the conditions for verbatim copying, provided that
.\" the entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\"    Permission is granted to copy and distribute translations of this
.\" manual into another language, under the above conditions for modified
.\" versions, except that this permission notice may be stated in a
.\" translation approved by the Foundation.
.\"
.\" Japanese Version Copyright (c) 1998 Ueyama Rui
.\"         all rights reserved.
.\" Translated Fri May  1 21:21:18 JST 1998
.\"         by Ueyama Rui <rui@linux.or.jp>
.\"
.TH SLEEP 1 "GNU Shell Utilities" "FSF" \" -*- nroff -*-
.SH 名前
sleep \- 指定された時間だけ停止する。
.SH 書式
.B sleep
[\-\-help] [\-\-version] number[smhd]...
.SH 説明
この文書はもうメンテナンスされていないので、不正確・不完全
かもしれない。現在は texinfo 文書が正式な情報となっている。
.PP
このマニュアルページは GNU 版
.BR sleep
についての説明である。
.B sleep
は、コマンドライン引き数を合計した時間のあいだポーズする。すべての引き数に
時間を示す単位を付けることができる。つけないものは秒単位となる。単位は:
.IP s
秒
.IP m
分
.IP h
時間
.IP d
日
.SS OPTIONS
.TP
.I "\-\-help"
簡単な説明を標準出力に表示して、成功状態で終了する。
.TP
.I "\-\-version"
バージョン情報を標準出力に表示して、成功状態で終了する。
